feat(actions-with-page): removing, changing and replacing nodes in la…
atls-academy/frontend-study-gochicus pull request #11
Opened 2020-12-12 22:37 UTC by gochicus

…yout with functions

ISSUES CLOSED: #10

2020-12-13 09:46 UTC, themetronome requested changes
- именование иконок и изображений - придерживайся одного стиля
- для чего нужен файл ...min.css.map?
- используй чистый css
- не нужно использовать минифицированную версию стилей

2020-12-13 09:46 UTC, themetronome commented on lessons/actions-with-page/package.json
> +  "version": "0.1.0",
https://github.com/Atlantis-Lab/convention
https://semver.org/lang/ru/

2020-12-13 09:46 UTC, themetronome commented on lessons/actions-with-page/src/index.js
> +  let bg = document.querySelector(".promo__bg");
let or const?

2020-12-13 09:46 UTC, themetronome commented on lessons/actions-with-page/src/index.js
> +  let genre = document.querySelector(".promo__genre");
let or const?

2020-12-13 09:46 UTC, themetronome commented on lessons/actions-with-page/src/index.js
> +  let el = document.querySelectorAll(".promo__adv-title ~ img ");
let or const?

2020-12-13 09:46 UTC, themetronome commented on lessons/actions-with-page/src/index.js
> +function removeAdds() {
Наверное ты имел в виду removeAds, от слова - advertisements

2020-12-13 09:46 UTC, themetronome commented on lessons/actions-with-page/src/index.js
> +let filmOrder = movieDB.movies.sort();
Думаю, стоит сделать эту переменную локальной, в рамках функции, где она используется

2020-12-13 17:29 UTC, themetronome requested changes

2020-12-13 17:29 UTC, themetronome commented on lessons/actions-with-page/src/sass/style.scss
> +                background: url('../icons/star.svg') center (center / cover) no-repeat;
Если ты используешь чистый css, зачем тебе scss стили?

2020-12-13 17:58 UTC, themetronome approved these changes

2020-12-15 17:12 UTC, themetronome approved these changes

2020-12-15 19:46 UTC, TorinAsakura approved these changes

2020-12-15 19:47 UTC, merged