feat(events-on-page): eventListenners added to the form and delete icon
atls-academy/frontend-study-gochicus pull request #13
Opened 2020-12-15 19:56 UTC by gochicus

ISSUES CLOSED: #12

2020-12-15 20:37 UTC, themetronome requested changes
Есть вопросы по логическим блокам самого кода, следует немного соотносить их; где объявляешь переменные, где объектный литерал, где реализация функций и тд. Так код читать удобнее и тебе и другим

p.s. опечатка в коммит месседже

2020-12-15 20:37 UTC, themetronome commented on lessons/events-on-page/src/index.js
> +  function createML(films, parent) {
Использование аббревиатур в именовании - сыграет против тебя в будущем

2020-12-15 20:37 UTC, themetronome commented on lessons/events-on-page/src/index.js
> +  bin.forEach((item, i) => {
Почему бы не перебрать итемы из списка рядом с генерацией новых в этот самый список?

2020-12-17 10:04 UTC, themetronome requested changes
Окей, кажется про логические части ты не совсем понял, постараюсь объяснить поподробнее (как это вижу я, более читабельным):
1. Объявляешь литерал объекта, который будет служить своего рода хранилищем данных
2. Объявляешь все переменные в глобальном скоупе, если они необходимы, в которые запишешь нужные dom-элементы(которые в последующем будут использоваться)
3. Реализуешь функции/применяешь методы, которые будут взаимодействовать с объявленными выше переменными/объектами
4. Вызов функций

2020-12-17 10:04 UTC, ad21ewda1231dsa123das12 commented on lessons/events-on-page/README.md
> +* Функция `createML` генерирует список фильмов и сортирует их с помощью функции` sortArr`
Такой функции уже нет, будь внимательнее

2020-12-17 13:24 UTC, themetronome approved these changes

2020-12-17 20:25 UTC, TorinAsakura approved these changes

2020-12-17 20:25 UTC, merged