Feture/product presentation using tabs
atls-academy/frontend-study-gochicus pull request #19
Opened 2020-12-21 20:52 UTC by gochicus

* css classes added by functions activated by eventListenner
#14

2020-12-22 12:39 UTC, themetronome requested changes
1. Опечатка в части <type> коммит месседжа, а так же в <description> "listener" - пишется с одной буквой "n"
2. Внеси, пожалуйста, ясность по коммитам. Почему решил сделать именно так?

2020-12-22 12:39 UTC, themetronome commented on practice/product-presentaiton-using-tabs/package.json
> +
Лишняя строка. Проверяй перед коммитом все конфиги и исходники пока их не так много, и пока не используем линтер

2020-12-22 17:11 UTC, gochicus commented
> 1. Опечатка в части `<type>` коммит месседжа, а так же в `<description>` "listener" - пишется с одной буквой "n"
> 2. Внеси, пожалуйста, ясность по коммитам. Почему решил сделать именно так?

Содержимое у меня было скопировано, revert показался наиболее простым решением.

2020-12-23 11:03 UTC, themetronome commented
> > 1. Опечатка в части `<type>` коммит месседжа, а так же в `<description>` "listener" - пишется с одной буквой "n"
> > 2. Внеси, пожалуйста, ясность по коммитам. Почему решил сделать именно так?
> 
> Содержимое у меня было скопировано, revert показался наиболее простым решением.

Это какой-то общий ответ. Показался простым относительно чего? Что ты хотел сделать с помощью ревёрта?

2020-12-23 11:07 UTC, gochicus commented
> > > 1. Опечатка в части `<type>` коммит месседжа, а так же в `<description>` "listener" - пишется с одной буквой "n"
> > > 2. Внеси, пожалуйста, ясность по коммитам. Почему решил сделать именно так?
> > 
> > 
> > Содержимое у меня было скопировано, revert показался наиболее простым решением.
> 
> Это какой-то общий ответ. Показался простым относительно чего? Что ты хотел сделать с помощью ревёрта?

Я хотел отменить предыдущий коммит и сделать новый, с ребэйс не стал заморачиваться потому что  наличие "отменяющего" коммита в истории не принципиально, заморачиваться и расчищать всю историю не стал. Отменил коммит, поменял названия и сделал новый.

2020-12-23 13:04 UTC, themetronome commented
> > > > 1. Опечатка в части `<type>` коммит месседжа, а так же в `<description>` "listener" - пишется с одной буквой "n"
> > > > 2. Внеси, пожалуйста, ясность по коммитам. Почему решил сделать именно так?
> > > 
> > > 
> > > Содержимое у меня было скопировано, revert показался наиболее простым решением.
> > 
> > 
> > Это какой-то общий ответ. Показался простым относительно чего? Что ты хотел сделать с помощью ревёрта?
> 
> Я хотел отменить предыдущий коммит и сделать новый, с ребэйс не стал заморачиваться потому что наличие "отменяющего" коммита в истории не принципиально, заморачиваться и расчищать всю историю не стал. Отменил коммит, поменял названия и сделал новый.

По части кода вопросов нет. На счёт отменяющего коммита в истории, и опечатках в названиях ветки и коммит месседжа надеюсь ответит @TorinAsakura.

p.s. пожелание от меня - быть более внимательным, старайся осмыслять флоу в котором работаешь, все затыки связаны с этим

2020-12-28 21:34 UTC, TorinAsakura approved these changes

2020-12-29 12:18 UTC, themetronome approved these changes

2020-12-29 18:33 UTC, merged