feat(timer): countdown timer was created using instance of Date and f…
atls-academy/frontend-study-gochicus pull request #22
Opened 2021-01-05 10:28 UTC by gochicus

…uctions calculating difference

affects: @practice/timer-in-page

ISSUES CLOSED: #20

2021-01-05 10:33 UTC, themetronome approved these changes, later dismissed

2021-01-06 17:28 UTC, TorinAsakura requested changes
Дальше даже смотреть не буду

2021-01-06 17:28 UTC, TorinAsakura commented on practice/timer/package.json
> +  "name": "@practice/timer-in-page",
Названия пакета и папки не совпадают

2021-01-07 09:06 UTC, themetronome reviewed
Так, стоп. Тут же конкретная практика по учебному проекту, сервис по доставке еды. Почему у тебя пакет с табами отдельно таймер отдельно. Чем это обусловлено? Или ты просто по инерции сделал? :confused:

2021-01-07 09:41 UTC, gochicus commented
> Так, стоп. Тут же конкретная практика по учебному проекту, сервис по доставке еды. Почему у тебя пакет с табами отдельно таймер отдельно. Чем это обусловлено? Или ты просто по инерции сделал? 😕

Каждый пакет отражает отдельную решенную задачу . Практика по урокам, цельным проектом это не является.

2021-01-07 20:41 UTC, themetronome commented
> > Так, стоп. Тут же конкретная практика по учебному проекту, сервис по доставке еды. Почему у тебя пакет с табами отдельно таймер отдельно. Чем это обусловлено? Или ты просто по инерции сделал? confused
> 
> Каждый пакет отражает отдельную решенную задачу . Практика по урокам, цельным проектом это не является.

Хорошо, а если я тебя попрошу задеплоить весь проект по доставке, с работающими табами, таймером, модальным окном и тд. Как тогда поступить?

2021-01-08 06:19 UTC, gochicus commented
> > > Так, стоп. Тут же конкретная практика по учебному проекту, сервис по доставке еды. Почему у тебя пакет с табами отдельно таймер отдельно. Чем это обусловлено? Или ты просто по инерции сделал? confused
> > 
> > 
> > Каждый пакет отражает отдельную решенную задачу . Практика по урокам, цельным проектом это не является.
> 
> Хорошо, а если я тебя попрошу задеплоить весь проект по доставке, с работающими табами, таймером, модальным окном и тд. Как тогда поступить?

Если ты захочешь увидеть как отрабатывают все четыре задания привязанных к готовой верстке можно деплоить последний готовый пакет, потому что старый код я не убираю, а отделяю комментарием. Я одного не пойму: откуда взялся проект по доставке? Там нет полноценного функционала страницы, просто четыре задачи привязанные к одной верстке. если таков критерий, то и верстка с фильмами должна была идти проектом.

2021-01-08 08:47 UTC, themetronome commented
> > > > Так, стоп. Тут же конкретная практика по учебному проекту, сервис по доставке еды. Почему у тебя пакет с табами отдельно таймер отдельно. Чем это обусловлено? Или ты просто по инерции сделал? confused
> > > 
> > > 
> > > Каждый пакет отражает отдельную решенную задачу . Практика по урокам, цельным проектом это не является.
> > 
> > 
> > Хорошо, а если я тебя попрошу задеплоить весь проект по доставке, с работающими табами, таймером, модальным окном и тд. Как тогда поступить?
> 
> Если ты захочешь увидеть как отрабатывают все четыре задания привязанных к готовой верстке можно деплоить последний готовый пакет, потому что старый код я не убираю, а отделяю комментарием. Я одного не пойму: откуда взялся проект по доставке? Там нет полноценного функционала страницы, просто четыре задачи привязанные к одной верстке. если таков критерий, то и верстка с фильмами должна была идти проектом.

Должна. Вспомни хронологию того, как мы приняли решение о рефакторинге пакетов, когда все лежали в lessons. Проект взялся в разделе курса, весь функционал ты реализовываешь исходя из полученных в разделе знаний и навыков. Что значит "полноценный функционал страницы"?

2021-01-08 09:00 UTC, gochicus commented
> > > > > Так, стоп. Тут же конкретная практика по учебному проекту, сервис по доставке еды. Почему у тебя пакет с табами отдельно таймер отдельно. Чем это обусловлено? Или ты просто по инерции сделал? confused
> > > > 
> > > > 
> > > > Каждый пакет отражает отдельную решенную задачу . Практика по урокам, цельным проектом это не является.
> > > 
> > > 
> > > Хорошо, а если я тебя попрошу задеплоить весь проект по доставке, с работающими табами, таймером, модальным окном и тд. Как тогда поступить?
> > 
> > 
> > Если ты захочешь увидеть как отрабатывают все четыре задания привязанных к готовой верстке можно деплоить последний готовый пакет, потому что старый код я не убираю, а отделяю комментарием. Я одного не пойму: откуда взялся проект по доставке? Там нет полноценного функционала страницы, просто четыре задачи привязанные к одной верстке. если таков критерий, то и верстка с фильмами должна была идти проектом.
> 
> Должна. Вспомни хронологию того, как мы приняли решение о рефакторинге пакетов, когда все лежали в lessons. Проект взялся в разделе курса, весь функционал ты реализовываешь исходя из полученных в разделе знаний и навыков. Что значит "полноценный функционал страницы"?

Так нет же, в курсе он прямо так и говорит, что вам сходу будет трудно такое реализовать и сейчас показываю как сделать вот такое. В частности,  такое он говорит в уроках про табы. По ходу уроков работа в этой же верстке и идет. Можешь привести где сказано, что это реализация проекта на основе полученных знаний? Насчет полного функционала имею в виду, что обычно, когда речь идет о полноценном проекте, то там должны работать и кнопки и события и все, что нужно для реализации. У нас имеется четыре задачи по урокам, привязанным к уже готовой верстке. Как по мне так это отработка упражнений, а не выполненный проект.  Насчет рефакторинга помню только решение, что делаем в отдельных пакетах lessons и practice. Это логично - разные разделы курса.

2021-01-08 21:06 UTC, TorinAsakura requested changes
Помимо всего прочего иконки и статика лежат тупо в папке src, ни assets ни static, а просто в src

2021-01-08 21:06 UTC, TorinAsakura commented on practice/timer/src/index.html
> +                    </div> -->
Закомменченый код не должен отправляться в основную бранчу - верный признак того, что код ещё не готов к релизу

2021-01-11 15:28 UTC, themetronome reviewed
Касаемо рефактора кода пакета всё в порядке, но я по прежнему считаю что оформить практику нужно оформить в виде пакета с сервисом доставки, где ты комплексно применяешь полученные знания. Был бы рад узнать что ближе к истине у @TorinAsakura

2021-01-11 17:54 UTC, TorinAsakura commented
> Касаемо рефактора кода пакета всё в порядке, но я по прежнему считаю что оформить практику нужно оформить в виде пакета с сервисом доставки, где ты комплексно применяешь полученные знания. Был бы рад узнать что ближе к истине у @TorinAsakura

так как код-сплиттингу и наследованию/импорту ESM вы пока не владеете - то, да, только так

Но, практика с пакетами хороша тем, что код из них можно импортировать через зависимости в другой пакет, однако это уже другие вещи и другие миры, а по сему, да - только целостное приложение и только в один пакет

Если пакет нежизнеспособен, его нельзя запустить и протестировать - тогда какой от него толк?

2021-01-14 11:22 UTC, closed without merging