refactor(frontend-study-gochicus): js was converted into ts
atls-academy/frontend-study-gochicus pull request #30
Opened 2021-01-21 10:38 UTC by gochicus

affects: @lessons/how-to-js, @lessons/how-to-use-functions, @lessons/how-to-use-objects,
@lessons/loops-and-conditions, @practice/actions-with-page, @practice/events-in-page,
@practice/food-delivery

ISSUES CLOSED: #24

2021-01-21 11:04 UTC, themetronome submitted a review, later dismissed

2021-01-21 11:13 UTC, themetronome requested changes
Что со скоупом?

2021-01-21 11:30 UTC, gochicus commented
> Что со скоупом?

Весь проект указан в скоупе,  изменения затрагивают все пакеты.  Разве не так нужно?

2021-01-21 11:51 UTC, themetronome commented
> > Что со скоупом?
> 
> Весь проект указан в скоупе, изменения затрагивают все пакеты. Разве не так нужно?

https://github.com/Atlantis-Academy/frontend-study-ikorol/pull/26 - посмотри этот пуллреквест, здесь Ирина допустила такую же ошибку

2021-01-21 11:56 UTC, TorinAsakura requested changes

2021-01-21 11:56 UTC, TorinAsakura commented on lessons/loops-and-conditions/README.md
>  задаётся два вопроса(за искл. первого вопроса).
задаётся два вопроса…за исключением первого вопроса…что за бред?

2021-01-21 11:56 UTC, TorinAsakura commented on lessons/how-to-use-objects/src/index.ts
> +  moviesCount: (): void => {
почему везде протыкан void? у вас функции вообще ничего не возвращают? Совсем ничего? Хорошо подумали?

2021-01-21 11:56 UTC, TorinAsakura commented on practice/actions-with-page/src/index.ts
> +function replaceOrder(): void {
опять 25

2021-01-21 11:56 UTC, TorinAsakura commented on practice/events-on-page/src/index.ts
>      evt.preventDefault();
что такое evt?

2021-01-21 11:56 UTC, TorinAsakura commented on practice/events-on-page/src/index.ts
>    bin.forEach((item, i) => {
что такое i?

2021-01-21 11:56 UTC, TorinAsakura commented on practice/events-on-page/src/index.ts
>      arr.sort();
что такое arr?

2021-01-21 11:56 UTC, TorinAsakura commented on practice/food-delivery/src/index.ts
> +    ".tabheader__item"
что такое tabheader?

2021-01-21 11:56 UTC, TorinAsakura commented on practice/food-delivery/src/index.ts
>      const t = Date.parse(endTime) - now,
что такое t?

2021-01-21 11:56 UTC, TorinAsakura commented on practice/food-delivery/src/index.ts
> +    const seconds: any = timer.querySelector("#seconds");
почему any?

2021-01-21 13:40 UTC, gochicus commented on practice/events-on-page/src/index.ts
>    bin.forEach((item, i) => {
Это просто вопрос на понимание или мне нужно переименовать аргумент, отвечающий за номер обрабатываемого  элемента массива bin?

2021-01-22 08:29 UTC, TorinAsakura requested changes

2021-01-22 08:29 UTC, TorinAsakura commented on lessons/how-to-js/src/index.ts
> +const d: number = +prompt("На сколько оцените его?", "");
https://www.codewithjason.com/variable-name-anti-patterns/
на этом я могу пока закончить

2021-01-23 12:22 UTC, themetronome requested changes

2021-01-23 12:22 UTC, themetronome commented on lessons/how-to-use-functions/src/index.ts
> +      return (personalMoviesDB.movies[lastFilm] = filmRating);
здесь точно должен быть return?

2021-01-23 12:22 UTC, themetronome commented on lessons/how-to-use-objects/src/index.ts
> +        return (personalMoviesDB.movies[lastFilm] = filmRating);
здесь тоже

2021-01-23 15:08 UTC, themetronome approved these changes
С точки зрения "уборки" - код стал чище, явные фрагменты антипаттернов были устранены. Единственное что, не могу в полной мере оценить указания типов в тех или иных местах, т.к. нахожусь в данный момент, примерно на том же уровне понимания. На мой взгляд, в некоторых местах, например с указанием типов полей в объекте через интерфейс выглядит overkill

2021-01-24 14:18 UTC, TorinAsakura commented on lessons/loops-and-conditions/README.md
> + Посредством функции `prompt` в цикле,задаётся два вопроса(за искл. первого вопроса).
Сделай нормальное описание уже

2021-01-24 14:20 UTC, TorinAsakura approved these changes

2021-01-24 14:21 UTC, merged