chore: husky installed, configured in package.json
atls-academy/frontend-study-gochicus pull request #34
Opened 2021-01-25 11:57 UTC by gochicus

ISSUES CLOSED: #31

2021-01-25 12:10 UTC, themetronome requested changes
Это всё хорошо, а где результат внедрения?

2021-01-25 12:35 UTC, gochicus commented
> Это всё хорошо, а где результат внедрения?

Можешь чуть прояснить? Не совсем понял что именно требуется,  я сделал тестовый коммит с ошибкой, он отрабатывает. Рефактор пойдет отдельным заданием.

2021-01-25 12:37 UTC, themetronome commented
> > Это всё хорошо, а где результат внедрения?
> 
> Можешь чуть прояснить? Не совсем понял что именно требуется, я сделал тестовый коммит с ошибкой, он отрабатывает. Рефактор пойдет отдельным заданием.

https://github.com/Atlantis-Academy/frontend-study-gochicus/pull/32#pullrequestreview-574941055

2021-01-25 21:44 UTC, themetronome requested changes
Почему semicolon'ы проставлены? Точно подцепился нужный конфиг?

2021-01-25 22:10 UTC, gochicus commented
> Почему semicolon'ы проставлены? Точно подцепился нужный конфиг?

Кажется, husky слетел.  Ещё потестирую сегодня.

2021-01-28 15:35 UTC, themetronome approved these changes, later dismissed

2021-02-01 11:14 UTC, TorinAsakura requested changes

2021-02-01 11:14 UTC, TorinAsakura commented on practice/food-delivery/src/index.ts
>    // Countdown timer food delivery
комменты в формате JSDoc должны быть

2021-02-01 11:14 UTC, TorinAsakura commented on practice/events-on-page/src/index.ts
> +  const bin: NodeListOf<Element> = document.querySelectorAll('.delete')
что такое bin?

2021-02-01 22:39 UTC, themetronome approved these changes, later dismissed

2021-02-02 10:02 UTC, TorinAsakura requested changes

2021-02-02 10:02 UTC, TorinAsakura commented on practice/events-on-page/src/index.ts
> +  binIcon.forEach((item, i) => {
Да бляха! Почему удаление это BIN-то?! Что за жесть?! Почему не назвать просто remove без выпендрёжей?!

2021-02-02 12:46 UTC, themetronome approved these changes

2021-02-02 14:43 UTC, TorinAsakura approved these changes

2021-02-02 14:43 UTC, merged