chore: git automation yml file added
atls-academy/frontend-study-gochicus pull request #38
Opened 2021-02-02 14:55 UTC by gochicus

ISSUES CLOSED: #33

2021-02-02 16:00 UTC, themetronome submitted a review, later dismissed

2021-02-02 17:08 UTC, TorinAsakura requested changes

2021-02-02 17:08 UTC, TorinAsakura commented on .github/workflows/lintcheck.yml
> +        run: yarn lint
newline at end of file…

2021-02-03 10:13 UTC, themetronome submitted a review, later dismissed

2021-02-03 11:39 UTC, TorinAsakura requested changes

2021-02-03 11:39 UTC, TorinAsakura commented on .github/workflows/lintcheck.yml
> +  run:
почему у тебя имя джоба run когда ты в name указал lintcheck?

2021-02-03 12:05 UTC, TorinAsakura commented on .github/workflows/lintcheck.yml
> +  run:
смотри на какую строку я указал…

2021-02-03 12:59 UTC, themetronome approved these changes

2021-02-03 18:50 UTC, TorinAsakura approved these changes

2021-02-03 18:51 UTC, merged