WIP(food-delivery): slider functions added
atls-academy/frontend-study-gochicus pull request #46
Opened 2021-02-15 13:36 UTC by gochicus

affects: @practice/food-delivery

ISSUES CLOSED: #45

2021-02-15 14:23 UTC, themetronome requested changes

2021-02-15 14:23 UTC, themetronome commented on practice/food-delivery/src/index.ts
> +  offerSlides[slideIndex - 1].classList.remove('hide')
что тут должно произойти, и что должно случится для этого?

2021-02-15 14:23 UTC, themetronome commented on practice/food-delivery/src/index.ts
> +  function showSlides(index: number) {
разберись с этой функцией, я полагаю, нужно что-то с ней сделать, чтобы в последствии передать её в обработчики которые навешаны на стрелки

2021-02-16 04:36 UTC, gochicus commented on practice/food-delivery/src/index.ts
> +  offerSlides[slideIndex - 1].classList.remove('hide')
@themetronome  Все равно не понимаю, вроде как корректно отрабатывает именно эа часть, нужные классы удаляются и применяются.

2021-02-16 04:37 UTC, gochicus commented on practice/food-delivery/src/index.ts
> +  function showSlides(index: number) {
@themetronome  проблема в контексте или что? Я как-то теряюсь.

2021-02-16 07:19 UTC, themetronome commented on practice/food-delivery/src/index.ts
> +  function showSlides(index: number) {
> @themetronome проблема в контексте или что? Я как-то теряюсь.

посмотри на функции в обработчике событий стрелок, что они делают, что возвращают

2021-02-16 07:21 UTC, themetronome commented on practice/food-delivery/src/index.ts
> +  offerSlides[slideIndex - 1].classList.remove('hide')
> @themetronome Все равно не понимаю, вроде как корректно отрабатывает именно эта часть, нужные классы удаляются и применяются.

при запуске наверное да, эта часть не должна быть в глобальной области видимости

2021-02-16 10:15 UTC, themetronome approved these changes

2021-02-17 14:38 UTC, TorinAsakura approved these changes

2021-02-17 14:38 UTC, merged