fix(food-delivery): css classes names changed
atls-academy/frontend-study-gochicus pull request #49
Opened 2021-02-18 03:00 UTC by gochicus

affects: @practice/food-delivery

ISSUES CLOSED: #48

2021-02-18 07:14 UTC, themetronome approved these changes, later dismissed

2021-02-18 12:46 UTC, TorinAsakura approved these changes

2021-02-18 12:49 UTC, TorinAsakura requested changes

2021-02-18 12:49 UTC, TorinAsakura commented on practice/food-delivery/src/index.css
>  }
через кеймел slideContent и т.д.

2021-02-18 13:03 UTC, themetronome submitted a review, later dismissed

2021-02-18 14:52 UTC, TorinAsakura requested changes

2021-02-18 14:52 UTC, TorinAsakura commented on practice/food-delivery/public/index.html
> +                    <div class='slideContentDescr'>
что такое Descr?
Slide - parent
Content - child
Descr - modifier
=>
slideContent-descr

2021-02-18 15:11 UTC, themetronome approved these changes, later dismissed

2021-02-18 20:11 UTC, TorinAsakura requested changes

2021-02-18 20:11 UTC, TorinAsakura commented on practice/food-delivery/public/index.html
> +                    <div class='slideContentDescr'>
внимательней…
@themetronome перепроверь

2021-02-19 08:35 UTC, themetronome approved these changes
Проверил, стили после переименования отрабатывают корректно

2021-02-19 12:58 UTC, themetronome requested changes

2021-02-19 12:58 UTC, themetronome commented on practice/food-delivery/public/index.html
> +                    <div class='slideContentDescription'>
Сделай названия модификаторов через дефис, всё то, что идёт до модификатора - камелкейс

2021-02-19 13:35 UTC, themetronome approved these changes

2021-02-19 14:38 UTC, TorinAsakura approved these changes

2021-02-19 14:38 UTC, merged