feat(food-delivery): slider pagination added
atls-academy/frontend-study-gochicus pull request #51
Opened 2021-02-20 17:20 UTC by gochicus

affects: @practice/food-delivery

ISSUES CLOSED: #47

2021-02-21 08:21 UTC, themetronome requested changes

2021-02-21 08:21 UTC, themetronome commented on practice/food-delivery/src/index.css
>  }
Не лепи правила друг к другу

2021-02-21 08:21 UTC, themetronome commented on practice/food-delivery/src/index.css
> +.carouselIndicators {
https://github.com/Atlantis-Academy/frontend-study-ikorol/pull/53#discussion_r579629119

2021-02-21 08:21 UTC, themetronome commented on practice/food-delivery/src/index.css
> +.dot {
https://github.com/Atlantis-Academy/frontend-study-ikorol/pull/53#discussion_r579234240

2021-02-21 08:21 UTC, themetronome commented on practice/food-delivery/src/index.css
> +}
no new line at EOF

2021-02-21 08:21 UTC, themetronome commented on practice/food-delivery/src/index.ts
> +    dotContainer.append(dot)
Вот пример как сливается переменная с правилом, сделай имя класса более конкретным

2021-02-21 13:16 UTC, themetronome approved these changes, later dismissed

2021-02-22 15:10 UTC, TorinAsakura requested changes

2021-02-22 15:10 UTC, TorinAsakura commented on practice/food-delivery/src/index.css
> +.currentDot {
-> sliderDor-current

2021-02-22 15:21 UTC, TorinAsakura approved these changes

2021-02-22 20:53 UTC, TorinAsakura approved these changes

2021-02-22 20:53 UTC, merged