feat(food-delivery): code-splitting using webpack
atls-academy/frontend-study-gochicus pull request #54
Opened 2021-02-25 08:44 UTC by gochicus

affects: @practice/food-delivery

ISSUES CLOSED: #52

2021-02-25 08:55 UTC, themetronome requested changes

2021-02-25 08:55 UTC, themetronome commented on package.json
> +    "webpack-cli": "^4.5.0"
Нужны ли в корне эти зависимости?

2021-02-25 08:55 UTC, themetronome commented on practice/food-delivery/src/modules/modalWindow.ts
> +export { closeModal }
Почему выбрал такой способ экспорта?

2021-02-25 08:55 UTC, themetronome commented on package.json
> +    "compile": "tsc",
Получается, что у тебя в корне скрипты относящиеся(примерно) к одному пакету. Например, если в другом пакете ты будешь использовать parcel, а ещё в одном rollup и тд. Неужели все скрипты бандлеров будут тут?

2021-02-25 09:01 UTC, gochicus commented on practice/food-delivery/src/modules/modalWindow.ts
> +export { closeModal }
@themetronome  когда разбирался попалась статья https://basarat.gitbook.io/typescript/main-1/defaultisbad, а поскольку я подозреваю, что переименования мне делать таки придется, аргументы показались убедительными

2021-02-25 09:15 UTC, themetronome submitted a review, later dismissed

2021-02-28 10:29 UTC, TorinAsakura requested changes

2021-02-28 10:29 UTC, TorinAsakura commented on practice/food-delivery/src/modules/menuCards.ts
> +function menu() {
зачем тут функция когда внутри класс?

2021-02-28 10:29 UTC, TorinAsakura commented on practice/food-delivery/src/modules/menuCards.ts
> +  class MenuCard {
Что я говорил про классы?

2021-02-28 10:29 UTC, TorinAsakura commented on practice/food-delivery/src/modules/countdownTimer.ts
> +function countdownTimer(id: string, deadline: string) {
Тебе для обёртки нужна функция?

2021-02-28 11:00 UTC, gochicus commented on practice/food-delivery/src/modules/menuCards.ts
> +  class MenuCard {
@TorinAsakura  что то не припомню, а в чем именно проблема?

2021-02-28 11:00 UTC, gochicus commented on practice/food-delivery/src/modules/countdownTimer.ts
> +function countdownTimer(id: string, deadline: string) {
@TorinAsakura  В общем, да. Можно подробнее что не так?

2021-02-28 11:14 UTC, themetronome commented on practice/food-delivery/src/modules/menuCards.ts
> +  class MenuCard {
> Что я говорил про классы?

Что не используются практически, это всё те же какрточки на классах. Тут задача в разбивке кода :thinking:

2021-03-01 15:09 UTC, themetronome requested changes
Попробуй не использовать функции обёртки во всех модулях. Экспортируй только функции использование которых реально нужно в других частях проекта

2021-03-01 17:01 UTC, ad21ewda1231dsa123das12 commented on practice/food-delivery/src/modules/menuCards.ts
> +export default MenuCard
@TorinAsakura помоги пожалуйста, есть ли смысл в дефолтном импорте? (например ситуация в которой нам нужно будет унаследоваться от класса в другой части пакета)

2021-03-02 06:38 UTC, themetronome commented on practice/food-delivery/src/modules/menuCards.ts
> +export default MenuCard
@gochicus я думаю, что смешивать экспорты не очень хорошая идея, а поскольку ты используешь **menuRender** для отрисовки экспортируй только эту функцию `export function foo()...`

2021-03-02 07:07 UTC, themetronome approved these changes

2021-03-02 08:37 UTC, TorinAsakura approved these changes

2021-03-02 08:37 UTC, merged