refactor(refactor): code refactored using new ES features
atls-academy/frontend-study-gochicus pull request #57
Opened 2021-02-28 09:43 UTC by gochicus

affects: @practice/refactor

ISSUES CLOSED: #55

2021-02-28 09:51 UTC, TorinAsakura approved these changes

2021-02-28 10:10 UTC, themetronome requested changes

2021-02-28 10:10 UTC, ad21ewda1231dsa123das12 commented on practice/refactor/public/index.html
> +</html>
newline EOF

2021-02-28 10:10 UTC, themetronome commented on practice/refactor/src/base.js
> +makeBusiness.apply(null, ['Sam', null, money, employersNames]); */
В этом нет необходимости, по `index.ts` понятно какие части отрефачены

2021-02-28 10:10 UTC, themetronome commented on practice/refactor/README.md
> +* Код из `base.js` переписан с использованием нововведений ES6+
Лучше опиши то как заюзать твоё "консольное приложение" :)

2021-02-28 10:21 UTC, gochicus commented on practice/refactor/README.md
> +* Код из `base.js` переписан с использованием нововведений ES6+
@themetronome  Нормально будет если я просто перечислю что отрефакторил?  Так то это просто абстрактная задача, само задание состояло именно в рефакторинге легаси кода.

2021-02-28 10:27 UTC, themetronome commented on practice/refactor/README.md
> +* Код из `base.js` переписан с использованием нововведений ES6+
> @themetronome  Нормально будет если я просто перечислю что отрефакторил?  Так то это просто абстрактная задача, само задание состояло именно в рефакторинге легаси кода.

Опиши просто как этим пакетом пользоваться. Задача абстрактная, но надо знать как этот код запустить. Представь, что код уже был написан, а ты просто сделал его современнее

2021-02-28 10:30 UTC, TorinAsakura requested changes

2021-02-28 10:30 UTC, TorinAsakura commented on practice/refactor/src/base.js
> +/*
почему весь блок закоменчен?

2021-02-28 10:32 UTC, gochicus commented on practice/refactor/src/base.js
> +/*
@TorinAsakura  это и есть задача, тот код который нужно было отрефакторить.

2021-02-28 11:54 UTC, themetronome requested changes

2021-02-28 11:54 UTC, themetronome commented on practice/refactor/public/index.html
> +<script src = ../src/index.js></script>
А ты точно проверил работоспособность на странице? :confused:

2021-02-28 11:54 UTC, themetronome commented on practice/refactor/src/index.ts
> +    return sum + currentValue
В данном случае ты можешь задать стрелочную функцию в одну строку и не указывать явно return

2021-02-28 12:07 UTC, gochicus commented on practice/refactor/public/index.html
> +<script src = ../src/index.js></script>
@themetronome Не тот конфиг в ветке, да. А так всё работает. Сейчас закину.

2021-02-28 12:09 UTC, gochicus commented on practice/refactor/src/index.ts
> +    return sum + currentValue
@themetronome  eslint требует для метода

2021-03-01 08:46 UTC, themetronome requested changes

2021-03-01 08:46 UTC, themetronome commented on practice/refactor/.eslintrc.json
> +    "prefer-const": 0,
Нет необходимости вводить это правило, просто используй const если не перезаписываешь значение переменной. Если не ошибаюсь, если eslint проходится с флагом --fix, он сам исправляет let на const

2021-03-01 08:46 UTC, themetronome commented on practice/refactor/.eslintrc.json
> +    "eqeqeq": 0,
Тоже самое, можно просто не использовать сравнение с приведением типов. Как я вижу, линтер уже поправил оператор сравнения

2021-03-01 08:46 UTC, themetronome commented on practice/refactor/tsconfig.json
> +}
outDir поставь назад dist

2021-03-01 08:46 UTC, themetronome commented on practice/refactor/public/index.html
> +<script src = ../src/index.js></script>
@gochicus поправь путь в подключении скрипта, а именно добавь кавычки. моя ошибка, не знал что браузер сам доставляет их. поправь конфиг на тот что был, пусть он компилится в dist, с ним всё в порядке

2021-03-01 15:12 UTC, themetronome approved these changes

2021-03-01 15:13 UTC, TorinAsakura approved these changes

2021-03-01 15:13 UTC, merged