Feature/web diary
atls-academy/frontend-study-gochicus pull request #65
Opened 2021-03-26 07:21 UTC by gochicus

2021-03-29 15:02 UTC, TFK70 requested changes

2021-03-29 15:02 UTC, TFK70 commented on practice/web-diary/package.json
> +  "name": "web-diary",
@practice?

2021-03-29 15:02 UTC, TFK70 commented on practice/web-diary/package.json
> +  "version": "1.0.0",
версии должны начинаться с 0.0.0

2021-03-29 15:02 UTC, TFK70 commented on practice/web-diary/package.json
> +    "@types/react": "^17.0.3",
Типы - дев зависимости
От них нет никакого смысла при установке пакета как зависимость т.к. типизация нужна только при разработке

2021-03-29 15:02 UTC, TFK70 commented on practice/web-diary/ui/layout/src/Box.tsx
> +  position?: string
чтобы не описывать кучу пропсов руками стоит воспользоваться [styled-system](https://styled-system.com/api)
увидел что он тут есть, тогда воспользуйся [типами](https://github.com/Atlantis-Lab/uikit/blob/master/packages/select/src/types.ts#L2) оттуда

2021-03-29 15:02 UTC, TFK70 commented on practice/web-diary/ui/layout/src/Box.tsx
> +  position?: string
да и в целом было бы неплохо держать интерфейсы в отдельном файле, как в той ссылке

2021-03-29 15:02 UTC, TFK70 commented on practice/web-diary/ui/post-add-form/src/index.tsx
> +export default PostAddForm
в индексе не должно быть дефолтных экспортов, сделай так же как ты сделал в layout
и в целом нужно стараться писать в одном стиле

2021-03-29 15:02 UTC, TFK70 commented on practice/web-diary/app-launcher/app/src/App.tsx
> +      <Layout display='flex' flexDirection='column' alignItems='center' margin='0' maxWidth='800'>
display: flex уже есть в дефолт пропсах лейаута

2021-03-29 15:02 UTC, TFK70 commented on practice/web-diary/app-launcher/app/package.json
> +    "lint": "eslint"
должно быть в корне + тут все-таки должен быть actl

2021-03-29 15:02 UTC, TFK70 commented on practice/web-diary/ui/post-add-form/src/index.tsx
> +export default PostAddForm
кстати по смежной причине появляются ворнинги при сборке проекта

2021-03-29 15:08 UTC, TFK70 commented on practice/web-diary/ui/app-header/package.json
> +    "lint": "eslint"
ну соответственно подобное надо бы убрать везде
линт достаточно запустить 1 раз из корня, ему незачем в скриптах в каждом пакете висеть

2021-03-29 15:10 UTC, TFK70 commented on practice/web-diary/ui/button/src/ButtonInfo.tsx
> +  return <button type='button'>{intl.formatMessage(messages.info)}</button>
ни onClick не повесить, ни стилизовать
компонент должен быть гибким и конфигурируемым (в пределах разумного, конечно)

2021-03-29 15:15 UTC, TFK70 commented on practice/web-diary/ui/button/src/ButtonSubmit.tsx
> +  return <button type='submit'>{intl.formatMessage(messages.add)}</button>
Все кнопки отличаются лишь контентом внутри? Не было смысла разбивать их на много разных компонентов, в таком случае
Конструкция
```javascript
const Button = ({ children }) => <button>{children}</button>
```
Способна сгрести все эти компоненты в один универсальный
И да, опять же, children - не все, что должно быть в ее пропсах
Должно быть +-[так](https://github.com/Atlantis-Lab/uikit/blob/master/packages/button/src/Button.tsx#L33)

2021-03-29 15:16 UTC, TFK70 commented on practice/web-diary/ui/button/src/ButtonSubmit.tsx
> +  return <button type='submit'>{intl.formatMessage(messages.add)}</button>
К этому кстати в том числе про второй принцип SOLID: открытости/закрытости
Руководствуйся им при проектировании

2021-03-29 15:20 UTC, TFK70 commented on practice/web-diary/ui/input/src/Input.tsx
> +  return <StyledInput type='text' />
И снова то же самое
Вот понадобится тебе сделать
```javascript
background-color: '#000',
color: '#fff'
```
Неужели нужно будет создавать новый компонент для этого? Его нужно открыть как минимум для модификации

2021-03-29 15:22 UTC, TFK70 commented on practice/web-diary/ui/post-list/src/PostList.tsx
> +      <PostListItem />
А если их нужно будет 4? 50? 100?
Снова очень не гибкий компонент, так не должно быть

2021-03-29 15:28 UTC, TFK70 commented on practice/web-diary/ui/post-status-filter/src/PostStatusFilter.tsx
> +          <ButtonInfo />{' '}
Хардкод
Если есть проблема с пробелами - ее нужно решить в другом месте, другим способом, в лучшем случае - автоматизировать, в крайнем - вынести эту логику в сам баттон. Адаптируй свои компоненты к окружению

2021-03-29 15:35 UTC, TFK70 commented on practice/web-diary/ui/search-panel/src/SearchPanel.tsx
> +  return <Input />
Какой смысл использовать SearchPanel если он абсолютно идентичен инпуту?

2021-03-30 14:37 UTC, TFK70 requested changes

2021-03-30 14:37 UTC, TFK70 commented on practice/web-diary/app-launcher/app/src/App.tsx
> +import { Input }            from '../../../ui/input'
Релятивные пути
Приемущество `'@ui/input` над этим кошмаром очевидно

2021-03-30 14:37 UTC, TFK70 commented on practice/web-diary/ui/button/src/CommonButton.tsx
> +import { ButtonInterface }                         from '../interface/interface'
Типы можно вынести просто в файл types.ts
Ну а при таком подходе папку стоило назвать interfaceS, а файлу с интерфейсом для кнопки более конкретное название

2021-03-30 14:37 UTC, TFK70 commented on practice/web-diary/ui/input/src/Input.tsx
> +  display: block;
https://github.com/Atlantis-Academy/frontend-study-ikorol/pull/66#discussion_r603411408

2021-03-30 14:37 UTC, TFK70 commented on practice/web-diary/ui/input/src/Input.tsx
> +export const Input = ({ text }, { color }) => {
({ text, color }) выглядит приятнее

2021-03-30 14:37 UTC, TFK70 commented on practice/web-diary/ui/post-list/src/PostList.tsx
> +  ' margin-top: 50px;\n' +
Выглядит очень плохо,ничто не мешало стилизовать это так же, как и другие компоненты
И реализовать подобное можно без ul

2021-03-30 14:37 UTC, TFK70 commented on practice/web-diary/ui/post-list-item/src/PostListItem.tsx
> +const ListItem = styled.li('font-size: 1.25 rem \n', 'display: flex \n', 'justify-content: row')
Соотвтственно, так писать не стоит

2021-03-30 14:37 UTC, TFK70 commented on practice/web-diary/ui/post-status-filter/src/PostStatusFilter.tsx
> +import messages         from '../../post-add-form/messages/messages'
Полагаю из-за невнимательности
Путь эквивалентен `../messages/messages`

2021-03-30 14:37 UTC, TFK70 commented on practice/web-diary/package.json
> +    "@app-launcher/app": "0.0.0",
Он тут зачем?

2021-03-30 14:37 UTC, TFK70 commented on practice/web-diary/ui/button/interface/interface.tsx
> +  color?: string
И да, я все еще настаиваю на использовании типов из styled-system)

2021-03-30 20:47 UTC, gochicus commented on practice/web-diary/ui/button/interface/interface.tsx
> +  color?: string
Я пока не готов пользоваться этой автоматизацией, в интерфейсе кнопки прописал ColorProps - получилось, в лэйауте применение этих пропсов вызывает ошибки тайпскрипта, с чем они связаны я даже предположить не берусь.

2021-03-30 21:33 UTC, gochicus commented on practice/web-diary/ui/input/src/Input.tsx
> +export const Input = ({ text }, { color }) => {
Так отчего-то не работает.

2021-03-31 13:14 UTC, TFK70 requested changes

2021-03-31 13:14 UTC, TFK70 commented on practice/web-diary/ui/button/src/CommonButton.tsx
> +export const CommonButton = ({ children, color }) => {
Не могу понять к чему этот компонент
Разве я не могу использовать просто Button?
```javascript
<Button color='aqua'>{'OK'}</Button>
```

2021-03-31 13:14 UTC, TFK70 commented on practice/web-diary/ui/input/src/Input.tsx
> +const StyledInput = styled('input')(() => ({
Компонент по-прежнему очень скудный
Дай возможность его конфигурации снаружи: поменять цвет, размер
Оставь только базовые пропсы которые уж точно нигде менять не нужно будет

2021-03-31 13:14 UTC, TFK70 commented on practice/web-diary/ui/input/src/Input.tsx
> +export const Input = ({ text }) => {
Проп для placeholder лучше и назвать placeholder

2021-03-31 13:14 UTC, TFK70 commented on practice/web-diary/ui/layout/interfaces/LayoutInterface.ts
> +export interface Row {
Тогда к чему было выносить все типы в отдельную директорию если все интерфейсы все-равно смешаны в одном файле? Проще уж было на том же уровне файл types.ts создать и скинуть все туда - тогда это можно понять
При таком подходе интерфейсы нужно декомпозировать. Вынеси каждый интерфейс в свой файл, так же намного удобнее будет ориентироваться

2021-03-31 13:14 UTC, TFK70 commented on practice/web-diary/ui/layout/interfaces/LayoutInterface.ts
> +export interface Row {
НО, так же создай index и экспортируй все интерфейсы через него
Это необходимо для того чтобы избежать дублирования:
```javascript
import { LayoutInterface } from './interfaces/LayoutInterface'
import { BoxInterface } from './interfaces/BoxInterface'
```
С индекс файликом будет так:
```javascript
import { LayoutInterface,BoxInteface } from './interfaces'
```

2021-03-31 13:14 UTC, TFK70 commented on practice/web-diary/ui/layout/interfaces/LayoutInterface.ts
> +export const boxSizing = system({
И зачем он здесь?

2021-03-31 13:14 UTC, TFK70 commented on practice/web-diary/ui/layout/src/index.tsx
> +import { Box }    from './Box'
Если ты не используешь дефолтные экспорты - в этой конструкции нет необходимости
Можно просто сделать так:
```javascript
export * from './Layout'
```

2021-03-31 13:14 UTC, TFK70 commented on practice/web-diary/ui/post-list/src/PostList.tsx
> +  margin-top: 10px;
Это тоже нужно описать js-объектом, как я раньше уже упоминал

2021-04-01 12:40 UTC, gochicus commented on practice/web-diary/ui/button/src/CommonButton.tsx
> +export const CommonButton = ({ children, color }) => {
@TFK70 Не совсем понял, Button просто стилизованная кнопка, а вынес в отдельный файл потому-что eslint выдает ошибку из-за пропса color и color в Button.

2021-04-01 12:42 UTC, gochicus commented on practice/web-diary/ui/layout/src/index.tsx
> +import { Box }    from './Box'
@TFK70  Этот момент тоже непонятен, я ж использую именованные экспорты.  Зачем экспортировать всё чеерз звездочку?

2021-04-01 12:44 UTC, TFK70 commented on practice/web-diary/ui/button/interface/interface.tsx
> +  color?: string
> @TFK70 Я пока не готов пользоваться этой автоматизацией, в интерфейсе кнопки прописал ColorProps - получилось, в лэйауте применение этих пропсов вызывает ошибки тайпскрипта, с чем они связаны я даже предположить не берусь.
> 
> UPD. Ещё интересней, то что работало с ColorProps ( цвета применялись) вдруг перестало работать, не смог сделать коммит, так как вновь появилась ошибка тайпскрипт на ColorProps

Опиши более подробно, приложи логи, свои действия

2021-04-01 13:22 UTC, TFK70 commented on practice/web-diary/ui/layout/src/index.tsx
> +import { Box }    from './Box'
> @TFK70 Этот момент тоже непонятен, я ж использую именованные экспорты. Зачем экспортировать всё чеерз звездочку?

Звездочка абсолютно идентична текущей конструкции, она только сократит код в 2 раза

2021-04-01 14:03 UTC, TFK70 requested changes

2021-04-01 14:03 UTC, TFK70 commented on practice/web-diary/ui/input/src/Input.tsx
> +import { InputCSS }                     from './Types'
Почему файл с заглавной буквы-то?
И что значит InputCSS? Ты описываешь типы для пропсов инпута, а не для css

2021-04-02 07:06 UTC, TFK70 requested changes

2021-04-02 07:06 UTC, TFK70 commented on practice/web-diary/app-launcher/app/src/App.tsx
> +          <PostListItem />
Насчет этого я уже писал, если не ошибаюсь
Эта логика должна быть вынесена внутрь PostList. Создание/конфигурация итемов должна происходить через изменение пропсов PostList

2021-04-02 07:06 UTC, TFK70 commented on practice/web-diary/ui/app-header/src/AppHeader.tsx
> +      <h2>{intl.formatMessage(messages.header)}</h2>
Здесь h2, в другом месте h1, в третьем месте h3. Создай для текста отдельный компонент Text и производи стилизацию текста через пропсы. Так намного проще сохранить единый стиль кода и зарегламентировать все возможные стилизации текста

2021-04-02 07:06 UTC, TFK70 commented on practice/web-diary/ui/post-add-form/src/PostAddForm.tsx
> +          <CommonButton color='black'>{intl.formatMessage(messages.add)}</CommonButton>
От CommonButton тоже нужно избавиться, он ничем не отличается от обычного Button

2021-04-02 07:06 UTC, TFK70 commented on practice/web-diary/ui/post-list/src/PostList.tsx
> +  return <List>{children}</List>
Как раз здесь и нужно описать логику создания итемов, а не делать это снаружи

2021-04-02 07:21 UTC, gochicus commented on practice/web-diary/ui/post-add-form/src/PostAddForm.tsx
> +          <CommonButton color='black'>{intl.formatMessage(messages.add)}</CommonButton>
@TFK70 Я не знаю как props children передать в Button

2021-04-02 07:38 UTC, TFK70 commented on practice/web-diary/ui/post-add-form/src/PostAddForm.tsx
> +          <CommonButton color='black'>{intl.formatMessage(messages.add)}</CommonButton>
> @TFK70 Я не знаю как props children передать в Button

В смысле?
```javascript
<Button color='black'>{intl.formatMessage(messages.add)}</Button>
```
Достаточно везде, CommonButton поменять на Button

2021-04-02 07:43 UTC, TFK70 commented on practice/web-diary/ui/post-add-form/src/PostAddForm.tsx
> +          <CommonButton color='black'>{intl.formatMessage(messages.add)}</CommonButton>
@gochicus в uikit делается прослойка в виде еще одного компонента:
```javascript
const StyledButton = styled('button')((styles) => {...styles})

const Button = ({children, ...props}) => <StyledButton {...props}>{children}</Button>

export default Button
```
В твоем случае кнопка экспортируется напрямую:
```javascript
const StyledButton = styled('button')((styles) => {...styles})

export default StyledButton
```
Только вместо StyledButton она называется Button
Тут вообще никаких проблем нет

2021-04-02 07:44 UTC, gochicus commented on practice/web-diary/ui/post-add-form/src/PostAddForm.tsx
> +          <CommonButton color='black'>{intl.formatMessage(messages.add)}</CommonButton>
Ок, понял.

2021-04-02 09:32 UTC, TFK70 requested changes

2021-04-02 09:32 UTC, TFK70 commented on practice/web-diary/ui/button/src/Button.tsx
> +import { ButtonInterface }                from './types'
ButtonProps
Ни к чему приписывать Interface, это и так понятно что в файле types кроме интерфейсов ничего быть не может, но вот подписать что именно он описывает - не помешает

2021-04-02 09:32 UTC, TFK70 commented on practice/web-diary/ui/input/src/Input.tsx
> +  { border },
Это как?

2021-04-02 09:32 UTC, TFK70 commented on practice/web-diary/ui/post-list/src/PostList.tsx
> +const diary: { post: string; id: number }[] = [
diary должен приходить извне
В данном случае зона ответственности твоего компонента размывается + он не поддается конфигурации
Твоя задача - описать шаблон компонента. Представь что помимо тебя этим компонентом будут пользоваться другие разрабы для верстки своих страниц, а там контекст совсем другой

2021-04-02 09:32 UTC, TFK70 commented on practice/web-diary/ui/post-list/src/PostList.tsx
> +        <Layout justifyContent='space-around'>
Зачем это описывать вручную?
У тебя же был компонент PostListItem.  Можно было поставить его сюда как зависимость, ничего плохого в этом нет, скорее наоборот

2021-04-02 10:38 UTC, TFK70 requested changes

2021-04-02 10:38 UTC, TFK70 commented on practice/web-diary/ui/button/src/Button.tsx
> +import { ButtonChildrenAndColor }         from './types'
Ну это слишком конкретно
Если тебе понадобится добавить в пропсы border - придется переименовываться в ButtonChildrenAndColorWithBorder?)
Просто BorderProps более чем достаточно

2021-04-02 10:38 UTC, TFK70 commented on practice/web-diary/ui/post-list/src/PostList.tsx
> +import { PostListItem } from '../../post-list-item'
Снова релятивные импорты?

2021-04-02 10:38 UTC, TFK70 commented on practice/web-diary/ui/post-list/src/PostList.tsx
> +import { Diary }        from './Diary'
Нет-нет-нет, я не это имел ввиду
Под "компонентом" подразумевается весь пакет `@ui/post-list`. Единственное за что он должен отвечать - за представление данных, которые ему предоставляют. В этом случае данные предоставляются через пропсы, твой компонент не должен ничего знать о том, что в него войдет, но должен с помощью типизации говорить о том,  в каком виде эти данные нужно предоставлять

2021-04-02 10:46 UTC, gochicus commented on practice/web-diary/ui/post-list/src/PostList.tsx
> +import { Diary }        from './Diary'
@TFK70  Как то слабо себе представляю реализацию, можешь примерно обозначить где значение пропса быть должно?

2021-04-02 10:48 UTC, TFK70 commented on practice/web-diary/ui/post-list/src/PostList.tsx
> +import { Diary }        from './Diary'
> @TFK70 Как то слабо себе представляю реализацию, можешь примерно обозначить где значение пропса быть должно?

В смыысле?
Пропсы для компонента можно определить только в одном месте, оттуда ты этот diary и возьмешь
Ты будешь его прокидывать как атрибут <PostList diary{{...}} />

2021-04-02 10:59 UTC, gochicus commented on practice/web-diary/ui/post-list/src/PostList.tsx
> +import { Diary }        from './Diary'
@TFK70 Вот есть у меня пропс в  PostListItem,  он получал значение пропсав PostList, а если  в  PostList просто пропс, откуда должен получать значение PostListItem?

2021-04-02 11:07 UTC, TFK70 commented on practice/web-diary/ui/post-list/src/PostList.tsx
> +import { Diary }        from './Diary'
> @TFK70 Вот есть у меня пропс в PostListItem, он получал значение пропсав PostList, а если в PostList просто пропс, откуда должен получать значение PostListItem?

Снова ничего не понял, но предполагаю что ты про пробрасывание пропсов вниз по дереву, если да - то это нормально
Думаю будет странно если я тебе готовый кусок кода напишу, тут вполне можно самому все сделать если немного внимательнее быть

Пропсы - это всего лишь аргумент функции который по дефолту объект. Ты можешь делать с ним все, что угодно

2021-04-02 12:41 UTC, TFK70 requested changes

2021-04-02 12:41 UTC, TFK70 commented on practice/web-diary/app-launcher/app/src/App.tsx
> +const Background = styled('div')(() => ({
А почему он здесь? Это отдельный компонент

2021-04-02 12:41 UTC, TFK70 commented on practice/web-diary/ui/app-header/src/AppHeader.tsx
> +const AppHeader = () => {
Теперь пора вынести подобные компоненты в components
Они слишком привязаны к контексту для ui

2021-04-02 12:41 UTC, TFK70 commented on practice/web-diary/ui/app-header/src/AppHeader.tsx
> +const AppHeader = () => {
И он не один здесь такой

2021-04-02 12:41 UTC, TFK70 commented on practice/web-diary/ui/layout/src/Layout.tsx
> +export const Row = styled.div<RowType>(layout, space, flexbox, position)
Не видел чтобы ты его использовал где-то

2021-04-02 12:41 UTC, TFK70 commented on practice/web-diary/ui/post-list/src/PostList.tsx
> +        <PostListItem> {item.post}</PostListItem>
Так обычно не делают
Передай item.post пропом в PostListItem и обработай его внутри айтема:
```javascript
<PostListItem content={item.post} />
```

2021-04-02 13:30 UTC, TFK70 requested changes

2021-04-02 13:30 UTC, TFK70 commented on practice/web-diary/components/post-list-item/package.json
> +  "name": "@components/post-list-item",
Нет, post-list должен быть в ui
Есть идеи почему?

2021-04-02 13:45 UTC, gochicus commented on practice/web-diary/components/post-list-item/package.json
> +  "name": "@components/post-list-item",
@TFK70 Нет, вообще не вижу логики с точки зрения зависимости от контекста

2021-04-02 15:45 UTC, TFK70 requested changes

2021-04-02 15:45 UTC, TFK70 commented on practice/web-diary/ui/list/src/ListItem.tsx
> +import { Label }       from '@ui/list'
Внутри пакета используй релятивные пути
Такая запись подразумевает что `@ui/list` будет установлен как зависимость, но учитывая что ты уже работаешь в `@ui/list` это невозможно

2021-04-02 15:45 UTC, TFK70 commented on practice/web-diary/ui/list/src/Label.tsx
> +export const Label = styled('span')(() => ({
Label точно должен быть описан в list?
Судя по тому что он стилизует span, Label можно заменить на компонент из `@ui/text`

2021-04-02 15:50 UTC, TFK70 commented on practice/web-diary/ui/list/src/ListItem.tsx
> +import { Label }       from '@ui/list'
Да и если с точки зрения логики подумать: компонент ссылается сам на себя, выглядит странно

2021-04-02 16:04 UTC, TFK70 requested changes

2021-04-02 16:04 UTC, TFK70 commented on practice/web-diary/ui/post-status-filter/package.json
> +  "name": "@ui/filter",
1. Почему пакет пазывается `@ui/filter`, а компонент `PostStatusFilter`?
2. Ему точно место в ui?

2021-04-02 16:10 UTC, gochicus commented on practice/web-diary/ui/post-status-filter/package.json
> +  "name": "@ui/filter",
@TFK70 с названием компонента да, упустил, а в компонетах, пожалуй, да. Это стилизованный див, которй оборачивает кннопки. В идеале, можно опустить фильтр и там же использовать лист, но тут не уверен, логически это другая часть приложения.

2021-04-02 16:19 UTC, TFK70 commented on practice/web-diary/ui/post-status-filter/package.json
> +  "name": "@ui/filter",
> @TFK70 с названием компонента да, упустил, а в ui, пожалуй, да. Это стилизованный див, которй оборачивает кннопки. В идеале, можно опустить фильтр и там же использовать лист, но тут не уверен, логически это другая часть приложения.

В ui у тебя находятся скорее инструменты для создания компонентов, а не сами компоненты. Этот фильтр можно назвать инструментом?

2021-04-02 16:25 UTC, gochicus commented on practice/web-diary/ui/post-status-filter/package.json
> +  "name": "@ui/filter",
@TFK70 Я перенесу его в компоненты,  но, по сути, структурно это тот же лист.

2021-04-02 16:30 UTC, TFK70 commented on practice/web-diary/ui/post-status-filter/package.json
> +  "name": "@ui/filter",
@gochicus я не говорил же прямым текстом переносить его в компоненты, ты в праве сам решить что с ним делать, я просто указал что его текущее состояние вообще ни в какие ворота

2021-04-02 16:46 UTC, TFK70 requested changes

2021-04-02 16:46 UTC, TFK70 commented on practice/web-diary/components/filter/package.json
> +  "name": "@components/filter",
Ты не уловил суть
Фрагменты - не универсальны, они привязаны к контексту и названия у них должны быть соответствующие, конкретизирующие места где они должны использоваться

2021-04-02 16:49 UTC, gochicus commented on practice/web-diary/components/filter/package.json
> +  "name": "@components/filter",
@TFK70 Стоп, мы ведь не используем фрагменты сейчас? При чем тут они?

2021-04-02 16:53 UTC, gochicus commented on practice/web-diary/components/filter/package.json
> +  "name": "@components/filter",
@TFK70  Если я кго в status-filter переименую, будет нормально? У компонента, как мне кажется, нет жесткой привязки к контексту.

2021-04-02 17:02 UTC, TFK70 commented on practice/web-diary/components/filter/package.json
> +  "name": "@components/filter",
@gochicus вот тут ты по-хорошему и должен сам решить как для твоего приложения будет лучше
Ты его вынес в components потому что он реализует конкретный кусок логики
В данном случае он будет фильтровать тудушки и только. Если нам понадобится фильтровать юзеров - придется создавать новый компонент `@components/user-filter` который будет отвечать только за фильтрацию юзеров
Или ты можешь сделать `@ui/filter`, которому будет все-равно что фильтровать: юзеров или тудушки. Он будет делать это основываясь на переданных ему пропсах, а его назначение ты уже будешь определять сам в зависимости от контекста, как тебе удобно

2021-04-02 17:06 UTC, gochicus commented on practice/web-diary/components/filter/package.json
> +  "name": "@components/filter",
@TFK70 тогда возвращаю его обратно в  ui, поскольку тут уловить адекватный контекст для привязки затруднительно. И по структуре он может принять любые инпуты и кнопки.

2021-04-03 07:42 UTC, TFK70 requested changes

2021-04-03 07:42 UTC, TFK70 commented on practice/web-diary/components/switcher-button/package.json
> +  "name": "@components/switcher-button",
Почему button? 
1. Насколько я помню там было больше двух кнопок
2. Название switcher уже подразумевает под собой компонент с каким-то количеством кнопок
3. Раз уж это находится в компонентах - где конкретика в названии? Что именно свитчер переключает?
4. И по-прежнему: ты уверен что это должно быть в components, а не в ui? Ты же можешь сделать универсальный компонент который будет создавать такие свитчеры, примерно как list

2021-04-03 08:46 UTC, gochicus commented on practice/web-diary/components/switcher-button/package.json
> +  "name": "@components/switcher-button",
@TFK70 Именно потому что switcher подразумевает группу toogle, я и указал button  - тип элементов, переключаемых switcher. Да, в компонентах с привязкой к контексту, в этой тудушке универсальный свитчер не нужен.

2021-04-03 08:51 UTC, TFK70 commented on practice/web-diary/components/switcher-button/package.json
> +  "name": "@components/switcher-button",
@gochicus свитчер не подразумевает группу тоггл, это две разные вещи, хоть и похожие
Тоггл - это когда у тебя одна кнопка отвечает за переключение конкретного состояния (вкл/выкл, например)
Свитчер - когда у тебя есть панель из кнопок, каждая из которых отвечает за свое состояние. Это значит что за состояние вкл/выкл у тебя будут отвечать уже две соответствующие кнопки, а не одна

2021-04-03 08:55 UTC, gochicus commented on practice/web-diary/components/switcher-button/package.json
> +  "name": "@components/switcher-button",
@TFK70 ну так тут и есть панель из кнопок, правда одна отвечает за удаление поста.

2021-04-03 09:01 UTC, TFK70 commented on practice/web-diary/components/switcher-button/package.json
> +  "name": "@components/switcher-button",
@gochicus это не просто "панель из кнопок"
Если ты говоришь что это свитчер и он должен переключать состояния - значит там должны быть только кнопки, отвечающие за переключение состояния
Кнопка которая при нажатии удаляет пост - это не состояние, а вот например кнопка, которая помечает пост как прочитанный - это состояние

И я уже написал что означает название switcher-button. Ты называешь элемент в глобальном контексте, как из этого названия я должен понять какое состояние этот свитчер вообще переключает?

2021-04-03 09:02 UTC, TFK70 commented on practice/web-diary/components/switcher-button/package.json
> +  "name": "@components/switcher-button",
@gochicus 
1. Не пренебрегай названиями
2. Не размывай зоны ответственности

2021-04-03 10:07 UTC, TFK70 requested changes

2021-04-03 10:07 UTC, TFK70 commented on practice/web-diary/app-launcher/app/package.json
> +    "@components/switcher-button-status": "0.0.0",
Снова
Мне не стало понятнее какое состояние переключает свитчер. Я уже говорил что свитчер уже подразумевает в себе наличие кнопок, иначе это был бы не свитчер
Это слово status не прояснило абсолютно ничего. Я должен посмотреть на название компонента и хотя бы примерно понять какую задачу он решает

2021-04-03 10:07 UTC, TFK70 commented on practice/web-diary/app-launcher/app/src/App.tsx
> +import { SwitcherButton } from '@components/switcher-button-status'
Название компонента соответственно должно меняться

2021-04-03 10:14 UTC, TFK70 commented
@gochicus опиши здесь почему ты назвал компонент именно так, за что отвечает каждая часть его названия

2021-04-03 10:17 UTC, gochicus commented
@TFK70 Сущность: switcher, элементы в свитчере - button,   что переключают кнопки  статус постов.

2021-04-03 10:20 UTC, TFK70 commented
@gochicus свитчера не может быть без кнопок внутри, зачем мне говорить что у машины есть колеса?

2021-04-03 10:24 UTC, gochicus commented
@TFK70 switcher-post-status

2021-04-03 10:30 UTC, TFK70 commented
@gochicus близко, но если забить switcher-post-status в переводчик то мы получим «статус поста коммутатора»
а если поменять на post-status-switcher то это уже будет «переключатель состояния сообщения»
про инглиш тоже забывать не стоит

2021-04-03 10:31 UTC, TorinAsakura commented
@TFK70 Запрашивая контекст мы должны задавать вопрос: что-где-делает

2021-04-03 10:37 UTC, gochicus commented
@TorinAsakura Вторая попытка

2021-04-03 10:38 UTC, TorinAsakura commented
@gochicus Очень хорошо. Теперь напиши то, что в прошлый раз не ушло

2021-04-03 10:42 UTC, gochicus commented
@TFK70 Так,  ещё вопрос, разве не важнее обозначить сущность в первую очередь?  Или главное, чтобы было понятно?

2021-04-03 10:46 UTC, TFK70 commented
@gochicus если придерживаться шаблона «что-где-делает» - то да, важнее, оставь switcher-post-status

2021-04-03 10:47 UTC, TorinAsakura commented
@TFK70 Это вы там фрагмент колдуете чтоли уже?

2021-04-03 10:49 UTC, TFK70 commented
@TorinAsakura почти
Саша решил не делать компонент switcher в ui и вынести его как конкретный кусок логики в components
вот и придумываем как назвать

2021-04-03 11:04 UTC, TFK70 requested changes

2021-04-03 11:04 UTC, TFK70 commented on practice/web-diary/components/form/package.json
> +  "name": "@components/form",
С этим абсолютно аналогично
что - form
где - ???
делает - ???

2021-04-03 11:21 UTC, TFK70 requested changes

2021-04-03 11:21 UTC, TFK70 commented on practice/web-diary/app-launcher/app/package.json
> +  "name": "@app-launcher/app",
Последний штрих
Зачем тебе app-launcher?
Сделай просто app и назови это @web-diary/app, так будет чище

2021-04-03 11:21 UTC, TFK70 commented on practice/web-diary/app-launcher/app/package.json
> +    "@app-launcher/app": "0.0.0",
И у тебя здесь вроде как цикл зависимостей?

2021-04-03 11:21 UTC, TFK70 commented on practice/web-diary/package.json
> +    "@app-launcher/app": "0.0.0",
И я все еще не понимаю зачем он здесь нужен

2021-04-03 12:00 UTC, TFK70 requested changes

2021-04-03 12:00 UTC, TFK70 commented on practice/web-diary/app-launcher/app/package.json
> +  "name": "@web-diary/app",
Хорошо, но зачем ты сейчас это в app-launcher держишь?
Бессмысленная вложенность, оставь просто папку app

2021-04-03 12:00 UTC, TFK70 commented on practice/web-diary/package.json
> +    "@web-diary/app": "0.0.0",
ну вот зачем тебе здесь эта зависимость?
я уже 3 раз спрашиваю про нее

2021-04-03 12:00 UTC, gochicus commented on practice/web-diary/package.json
> +    "@web-diary/app": "0.0.0",
@TFK70 actl пишет, что нужна

2021-04-03 12:04 UTC, TFK70 commented on practice/web-diary/package.json
> +    "@web-diary/app": "0.0.0",
@gochicus ну правильно, ты же [здесь](https://github.com/Atlantis-Academy/frontend-study-gochicus/pull/65/files#diff-7752378a93292c3f352a708658c3bf3e44484a0db1b39f22aacb7a7300edbde2R5) зачем-то ссылаешься на @web-diary/app хотя уже работаешь в нем
Я уже писал что внутри пакетов нужно использовать релятивные импорты в таких случаях

2021-04-03 12:15 UTC, TFK70 requested changes

2021-04-03 12:15 UTC, TFK70 commented on practice/web-diary/app/index.tsx
> +import App              from './src/App'
Будь внимательнее
У тебя в src есть index, импорт должен быть
```javascript
import App from './src'
```

2021-04-03 12:17 UTC, TFK70 commented on practice/web-diary/app/index.tsx
> +import App              from './src/App'
@gochicus  Точнее 
```javascript
import { App } from './src'
```
В индексах не должно быть дефолтных экспортов

2021-04-03 12:22 UTC, TFK70 commented
@gochicus messages из button. ты так и не убрал...

2021-04-03 12:23 UTC, TFK70 requested changes

2021-04-03 12:23 UTC, TFK70 commented on practice/web-diary/ui/button/messages/messages.ts
> +export default defineMessages({
Вот эти вот зачем вот они?

2021-04-03 12:27 UTC, TFK70 requested changes

2021-04-03 12:27 UTC, TFK70 commented on practice/web-diary/ui/text/src/index.tsx
> +import { Text } from './Text'
Я уже говорил про такую конструкцию
Либо звездочка, либо используй дефолтный экспорт в Text

2021-04-03 12:32 UTC, gochicus commented on practice/web-diary/ui/text/src/index.tsx
> +import { Text } from './Text'
@TFK70  Я тогда, к слову, интересовался а почему всё-таки звездочка лучше, чем эта конструкция?

2021-04-03 12:34 UTC, TFK70 commented on practice/web-diary/ui/text/src/index.tsx
> +import { Text } from './Text'
@gochicus я ж тогда и ответил

```javascript
import { Component } from './Component'

export { Component }
```

vs

```javascript
export * from './Component'
```

2021-04-03 12:43 UTC, gochicus commented on practice/web-diary/ui/text/src/index.tsx
> +import { Text } from './Text'
@TFK70 Эммм...это экономия места? Смысл не совсем понятен.

2021-04-03 12:44 UTC, TFK70 commented on practice/web-diary/ui/text/src/index.tsx
> +import { Text } from './Text'
@gochicus нуууу......дааа.....
кода в 2 раза меньше

2021-04-03 12:48 UTC, TFK70 commented on practice/web-diary/ui/text/src/index.tsx
> +import { Text } from './Text'
@gochicus тут вопрос не в экономии, незачем на паре байт экономить
звездочки лаконичнее и эквивалентны  конструкции import->export, этого достаточно чтобы их использовать

2021-04-03 12:50 UTC, gochicus commented on practice/web-diary/ui/text/src/index.tsx
> +import { Text } from './Text'
@TFK70  У меня звездочками не все компоненты корректно импортируются почему-то, так что где-то оставил старый импорт, сообщение нет такого дефолтного экспорта, хотя он есть из компонента.

2021-04-03 12:57 UTC, TFK70 commented on practice/web-diary/components/app-header/src/index.tsx
> +import AppHeader from './AppHeader'
@gochicus в таких ситуациях так и должно быть, звездочки на дефолтных экспортах не работают

2021-04-03 12:58 UTC, TFK70 requested changes

2021-04-03 12:58 UTC, TFK70 commented on practice/web-diary/ui/list/src/index.tsx
> +import { ListItem } from './ListItem'
Тебя тут ничего не смущает?

2021-04-03 12:59 UTC, gochicus commented on practice/web-diary/ui/list/src/index.tsx
> +import { ListItem } from './ListItem'
@TFK70  тыж писал либо дефолтный экспорт либо звездочки

2021-04-03 13:01 UTC, TFK70 commented on practice/web-diary/ui/list/src/index.tsx
> +import { ListItem } from './ListItem'
@gochicus ну так блин а почему у тебя здесь и дефолтный экспорт, и именной экспорт
Раз уж ты везде звездочки делал то придерживайся одного стиля и убери дефолтный экспорт из List

2021-04-03 13:12 UTC, TFK70 requested changes

2021-04-03 13:12 UTC, TFK70 commented on practice/web-diary/components/app-header/src/AppHeader.tsx
> +const AppHeader = () => {
export const тогда уж

2021-04-03 13:12 UTC, TFK70 commented on practice/web-diary/components/app-header/src/AppHeader.tsx
> +export { AppHeader }
чтобы этого не было

2021-04-03 13:15 UTC, gochicus commented on practice/web-diary/components/app-header/src/AppHeader.tsx
> +export { AppHeader }
@TFK70 как должно быть тогда?

2021-04-03 13:16 UTC, TFK70 commented on practice/web-diary/components/app-header/src/AppHeader.tsx
> +export { AppHeader }
@gochicus export const AppHeader = ...
Я ж напиал выше

2021-04-03 13:25 UTC, TFK70 requested changes

2021-04-03 13:25 UTC, TFK70 commented on practice/web-diary/ui/background/src/Background.tsx
> +  backgroundColor: '#eaf5fc',
Сашаааа
Мои самые первые комменты только и были про это: у твоего Background как минимум цвет-то должен поддаваться конфигурации

2021-04-03 13:25 UTC, TFK70 commented on practice/web-diary/ui/background/src/Background.tsx
> +  backgroundColor: '#eaf5fc',
Оставь его в defaultProps да и все, но для конфигурации открой

2021-04-03 13:45 UTC, TFK70 requested changes

2021-04-03 13:45 UTC, TFK70 commented on practice/web-diary/components/form-post-add/src/FormPostAdd.tsx
> +const StyledForm = styled<any>('div')(border, color, layout, space, typography)
Вот тут-то этого быть и не должно
Если ты вынес форму в components - это значит что это кусок уже готовой логики, в данном случае форму конфигурировать/модифицировать и т.д. ни к чему т.к. она позиционируется как уже готовый компонент с реализованной логикой

И не пихай бездумно ВСЕ функции из styled-system везде подряд

2021-04-03 13:45 UTC, TFK70 commented on practice/web-diary/components/switcher-post-status/src/SwitcherPostStatus.tsx
> +const StyledSwitcher = styled<any>('div')(border, color, layout, space, typography)
Например тут
Зачем тебе typography? Это просто контейнер для итемов, зачем контейнеру для итемов применять стили для шрифта?

2021-04-03 13:45 UTC, TFK70 commented on practice/web-diary/components/switcher-post-status/src/SwitcherPostStatus.tsx
> +const StyledSwitcher = styled<any>('div')(border, color, layout, space, typography)
Хотя заметил что он в components находится и здесь этого вообще быть не должно

2021-04-03 13:45 UTC, TFK70 commented on practice/web-diary/ui/list/src/List.tsx
> +const StyledList = styled<any>('div')(border, color, layout, space, typography)
Вот, здесь зато то же самое

Контейнер к которому зачем-то можно применять fontSize, fontFamily и прочее: зачем?
Здесь даже border сомнительный, оставь только нужное

2021-04-03 13:45 UTC, TFK70 commented on practice/web-diary/ui/list/src/List.tsx
> +const StyledList = styled<any>('div')(border, color, layout, space, typography)
Если тебе нужно менять стили шрифта для лист итемов - вынеси typography в ListItem, это его зона ответственности

2021-04-03 13:55 UTC, TFK70 requested changes

2021-04-03 13:55 UTC, TFK70 commented on practice/web-diary/ui/background/src/Background.tsx
> +export const Background = styled<any>('div')(border, color, layout, space, typography)
Еще раз: не торопись
Зачем тебе фону задавать бордер и стили для шрифта?
Пройдись еще раз по всему и проверь ui на такие моменты

2021-04-03 13:57 UTC, gochicus commented on practice/web-diary/ui/background/src/Background.tsx
> +export const Background = styled<any>('div')(border, color, layout, space, typography)
@TFK70 Здесь прописаны CSS стили, что должны находиться в body,  поэтому шрифты там нужны. Я этим компонентом приложение обернул, возможно, название неудачное.

2021-04-03 14:02 UTC, TFK70 commented on practice/web-diary/ui/background/src/Background.tsx
> +export const Background = styled<any>('div')(border, color, layout, space, typography)
@gochicus так у тебя бекграунд не должен отвечать за шрифты всего приложения, он отвечает за задний фон
Он не должен отвечать у тебя за шрифт вообще. За шрифт в инпуте отвечает typography в инпуте, за шрифт в баттоне тоже свои пропсы и т.д.

2021-04-03 14:05 UTC, TFK70 commented on practice/web-diary/ui/background/src/Background.tsx
> +export const Background = styled<any>('div')(border, color, layout, space, typography)
@gochicus опиши стандартные стили шрифта в дефолт пропсах у всех чтобы везде одно и то же не писать

2021-04-03 14:32 UTC, TFK70 requested changes

2021-04-03 14:32 UTC, TFK70 commented on practice/web-diary/components/switcher-post-status/src/SwitcherPostStatus.tsx
> +export default SwitcherPostStatus
Два экспорта?

2021-04-03 14:34 UTC, gochicus commented on practice/web-diary/components/switcher-post-status/src/SwitcherPostStatus.tsx
> +export default SwitcherPostStatus
@TFK70 изменения неудачно откатывал, есть ещё что-нибудь на исправление?

2021-04-03 14:42 UTC, TFK70 commented on practice/web-diary/components/switcher-post-status/src/SwitcherPostStatus.tsx
> +export default SwitcherPostStatus
@gochicus больше нет, ничего не заметил, исправь это и аппрувну
Но ты все-равно еще раз по проекту пройдись

2021-04-03 14:44 UTC, gochicus commented on practice/web-diary/components/switcher-post-status/src/SwitcherPostStatus.tsx
> +export default SwitcherPostStatus
@TFK70 Посмотрю уже утром, на свежую голову, сейчас уже глаз замылился.

2021-04-04 06:54 UTC, TFK70 requested changes

2021-04-04 06:54 UTC, TFK70 commented on practice/web-diary/ui/button/package.json
> +    "@ui/button": "0.0.0"
1. Ты нигде его не используешь
2. Это цикл зависимостей

2021-04-04 06:54 UTC, TFK70 commented on practice/web-diary/ui/button/src/types.ts
> +export interface ButtonProps {
Их не нужно оставлять просто для галочки
Убери если их не используешь, от них никакого смысла нет

2021-04-04 06:54 UTC, TFK70 commented on practice/web-diary/ui/button/src/Button.tsx
> +export const Button = styled<any>('button')<ButtonProps>(border, color, layout, padding, typography)
Оставь только any, здесь 0 смысла от ButtonProps

2021-04-04 06:54 UTC, TFK70 commented on practice/web-diary/ui/button/src/Button.tsx
> +import { border, color, layout, padding, typography } from 'styled-system'
Убери padding, его включает space из styled-system

2021-04-04 07:11 UTC, TFK70 requested changes

2021-04-04 07:11 UTC, TFK70 commented on practice/web-diary/ui/layout/src/types.ts
> +export interface LayoutType {
Лучше уж any написать вместо этого
Интерфейс все-равно не законченный, убери его тоже

2021-04-04 07:11 UTC, TFK70 commented on practice/web-diary/ui/list/src/List.tsx
> +  const elements = data.map((item: any) => {
Это не обязательно хранить в отдельной переменной, возвращай напрямую

2021-04-04 07:20 UTC, TFK70 approved these changes

2021-04-04 07:33 UTC, TFK70 requested changes

2021-04-04 07:33 UTC, TFK70 commented on practice/web-diary/ui/list/src/List.tsx
> +    return (
А зачем писать тело функции и return?
Сразу jsx и возвращай, этот огород ни к чему

2021-04-04 07:40 UTC, gochicus commented on practice/web-diary/ui/list/src/List.tsx
> +    return (
@TFK70 не понял идею, как оно должно работать?

2021-04-04 07:42 UTC, TFK70 commented on practice/web-diary/ui/list/src/List.tsx
> +    return (
@gochicus так же и должно
просто ты вместо
```javascript
arr.map(i => {
   return (<Jsx />)
})
```
 пишешь
```javascript
arr.map(i => <Jsx />)
```
азы синтаксиса

2021-04-04 07:55 UTC, gochicus commented on practice/web-diary/ui/list/src/List.tsx
> +    return (
@TFK70  Такое имеешь ввиду? 
 ```
data.map(item =>
      <StyledList key={item.id}>
        <ListItem content={item.post} />
      </StyledList>
```

2021-04-04 07:56 UTC, TFK70 commented on practice/web-diary/ui/list/src/List.tsx
> +    return (
> @TFK70 Такое имеешь в виду?
> 
> ```
> data.map(item =>
>      <StyledList key={item.id}>
>        <ListItem content={item.post} />
>      </StyledList>
> ```

+

2021-04-04 07:57 UTC, gochicus commented on practice/web-diary/ui/list/src/List.tsx
> +    return (
@TFK70 Так не работает

2021-04-04 07:58 UTC, TFK70 commented on practice/web-diary/ui/list/src/List.tsx
> +    return (
@gochicus если что ты скобку в конце потерял

2021-04-04 08:00 UTC, gochicus commented on practice/web-diary/ui/list/src/List.tsx
> +    return (
@TFK70 она есть, пропустил при копировании

2021-04-04 08:04 UTC, TFK70 commented on practice/web-diary/ui/list/src/List.tsx
> +    return (
@gochicus тогда конкретизируй что не работает, дай логи, предоставь код с точностью до символа

2021-04-04 08:10 UTC, gochicus commented on practice/web-diary/ui/list/src/List.tsx
> +    return (
@TFK70  Похоже просто баг был,  попытался воспроизвести - отрендерилось.

2021-04-04 08:15 UTC, TFK70 submitted a review, later dismissed

2021-04-04 16:54 UTC, TorinAsakura requested changes

2021-04-04 16:54 UTC, TorinAsakura commented on practice/web-diary/app/src/App.tsx
> +        <Layout margin='1 rem 0' justifyContent='space-between' alignItems='center'>
отступы считаем в статичных величинах

2021-04-04 16:54 UTC, TorinAsakura commented on practice/web-diary/app/src/App.tsx
> +          <Box flexBasis='40px' />
ты наверно хотел сделать отступ? для отступов используем layout, box юзаем для стилизованных вещей

2021-04-04 16:54 UTC, TorinAsakura commented on practice/web-diary/components/app-header/messages/messages.ts
> +    defaultMessage: '5 записей, из них понравилось 0',
а если будет 10 записей и из них понравится 10? 5 и 10 не константы, это разные строки, разные объекты

2021-04-04 16:54 UTC, TorinAsakura commented on practice/web-diary/components/app-header/package.json
> +  "name": "@components/app-header",
убери уже app-

2021-04-04 16:54 UTC, TorinAsakura commented on practice/web-diary/components/form-post-add/src/FormPostAdd.tsx
> +          <Input placeholder='Ваша запись' />
а тут почему не проброшено через intl?

2021-04-04 16:54 UTC, TorinAsakura commented on practice/web-diary/components/switcher-post-status/src/SwitcherPostStatus.tsx
> +  margin: ' 1rem 0',
при попытке распарсить он увидит пробел в начале и ты словишь "что-то пошло не так"

2021-04-04 16:54 UTC, TorinAsakura commented on practice/web-diary/ui/button/src/Button.tsx
> +  fontFamily: ' -apple-system, BlinkMacSystemFont, "Segoe UI", "Roboto", "Oxygen"',
ебать-колотить держите меня крепче! Саша! Шойта за хуйня?

2021-04-07 05:28 UTC, TFK70 requested changes

2021-04-07 05:28 UTC, TFK70 commented on practice/web-diary/components/form-post-add/messages/messages.ts
> +  placeholder: {
Слишком общее название
У тебя может быть несколько инпутов с разными плейсхолдерами на одной странице, конкретизируй

2021-04-07 05:28 UTC, TFK70 commented on practice/web-diary/components/header/messages/messages.ts
> +  header: {
То же самое

2021-04-07 05:28 UTC, TFK70 commented on practice/web-diary/components/header/package.json
> +  "name": "@components/header",
Конкретизируй название для хедера, напиши как минимум к чему он относится

2021-04-08 02:56 UTC, TorinAsakura commented on practice/web-diary/components/header/package.json
> +  "name": "@components/header",
У него аппликуха одна, стало быть хедер относящийся к аппликухе. Тут нет смысла что-либо уточнять.

2021-04-08 09:52 UTC, TFK70 requested changes

2021-04-08 09:52 UTC, TFK70 commented on practice/web-diary/components/form-post-add/messages/messages.ts
> +  placeholderFormPostAdd: {
Тебе ни к чему в названиях месседжей привязывать их к контексту
Было бы неплохо называть их исходя из самого месседжа: yourPost было бы вполне себе ок
Иначе, если бы тебе пригодилось использовать это сообщение еще где-то помимо плейсхолдера, то сам понимаешь

2021-04-09 04:39 UTC, TFK70 requested changes

2021-04-09 04:39 UTC, TFK70 commented on practice/web-diary/components/form-post-add/messages/messages.ts
> +  placeholderYourPost: {
Под контекстом я подразумевал слово placeholder

2021-04-09 04:39 UTC, TFK70 commented on practice/web-diary/components/form-post-add/messages/messages.ts
> +    id: `${name}.header`,
Так же и тут
Месседж "Ваша запись" почему-то имеет ключ header, при именовании месседжей отталкивайся от того, что в них

2021-04-09 06:00 UTC, gochicus commented on practice/web-diary/components/form-post-add/messages/messages.ts
> +  placeholderYourPost: {
@TFK70  Я как-то потерял нить, здесь пробрасывается именно  текст плэйсхолдера, не содержимое поста или ещё что-то.  Я допускаю, может быть несколько разных плэйсхолдеров в компоненте и можно на каждый своё сообщение. с соответствующим названием. Но если просто YourPost, то тут. мне кажется только путаница будет. Можешь прояснить?

2021-04-09 06:28 UTC, TFK70 commented on practice/web-diary/components/form-post-add/messages/messages.ts
> +  placeholderYourPost: {
В чем именно путаница?
Путаница будет если тебе нужно будет использовать один и тот же текст и в плейсхолдере, и где-то помимо плейсхолдера, там придется создавать второй месседж с тем же содержимым, но с другим ключом

2021-04-09 06:33 UTC, TFK70 commented on practice/web-diary/components/form-post-add/messages/messages.ts
> +  placeholderYourPost: {
И ты его назвал неверно, если у тебя в месседже "Добавить" - он должен называться add

yourPost - "Ваш пост"

2021-04-09 07:23 UTC, TFK70 requested changes

2021-04-09 07:23 UTC, TFK70 commented on practice/web-diary/components/form-post-add/messages/messages.ts
> +    id: `${name}.form-post-add`,
а что с id?
он должен соответствовать ключу месседжа, а слова должны разделяться андерскором

2021-04-09 09:28 UTC, TFK70 requested changes

2021-04-09 09:28 UTC, TFK70 commented on practice/web-diary/components/header/messages/messages.ts
> +    id: `${name}.headerPostCount`,
Слова разделяются андерскором, я ж написал
header_post_count

2021-04-09 09:28 UTC, TFK70 commented on practice/web-diary/components/header/messages/messages.ts
> +    id: `${name}.headerPostCount`,
хотя тут тоже нужно изменить название аналогично тому как ты его поменял в месседже плейсхолдера, ты почему-то текст "записей," привязал к хедер

2021-04-09 09:28 UTC, TFK70 commented on practice/web-diary/components/header/messages/messages.ts
> +    id: `${name}.headerPostCount`,
И пройдись по всем месседжам, сделай правки

2021-04-09 09:45 UTC, TFK70 requested changes

2021-04-09 09:45 UTC, TFK70 commented on practice/web-diary/components/form-post-add/src/FormPostAdd.tsx
> +const StyledForm = styled('div')(() => ({
И обязательно ли было так делать?
У тебя же для таких махинаций существует Box

2021-04-09 09:45 UTC, TFK70 commented on practice/web-diary/components/header/src/Header.tsx
> +    <Box justifyContent='space-between' alignItems='flex-end' display='flex'>
Я уже очень много раз говорил что display: flex уже есть в дефолт пропсах, зачем это здесь писать?

2021-04-09 09:45 UTC, TFK70 commented on practice/web-diary/components/switcher-post-status/messages/messages.ts
> +    id: `${name}.switcher`,
Вот тут например тоже id везде одинаковые почему-то

2021-04-09 09:45 UTC, TFK70 commented on practice/web-diary/ui/layout/src/Box.tsx
> +  display: 'flex',
На всякий случай помечу где тот самый display:flex находится для наглядности

2021-04-09 09:45 UTC, TFK70 commented on practice/web-diary/ui/list/src/List.tsx
> +export const List: any = ({ data }: any) => {
Либо затипизируй нормально, либо ничего не пиши
В большинстве случаев будет достаточно типизировать пропсы и все

2021-04-09 09:45 UTC, TFK70 commented on practice/web-diary/ui/list/src/List.tsx
> +StyledList.defaultProps = {
И абсолютно то же самое
Что в этом блоке такого, что делает его листом? Это просто блок-обертка, а для их реализации есть Box

2021-04-09 10:16 UTC, TFK70 requested changes

2021-04-09 10:16 UTC, TFK70 commented on practice/web-diary/ui/background/package.json
> +    "@types/styled-system": "^5.1.11"
Где они должны находиться?)

2021-04-09 10:16 UTC, TFK70 commented on practice/web-diary/ui/button/package.json
> +    "@types/styled-system": "^5.1.11"
Где-где?)))

2021-04-09 10:16 UTC, TFK70 commented on practice/web-diary/ui/list/src/List.tsx
> +  return data.map(item => (
А я же вроде уже давал насчет этого комментарий
Зачем тебе полностью описывать тело функции с return когда можно сразу возвратить data.map(...) без всего этого

2021-04-09 10:16 UTC, TFK70 commented on practice/web-diary/app/src/App.tsx
> +          <Input placeholder='Поиск' />
Почему тут не через intl?

2021-04-09 10:16 UTC, TFK70 commented on practice/web-diary/app/src/App.tsx
> +        <Header post={5} like={0} />
Почему у тебя хедер принимает пропсы? Зачем?

2021-04-09 10:16 UTC, TFK70 commented on practice/web-diary/app/src/App.tsx
> +        <Header post={5} like={0} />
Опиши логику внутри него же

2021-04-09 10:22 UTC, gochicus commented on practice/web-diary/ui/background/package.json
> +    "@types/styled-system": "^5.1.11"
@TFK70 Если ты имеешь ввиду тип стайлед систем, то ты ж и сам и говорил ставить их везде, где используются

2021-04-09 10:27 UTC, TFK70 commented on practice/web-diary/ui/background/package.json
> +    "@types/styled-system": "^5.1.11"
@gochicus да, но про @types я кажется тоже кое-что говорил
они нужны только при разработке

2021-04-09 10:31 UTC, gochicus commented on practice/web-diary/ui/background/package.json
> +    "@types/styled-system": "^5.1.11"
@TFK70 А, теперь понятно о чём ты

2021-04-09 10:36 UTC, gochicus commented on practice/web-diary/app/src/App.tsx
> +        <Header post={5} like={0} />
@TFK70 Дай подсказку в каком направлении думать, у меня в хэдере <Text>  обернутый в <Box>, ни тот ни другой к контексту привязывать не стоит.

2021-04-09 11:50 UTC, TFK70 approved these changes

2021-04-12 18:33 UTC, TorinAsakura requested changes

2021-04-12 18:33 UTC, TorinAsakura commented on practice/web-diary/components/header/src/Header.tsx
> +      <Text fontSize='25px'  >{post}{intl.formatMessage(messages.header)}{like}</Text>
Следи за вайтспейсами и чистотой синтаксиса

2021-04-12 18:33 UTC, TorinAsakura commented on practice/web-diary/app/package.json
> +    "@components/switcher-post-status": "0.0.0",
добавь по-человечески через yarn workspace

2021-04-12 18:39 UTC, TFK70 requested changes

2021-04-12 18:39 UTC, TFK70 commented on practice/web-diary/package.json
> +    "typescript": "^4.2.3"
Это дев зависимость, тебе тайпскрипт и типизация нужны только при разработке

2021-04-12 18:39 UTC, TFK70 commented on practice/web-diary/components/header/package.json
> +    "@ui/text": "0.0.0"
Тут тоже через yarn workspace добавь

2021-04-13 08:56 UTC, TFK70 commented
@gochicus у тебя же чеки не прошли
Если что эти зависимости не надо было убирать - их надо было заново добавить через yarn workspace .. add
У тебя скорее всего он не находил локальные пакеты, чтобы нашел - прописывай руками версию пакета yarn add @ui/button@0.0.0

2021-04-13 10:34 UTC, TFK70 requested changes

2021-04-13 10:34 UTC, TFK70 commented on practice/web-diary/package.json
> +    "lint": "actl lint"
А что он тут делает?

2021-04-13 13:30 UTC, TFK70 submitted a review, later dismissed

2021-04-13 16:50 UTC, TorinAsakura requested changes

2021-04-13 16:50 UTC, TorinAsakura commented on practice/web-diary/ui/list/src/List.tsx
> +    <Box marginTop='10px' padding='20px 35px 10px 35px' minWidth='300px' key={item.id}>
паддинги не должны использоваться для позиционирования родителей

2021-04-14 19:37 UTC, TFK70 requested changes

2021-04-14 19:37 UTC, TFK70 commented on practice/web-diary/ui/list/src/List.tsx
> +    <Box marginTop='10px' minWidth='300px' key={item.id}>
жду переписанный кусок(ки)

2021-04-15 10:15 UTC, TFK70 requested changes

2021-04-15 10:15 UTC, TFK70 commented on practice/web-diary/app/src/App.tsx
> +      <Layout flexDirection='column' alignItems='center'>
а почему так-то?
у тебя блоки с flex-direction должны быть вынесены в разные компоненты Row и Column соответственно
это же вообще не похоже на тот пример который я показывал

2021-04-15 10:22 UTC, gochicus commented on practice/web-diary/app/src/App.tsx
> +      <Layout flexDirection='column' alignItems='center'>
@TFK70 ок,  поменяю, а в остальном как?

2021-04-15 10:25 UTC, TFK70 requested changes

2021-04-15 10:25 UTC, TFK70 commented on practice/web-diary/app/src/App.tsx
> +        <Layout justifyContent='space-between' alignItems='center' minWidth='400px'>
Не пихай везде подряд Layout, в таких местах используй Box

2021-04-15 10:26 UTC, TFK70 commented on practice/web-diary/app/src/App.tsx
> +      <Layout flexDirection='column' alignItems='center'>
@gochicus вроде норм, но после правок виднее будет

2021-04-15 10:30 UTC, gochicus commented on practice/web-diary/app/src/App.tsx
> +        <Layout justifyContent='space-between' alignItems='center' minWidth='400px'>
@TFK70  Так Box же для стилизованных компонентов, а Layout для структуры?

2021-04-15 10:34 UTC, TFK70 commented on practice/web-diary/app/src/App.tsx
> +        <Layout justifyContent='space-between' alignItems='center' minWidth='400px'>
@gochicus да, но по-моему Layout лучше использовать для применения свойств которые влияют на разметку снаружи (типа align center), а Box для свойств которые более-менее заметно аффектят чилдренов

2021-04-15 10:37 UTC, TFK70 commented on practice/web-diary/app/src/App.tsx
> +        <Layout justifyContent='space-between' alignItems='center' minWidth='400px'>
@gochicus ну т.е. я в верстке Layout использую только когда мне нужно обернуть что-то в контейнер с минимумом свойств, который можно счесть скорее за формальность, чтобы верстка не полетела

для остального - Box

2021-04-15 10:39 UTC, gochicus commented on practice/web-diary/app/src/App.tsx
> +        <Layout justifyContent='space-between' alignItems='center' minWidth='400px'>
@TFK70   ` <Layout justifyContent='space-between' alignItems='center' minWidth='400px'>` Так здесь, вроде, и то и то, но в целом именно разметка. Возможно, если Layout с flexDirection поменять на Column, то избыток не так будет бросаться?

2021-04-15 10:43 UTC, TFK70 commented on practice/web-diary/app/src/App.tsx
> +        <Layout justifyContent='space-between' alignItems='center' minWidth='400px'>
@gochicus короче когда тебе что-то нужно обернуть старайся использовать Box, но когда чувствуешь что слишком жирно - меняй на Layout, я затрудняюсь объяснить где именно что использовать нужно, у меня это интуитивно)

2021-04-15 10:45 UTC, TFK70 commented on practice/web-diary/app/src/App.tsx
> +        <Layout justifyContent='space-between' alignItems='center' minWidth='400px'>
@gochicus я если что поправлять буду, со временем уловишь суть

2021-04-15 14:47 UTC, TFK70 requested changes

2021-04-15 14:47 UTC, TFK70 commented on practice/web-diary/ui/layout/src/Row.tsx
> +  display: 'flex',
а самое главное flexDirection: 'row' забыл)

2021-04-15 14:47 UTC, TFK70 commented on practice/web-diary/ui/text/src/Space.tsx
> +  return <Text>{space} </Text>
пагади...
я же вижу что у тебя там пробел есть

2021-04-15 14:47 UTC, TFK70 commented on practice/web-diary/ui/text/src/Space.tsx
> +  let space = ''
зачем оно надо-то?
тут ни единого символа нет
то же что и 7+0+0+0+0

2021-04-15 14:47 UTC, TFK70 commented on practice/web-diary/ui/text/src/Space.tsx
> +    rundownCounter -= 1
если уж ты так делаешь - то делай через for чтобы лишние переменные не создавать

но вообще тут нужно использовать методы строк

2021-04-15 14:47 UTC, TFK70 commented on practice/web-diary/ui/text/src/Space.tsx
> +import { Text } from './Text'
и тут нету большого смысла использовать текст, нам ни к чему применять какие-то стили к пробелу

2021-04-15 14:47 UTC, TFK70 commented on practice/web-diary/components/header/src/Header.tsx
> +        <Space count={1} />
там же уже initialValue = 1, зачем здесь это  писать? просто <Space />

2021-04-15 14:47 UTC, TFK70 commented on practice/web-diary/ui/list/src/Item.tsx
>          <Text>{content} </Text>
тут почему на space не заменил?

2021-04-15 14:49 UTC, gochicus commented on practice/web-diary/ui/layout/src/Row.tsx
> +  display: 'flex',
@TFK70 У флекса display row по умолчанию же

2021-04-15 14:51 UTC, TFK70 commented on practice/web-diary/ui/layout/src/Row.tsx
> +  display: 'flex',
@gochicus да, но все-равно лучше добавь для наглядности

2021-04-15 14:53 UTC, gochicus commented on practice/web-diary/ui/list/src/Item.tsx
>          <Text>{content} </Text>
@TFK70  А здесь то зачем space? Тут контент поста в одно слово.

2021-04-15 14:55 UTC, TFK70 commented on practice/web-diary/ui/list/src/Item.tsx
>          <Text>{content} </Text>
@gochicus space как раз для того и вводился чтобы заменить такие пробелы
<Text>{content} </Text>
< Space />

2021-04-15 14:58 UTC, gochicus commented on practice/web-diary/ui/list/src/Item.tsx
>          <Text>{content} </Text>
@TFK70 Если речь о пробеле между контентом и закрывающим Text, то здесь просто небрежность в коде, никакого пробела здесь не обозначается.

2021-04-15 15:27 UTC, TFK70 requested changes

2021-04-15 15:27 UTC, TFK70 commented on practice/web-diary/components/header/src/Header.tsx
> +        <span> {post} </span>
а это зачем??

2021-04-15 15:27 UTC, TFK70 commented on practice/web-diary/ui/text/src/Space.tsx
> +  const space = ' '.repeat(count)
вот опять: зачем тебе создавать лишнюю переменную?
делай repet прямо jsx и возвращай сразу jsx

2021-04-15 15:29 UTC, TFK70 commented on practice/web-diary/components/header/src/Header.tsx
> +        <span> {post} </span>
и если мне не изменяют мои глаза то там по бокам стоят пробелы

2021-04-15 15:29 UTC, gochicus commented on practice/web-diary/components/header/src/Header.tsx
> +        <span> {post} </span>
@TFK70 Возможно, я что-то упускаю, но просто так у меня корректно строки не склеиваются.

2021-04-15 15:31 UTC, TFK70 commented on practice/web-diary/components/header/src/Header.tsx
> +        <span> {post} </span>
@gochicus распиши в чем проблема тогда
ты же видишь что это полный бред и так точно быть не должно

но вообще основной вопрос был про то зачем ты тут Text на span поменял

2021-04-15 15:51 UTC, TFK70 requested changes

2021-04-15 15:51 UTC, TFK70 commented on practice/web-diary/ui/text/src/Space.tsx
> +  return <span>{' '.repeat(count)}</span>
почему вам так нравится этот return с телом функции писать?..
```javascript
const Text = ({children}) => {
   return <span>{children}</span>
}
```
vs
```javascript
const Text = ({children}) => <span>{children}</span>
```

2021-04-15 15:51 UTC, TFK70 commented on practice/web-diary/components/header/src/Header.tsx
>        <Text fontSize='25px'>
я бы не советовал сметать все это под один Text
тебе вполне может пригодиться в будущем сделать цвет шрифта у количества постов красным, например
вынеси все в отдельные Text и их уже раздели пробелами

2021-04-15 16:12 UTC, TFK70 requested changes

2021-04-15 16:12 UTC, TFK70 commented on practice/web-diary/components/header/src/Header.tsx
>          {intl.formatMessage(messages.postCount)}
стили шрифта применяются и к цифрам

2021-04-15 16:14 UTC, gochicus commented on practice/web-diary/components/header/src/Header.tsx
>          {intl.formatMessage(messages.postCount)}
@TFK70 Не понял суть проблемы.

2021-04-15 16:18 UTC, TFK70 commented on practice/web-diary/components/header/src/Header.tsx
>          {intl.formatMessage(messages.postCount)}
@gochicus сори, я чет даже несмотря на intl подумал что тут число находится...
почему ты postCount и likeCount то не разделил?

2021-04-15 16:20 UTC, gochicus commented on practice/web-diary/components/header/src/Header.tsx
>          {intl.formatMessage(messages.postCount)}
@TFK70  ` {intl.formatMessage(messages.postCount)}
                  <Space />
                 {intl.formatMessage(messages.likeCount)}`
Разделил же?

2021-04-15 16:21 UTC, TFK70 commented on practice/web-diary/components/header/src/Header.tsx
>          {intl.formatMessage(messages.postCount)}
@gochicus не, я про то почему ты в разные Text их не вынес

2021-04-15 16:25 UTC, gochicus commented on practice/web-diary/components/header/src/Header.tsx
>          {intl.formatMessage(messages.postCount)}
@TFK70 `записей, из них понравилось`  вот буквально эти две части предложения через запятую. Они в отдельных сообщенияхна случай если понравившихся будет 0. Но вот стилизовать их по отдельности явно не нужно.

2021-04-15 16:28 UTC, TFK70 commented on practice/web-diary/components/header/src/Header.tsx
>          {intl.formatMessage(messages.postCount)}
@gochicus если это имеет вид `x записей, из них понравилось y` - то `записей, из них понравилось` нужно вынести в один месседж

2021-04-15 16:37 UTC, TFK70 commented on practice/web-diary/components/header/src/Header.tsx
>          {intl.formatMessage(messages.postCount)}
> @TFK70 `записей, из них понравилось` вот буквально эти две части предложения через запятую. Они в отдельных сообщениях на случай если понравившихся будет 0. Но вот стилизовать их по отдельности явно не нужно.
> К слову, поясни что ты имел ввиду в своем первом ревью про числа и шрифты.

про числа и шрифты я сказал потому что думал что ты выводишь number переменную, типа:
```javascript
const x: number = 7
const Component = () => <p>{x}</p>
```
то есть так у тебя выведется 7 со всеми дефолтными стилями параграфа, + если ты припишешь какой-нибудь color='red' то 7 даже станет красной, ну и аналогично с остальными стилями шрифта, я хотел обратить внимание что при выводе чисел стили шрифта тоже важны

но, как я уже сказал, написал это по ошибке, так что все ок

2021-04-15 16:43 UTC, TFK70 requested changes

2021-04-15 16:43 UTC, TFK70 commented on practice/web-diary/components/switcher-post-status/src/SwitcherPostStatus.tsx
> +      <Button color='black'> {intl.formatMessage(messages.all)}</Button>
пробеелы

2021-04-15 16:43 UTC, TFK70 commented on practice/web-diary/ui/list/src/List.tsx
> +    <Column flexDirection='column'>
что-то тут есть лишнее

2021-04-15 16:45 UTC, gochicus commented on practice/web-diary/components/switcher-post-status/src/SwitcherPostStatus.tsx
> +      <Button color='black'> {intl.formatMessage(messages.all)}</Button>
@TFK70 Куда пробелы?

2021-04-15 16:46 UTC, TFK70 commented on practice/web-diary/components/switcher-post-status/src/SwitcherPostStatus.tsx
> +      <Button color='black'> {intl.formatMessage(messages.all)}</Button>
@gochicus неужели опять `небрежность в коде`?)
в начале строки пробел есть, либо убери, либо оформи через space

2021-04-15 16:58 UTC, TFK70 approved these changes, later dismissed

2021-04-15 20:06 UTC, TorinAsakura reviewed
Поправить дребедень с иконками и 👍🏻

2021-04-15 20:06 UTC, TorinAsakura commented on practice/web-diary/ui/list/src/Item.tsx
> +          <i className='fa fa-star' />
откуда у тебя fontawesome тут взялся? переведи в компоненты все иконки и это можно сделать за счёт цикла

2021-04-16 02:56 UTC, TFK70 requested changes

2021-04-16 02:56 UTC, TFK70 commented on practice/web-diary/ui/list/src/Item.tsx
> +import { HeartIcon }        from '../../icons'
ну импорты-то

2021-04-16 03:12 UTC, TFK70 approved these changes

2021-04-16 13:52 UTC, TorinAsakura approved these changes
Поздравляю дружище

2021-04-16 13:52 UTC, merged