Feature/item functionality
atls-academy/frontend-study-gochicus pull request #69
Opened 2021-04-27 08:55 UTC by gochicus

2021-04-27 08:57 UTC, gochicus commented
@TFK70 Требуется помощь, функционал добавления статуса like и important отрабатывет некорректно. Не могу понять в чем ошибка. С удалением всё в порядке.

2021-04-28 11:44 UTC, TFK70 commented
@gochicus 

**Есть недоработки:**

https://user-images.githubusercontent.com/62806448/116397690-5907f880-a840-11eb-97db-4a61006410b5.mov

1. Цвет должен меняться в зависимости от состояния флажка true/false
2. initialValue у счетчика лайков неверный, но я уже говорил что она не должна быть счетчиком. Количество лайкнутых записей должно браться от массива с постами postData как раз чтобы подобных ситуаций не было, когда состояние счетчика не совпадает с действительностью. В общем, примерно так же, как и postData.length, только чуть навороченнее

2021-04-28 11:49 UTC, TFK70 requested changes

2021-04-28 11:49 UTC, TFK70 commented on practice/web-diary/components/header/actions/counter.ts
> +  return postData.length
Это не стоит выносить в action
В них должна быть более сложная логика, а в этом просто нет смысла

2021-04-28 11:49 UTC, TFK70 commented on practice/web-diary/components/header/actions/favouredCounter.ts
> +      result += 1
В этой логике где-то ошибка, посты считаются неверно, как я уже говорил

2021-04-28 11:51 UTC, gochicus commented
> @gochicus
> 
> **Есть недоработки:**
> 
>  2021-04-28.16.38.20.mov 
> 1. Цвет должен меняться в зависимости от состояния флажка true/false
> 2. initialValue у счетчика лайков неверный, но я уже говорил что она не должна быть счетчиком. Количество лайкнутых записей должно браться от массива с постами postData как раз чтобы подобных ситуаций не было, когда состояние счетчика не совпадает с действительностью. В общем, примерно так же, как и postData.length, только чуть навороченнее
Я могу для изменения цвета  actions использовать? Я не знаю как синтаксически это прямо в строке сделать. Можешь по счетчику лайков пояснить, там 0,  так и лайков изначально 0.

2021-04-28 13:17 UTC, TFK70 approved these changes

2021-04-28 13:23 UTC, TorinAsakura approved these changes

2021-04-28 13:24 UTC, merged