feat(how-to-use-functions): use of functions in user answer collectin…
atls-academy/frontend-study-gochicus pull request #7
Opened 2020-12-09 19:15 UTC by gochicus

…g automation

ISSUES CLOSED: #6

2020-12-09 21:16 UTC, themetronome requested changes
Судя по всему, prettier не использовался вообще. Отформатируй код чтобы он выглядел подобающе

2020-12-09 21:16 UTC, ad21ewda1231dsa123das12 commented on lessons/how-to-use-functions/src/index.js
> +const MoviesCount = () => {
Почему название переменной начинается с заглавной буквы? PascalCase мы не используем, исправь

2020-12-09 21:16 UTC, ad21ewda1231dsa123das12 commented on lessons/how-to-use-functions/src/index.js
> +  },
Объект же пустой, зачем между скобками ещё строка?

2020-12-09 21:16 UTC, ad21ewda1231dsa123das12 commented on lessons/how-to-use-functions/src/index.js
> +  },
Тоже самое, объект пустой

2020-12-09 21:16 UTC, ad21ewda1231dsa123das12 commented on lessons/how-to-use-functions/src/index.js
> +  private:false
whitespace

2020-12-09 21:16 UTC, ad21ewda1231dsa123das12 commented on lessons/how-to-use-functions/src/index.js
> +function  rememberMyFilms() {
лишний whitespace

2020-12-09 21:16 UTC, ad21ewda1231dsa123das12 commented on lessons/how-to-use-functions/src/index.js
> +function ShowMyDB() {
camel case

2020-12-09 21:16 UTC, themetronome commented on lessons/how-to-use-functions/src/index.js
> +console.log(personalMoviesDB);
С какой целью именно здесь консолишь объект с данными? Ты же создал для этого специальную функцию

2020-12-09 21:16 UTC, themetronome commented on lessons/how-to-use-functions/src/index.js
> +      console.log(personalMoviesDB.private)
Тебе нужно показать весь объект, а не значение поля `private`

2020-12-09 21:16 UTC, themetronome commented on lessons/how-to-use-functions/src/index.js
> +ShowMyDB();
camel case again

2020-12-09 21:16 UTC, themetronome commented on lessons/how-to-use-functions/src/index.js
> +  geners: [],
Наверное `genres` ты имел в виду, исправь эту опечатку здесь и ниже везде где ошибся (в названии функции тоже)

2020-12-09 21:16 UTC, themetronome commented on lessons/how-to-use-functions/src/index.js
> +    personalMoviesDB.geners[i] = ask;
Как вариант, можно присвоить значению каждого индекса массива `genres` функцию prompt, без переменной

2020-12-09 21:16 UTC, themetronome commented on lessons/how-to-use-functions/src/index.js
> +writeYourGeners();
end of last line

2020-12-11 16:10 UTC, TorinAsakura approved these changes

2020-12-11 16:11 UTC, TorinAsakura approved these changes

2020-12-11 16:11 UTC, TorinAsakura commented
@themetronome approve?

2020-12-11 16:12 UTC, themetronome commented
> @themetronome approve?

yep

2020-12-11 16:13 UTC, TorinAsakura commented
> > @themetronome approve?
> 
> yep

что yep? Ты ревью проводил - тебе и аппрув ставить, без тебя - не вмержу

2020-12-11 16:15 UTC, themetronome approved these changes

2020-12-11 16:17 UTC, merged