chore(web-diary): deploy workflow added
atls-academy/frontend-study-gochicus pull request #79
Opened 2021-05-05 09:32 UTC by gochicus

affects: @practice/web-diary

ISSUES CLOSED: #78

2021-05-05 09:33 UTC, TFK70 requested changes

2021-05-05 09:33 UTC, TFK70 commented on practice/web-diary/package.json
> +    "@jamesives/github-pages-deploy-action": "^4.1.1",
Оно тут не надо, он сам [стягивается](https://github.com/atls-academy/frontend-study-gochicus/pull/79/files#diff-33cc4c925f7fd36575f5e5b61d1e9c942fea5189e2c67d09720d714e19151404R24) во время выполнения

2021-05-05 09:38 UTC, TFK70 requested changes

2021-05-05 09:38 UTC, TFK70 commented on .github/workflows/config.yml
> +        run: yarn workspase @practice/web-diary build
https://github.com/atls-academy/frontend-study-ikorol/runs/2505044401?check_suite_focus=true

2021-05-05 09:41 UTC, gochicus commented on .github/workflows/config.yml
> +        run: yarn workspase @practice/web-diary build
@TFK70  надо версию пакета указать? или просто билд сделать?

2021-05-05 09:41 UTC, TFK70 commented on .github/workflows/config.yml
> +        run: yarn workspase @practice/web-diary build
@gochicus как минимум - проверить локально

2021-05-05 09:44 UTC, gochicus commented on .github/workflows/config.yml
> +        run: yarn workspase @practice/web-diary build
@TFK70 ну, у меня именнно такой командой код билдится.

2021-05-05 09:45 UTC, TFK70 commented on .github/workflows/config.yml
> +        run: yarn workspase @practice/web-diary build
@gochicus так ты его руками потому что с 0 написал
попробуй этот скопипастить и запустить

2021-05-05 09:55 UTC, TFK70 submitted a review, later dismissed

2021-05-05 11:23 UTC, TorinAsakura requested changes

2021-05-05 11:23 UTC, TorinAsakura commented on .github/workflows/config.yml
> +name: Deploy project
https://github.com/atls/tools/tree/master/.github/workflows
Экшены нужно разбивать, для наглядности и изолированности

2021-05-05 11:23 UTC, TorinAsakura commented on .github/workflows/config.yml
> +name: Deploy project
прежде чем задеплоить нужно, помимо инсталла, пройти проверки, что мы не битое гавно отгружаем

2021-05-05 11:24 UTC, TorinAsakura requested changes

2021-05-05 11:24 UTC, TorinAsakura commented on yarn.lock
> +"@actions/exec@1.0.4":
что тут делают зависимости от экшенов? где ты их импортишь?

2021-05-06 08:01 UTC, TFK70 approved these changes

2021-05-06 12:21 UTC, TFK70 requested changes

2021-05-06 12:21 UTC, TFK70 commented on .github/workflows/deploy.yml
> +      - name: build app
Билд должен происходить после проверок

Если упал линт или тайпчек - смысла билдить приложение нет, это необходимо в целях экономии ресурсов

2021-05-06 12:27 UTC, TorinAsakura commented on .github/workflows/deploy.yml
> +      - name: build app
> Билд должен происходить после проверок
> 
> Если упал линт или тайпчек - смысла билдить приложение нет, это необходимо в целях экономии ресурсов

это необходимо с целью сохранения здравого смысла
ты же не купишь помидоры если они подпорчены,  чтобы потом их вернуть в магазин

2021-05-06 12:27 UTC, TFK70 approved these changes, later dismissed

2021-05-06 12:55 UTC, TFK70 approved these changes

2021-05-06 13:04 UTC, TorinAsakura requested changes

2021-05-06 13:04 UTC, TorinAsakura commented on .github/workflows/checking.yml
> +        run: yarn workspace @practice/web-diary build
зачем вы два раза билдите проект?

2021-05-06 13:07 UTC, TFK70 commented on .github/workflows/checking.yml
> +        run: yarn workspace @practice/web-diary build
@gochicus ну так если билд падает - то это лучше выявить на чеках
тайпчек же не выявит несоответствующие с реальностью пути в вебпак конфиге и тп

2021-05-06 15:05 UTC, TorinAsakura approved these changes

2021-05-06 15:05 UTC, merged