Feature/new design
atls-academy/frontend-study-gochicus pull request #80
Opened 2021-05-11 06:52 UTC by gochicus

2021-05-11 08:37 UTC, TFK70 commented
@gochicus есть кривости/недоработки по верстке:
1. Что с плюсиком? Он как-то совсем непропорционально спозиционирован
![Снимок экрана 2021-05-11 в 13 25 20](https://user-images.githubusercontent.com/62806448/117783827-56ec6380-b25c-11eb-99f3-00edf879ead9.png)

2. У кнопок должен быть `cursor: pointer`. Ну, тут и без дополнительных пояснений все ясно, как мне кажется

2021-05-11 09:29 UTC, TFK70 commented
@gochicus точные цвета для кнопок:

**backgroundColor:**
`#8f49e7` - default
`#FFFFFF` - active

**Icon color:**
`#FFFFFF` - default
`#8f49e7` - active

2021-05-12 08:49 UTC, TFK70 requested changes

2021-05-12 08:49 UTC, TFK70 commented on practice/web-diary/ui/theme/src/colors.ts
> +  backgroundControlsButton: '#8f49e7',
Почему у тебя тут 2 одинаковых цвета?

2021-05-12 08:49 UTC, TFK70 commented on practice/web-diary/ui/theme/src/colors.ts
> +  backgroundTrashButton: '#e74d3d',
Смысл темы - в комфортном реиспользовании ее значений
Этот цвет - красный, но ты не сможешь применить его больше нигде, потому что он своим названием привязан к кнопке удаления поста. Так не должно быть. Называй значения в теме в соответствии с их характеристиками, а не в соответствии с контекстом их использования, иначе в теме просто нет смысла

2021-05-12 09:49 UTC, TFK70 requested changes

2021-05-12 09:49 UTC, TFK70 commented on .github/workflows/deploy.yml
> +name: Deploy project
А как это тут оказалось?

2021-05-12 09:49 UTC, TFK70 commented on practice/food-delivery/src/assets/img/spinner.svg
> +<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style="margin: auto; backgrounds: none; display: block; shape-rendering: auto;" width="38px" height="38px" viewBox="
Ты же понял что ты сделал?

2021-05-12 09:59 UTC, TFK70 commented
@gochicus Еще поправь maxWidth у блока, дай тудушкам `cursor: pointer` т.к. там есть событие при наведении и добавь возможность скроллить тудушки
Часть из них навсегда остается за кадром, если их слишком много:


https://user-images.githubusercontent.com/62806448/117956386-6a69fe00-b332-11eb-814b-ee8a14f0b3df.mov

2021-05-12 10:02 UTC, gochicus commented on practice/food-delivery/src/assets/img/spinner.svg
> +<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style="margin: auto; backgrounds: none; display: block; shape-rendering: auto;" width="38px" height="38px" viewBox="
@TFK70  нет? Или ты про ветки? Как с ними лучше поступить сейчас?

2021-05-12 10:09 UTC, TFK70 commented on practice/food-delivery/src/assets/img/spinner.svg
> +<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style="margin: auto; backgrounds: none; display: block; shape-rendering: auto;" width="38px" height="38px" viewBox="
> @TFK70 нет? Или ты про ветки? Как с ними лучше поступить сейчас?

Я про строку под которой мы сейчас эти комменты пишем
Что это?

2021-05-12 10:10 UTC, gochicus commented on practice/food-delivery/src/assets/img/spinner.svg
> +<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style="margin: auto; backgrounds: none; display: block; shape-rendering: auto;" width="38px" height="38px" viewBox="
@TFK70 Видимо, штормовский рефактор.

2021-05-12 11:02 UTC, TFK70 requested changes

2021-05-12 11:02 UTC, TFK70 commented on practice/web-diary/app/src/App.tsx
> +      overflowY='auto'
Норм, только добавь еще отступ снизу, а то он при прокрутке к низу слишком сильно прижимется

2021-05-12 11:02 UTC, TFK70 commented on practice/web-diary/ui/list/src/Item.tsx
> +          className='postBackground'
Если Row не поддерживает проп cursor - значит не нужно использовать Row. Делать так - точно не вариант

Возьми Button, например, и стилизуй его

2021-05-12 11:02 UTC, TFK70 commented on practice/web-diary/ui/theme/src/globals.ts
>      button: {
Так, а это здесь зачем?

2021-05-12 11:16 UTC, gochicus commented on practice/web-diary/ui/theme/src/globals.ts
>      button: {
@TFK70 Не совсем тебя понял, курсор для кнопок задает же.

2021-05-12 11:19 UTC, TFK70 commented on practice/web-diary/ui/theme/src/globals.ts
>      button: {
@gochicus Не через globals же это делать, это для другого
Все, что относится к кнопке, должно быть в пакете `@ui/button`, а не тут

2021-05-12 11:23 UTC, gochicus commented on practice/web-diary/ui/theme/src/globals.ts
>      button: {
@TFK70 вроде styled-system `cursor ` не поддерживает,  у меня есть в` button.defaultprops ``cursor,`он не отрабатывает.

2021-05-12 12:32 UTC, TFK70 requested changes

2021-05-12 12:32 UTC, TFK70 commented on practice/web-diary/components/count-post/src/CountPost.tsx
> +      <Text>{intl.formatMessage(messages.messageCount)} </Text>
По-моему тут пробел

2021-05-12 12:32 UTC, TFK70 commented on practice/web-diary/ui/icons/svg/heart.svg
> +	 viewBox="0 0 391.837 391.837" style="enable-backgrounds:new 0 0 391.837 391.837;" xml:space="preserve">
Это тоже ресетнуть надо

2021-05-12 17:30 UTC, TFK70 requested changes

2021-05-12 17:30 UTC, TFK70 commented on practice/web-diary/ui/list/src/Item.tsx
> +      <Background backgroundColor='backgroundWhite' minWidth='250px'>
А зачем тут Background вообще? В сафари, например, это так не работает:
![Снимок экрана 2021-05-12 в 22 25 52](https://user-images.githubusercontent.com/62806448/118018273-04509b80-b371-11eb-98b8-35ec9bbb8b4c.png)

И скинь дефолтные стили у button, по типу outline, сделай color: inherit. Тоже для кроссбраузерности, тот же сафари, например, накидывает на кнопку доп стили

2021-05-12 17:30 UTC, TFK70 commented on practice/web-diary/ui/theme/src/colors.ts
>    white: 'white',
В теме должны быть только явные hex значения цветов

2021-05-12 17:30 UTC, TFK70 commented on practice/web-diary/ui/button/src/Button.tsx
>    border: '1px solid #6c757d',
Я же говорил что с этим делать
Все значения должны браться из темы

В данном случае тебе нужно только 1px solid, цвет должен идти в backgroundColor чтобы из темы зацепиться

2021-05-12 17:30 UTC, TFK70 commented on practice/web-diary/ui/background/src/Background.tsx
> +  backgroundColor: '#59b2da',
То же самое

2021-05-13 19:07 UTC, TFK70 requested changes

2021-05-13 19:07 UTC, TFK70 commented on practice/web-diary/ui/background/src/Background.tsx
> +  backgroundColor: 'backgroundGradient',
Такого цвета нет

2021-05-13 19:07 UTC, TFK70 commented on practice/web-diary/ui/button/src/Button.tsx
> +  borderColor: 'backgroundWhite',
*border*Color: '*background*White'

Я говорил по поводу нейминга значений в теме

2021-05-13 19:07 UTC, TFK70 commented on practice/web-diary/ui/theme/src/colors.ts
>    defaultPurple: '#8f49e7',
**white** - ok
**lightRed** - ok
**defaultPurple** - не ок, просто purple и так будет подразумевать дефолтный оттенок, да и в твоем приложении только одна вариация пурпурного используется

2021-05-13 19:07 UTC, TFK70 commented on practice/web-diary/ui/theme/src/colors.ts
>    backgroundWhite: '#f2f2f2',
Не ок тк привязано к контексту
Его нужно назвать исходя из оттенка (например semiWhite), но если [погуглить](https://www.color-hex.com/color/f2f2f2) конкретно этот цвет, то окажется что это оттенок серого (`Gray95`), поэтому за основу нужно брать `gray` и добавить к нему префикс. `dustyGray` вполне сойдет

2021-05-13 19:07 UTC, TFK70 commented on practice/web-diary/ui/theme/src/globals.ts
> +    button: {
??
Я же к этой же строке ревью коммент делал что "globals не для этого", зачем ты опять тут кнопку стилизуешь?

2021-05-13 19:07 UTC, TFK70 commented on practice/web-diary/ui/theme/src/globals.ts
> +    button: {
Ты не понял как мы с `cursor: 'pointer'` поступили и почему?

2021-05-13 23:33 UTC, gochicus commented on practice/web-diary/ui/theme/src/globals.ts
> +    button: {
@TFK70 Тут происходит сброс дефолтных стиле.

2021-05-13 23:34 UTC, gochicus commented on practice/web-diary/ui/background/src/Background.tsx
> +  backgroundColor: 'backgroundGradient',
@TFK70 а как тогда? Вроде решали же,что градиент в этот в бэкграунде ок.

2021-05-14 02:44 UTC, TFK70 commented on practice/web-diary/ui/theme/src/globals.ts
> +    button: {
@gochicus я вижу что тут происходит, почему это находится здесь?

2021-05-14 02:45 UTC, TFK70 commented on practice/web-diary/ui/background/src/Background.tsx
> +  backgroundColor: 'backgroundGradient',
@gochicus каким образом styled system в данном случае обратится в тему?

2021-05-14 10:02 UTC, TFK70 requested changes

2021-05-14 10:02 UTC, TFK70 commented on practice/web-diary/components/switcher-post-status/src/SwitcherPostStatus.tsx
> +          backgroundColor='purple'
Добавь стили для activeState в кнопках фильтров по аналогии с like и important

2021-05-14 10:02 UTC, TFK70 commented on practice/web-diary/ui/button/src/Button.tsx
> +    backgroundColor: 'transparent',
Это убери или перенеси в defaultProps

2021-05-14 10:02 UTC, TFK70 commented on practice/web-diary/ui/list/src/Item.tsx
> +          onMouseOver={() => setVisible('visible')}
По-моему у visible есть только 2 состояния: visible и invisible
Используй boolean (visible true/fasle)

2021-05-14 10:02 UTC, TFK70 commented on practice/web-diary/ui/list/src/Item.tsx
> +          onMouseOver={() => setVisible('visible')}
Так будет лучше тк к булу можно применять логические операторы и с ними сложнее ошибиться (например в данном случае ты можешь сделать опечатку в строке и у тебя работать ничего не будет, а опечатка в true/false сразу будет бросаться в глаза)

2021-05-14 10:32 UTC, gochicus commented on practice/web-diary/ui/button/src/Button.tsx
> +    backgroundColor: 'transparent',
@TFK70 Если в дефолт убрать, то они не работают. `outline` по крайней мере

2021-05-14 11:10 UTC, TFK70 commented on practice/web-diary/ui/button/src/Button.tsx
> +    backgroundColor: 'transparent',
@gochicus покажи код

2021-05-14 11:12 UTC, gochicus commented on practice/web-diary/ui/button/src/Button.tsx
> +    backgroundColor: 'transparent',
`export const Button = styled('button')(
  border,
  color,
  layout,
  typography,
  system({
    cursor: true,
  }),
)

Button.defaultProps = {
  border: '1px solid',
  borderColor: 'lightGrey',
  textAlign: 'center',
  padding: '6px 12px',
  fontSize: 'small',
  cursor: 'pointer',
  outline: 'none',
  color: 'inherit',
  backgroundColor: 'transparent',
}
`

2021-05-14 11:15 UTC, TFK70 commented on practice/web-diary/ui/button/src/Button.tsx
> +    backgroundColor: 'transparent',
@gochicus а зачем было все убирать в defaultProps?
Я указал только на backgroundColor потому что он у тебя зачем-то сетается внутри в 'transparent' и имеет дефолтный проп с пурпурным цветом одновременно, сейчас ничего не работает потому что Button не принимается пропсы по типу outline и тд

2021-05-14 11:16 UTC, gochicus commented on practice/web-diary/ui/button/src/Button.tsx
> +    backgroundColor: 'transparent',
@TFK70 А, тогда всё ок, делаю коммит

2021-05-14 11:34 UTC, TFK70 requested changes

2021-05-14 11:34 UTC, TFK70 commented on practice/web-diary/ui/list/src/Item.tsx
> +                maxWidth='30px'
а если просто:

```javascript
height='30px'
width='30px'
```

2021-05-14 11:34 UTC, TFK70 commented on practice/web-diary/ui/theme/src/backgrounds.ts
> +  backgroundGradient: 'linear-gradient(to bottom, #65e0ce, #4b86e4)',
переименуй в blueAndGreenGradient, а то название снова к контексту привязано

2021-05-14 11:34 UTC, TFK70 commented on practice/web-diary/ui/background/src/Background.tsx
> +  ({ theme, backgroundGradient }: any) => ({ background: theme.backgrounds[backgroundGradient] }),
Тут нужно добавить проверку на наличие backgroundGradient, чтобы приложение в случае его отсутствия не падало с ошибкой

Еще его нужно вынести наверх, чтобы, опять же, в случае отсутствия backgroundGradient, сетнулось значение background из коллбека background в styled-system

В данном случае твой коллбек его оверрайдит

2021-05-14 11:45 UTC, gochicus commented on practice/web-diary/ui/background/src/Background.tsx
> +  ({ theme, backgroundGradient }: any) => ({ background: theme.backgrounds[backgroundGradient] }),
@TFK70 синтаксически проверка как должна быть реализована?

2021-05-14 11:59 UTC, TFK70 commented on practice/web-diary/ui/background/src/Background.tsx
> +  ({ theme, backgroundGradient }: any) => ({ background: theme.backgrounds[backgroundGradient] }),
@gochicus логическим оператором

2021-05-14 12:00 UTC, gochicus commented on practice/web-diary/ui/background/src/Background.tsx
> +  ({ theme, backgroundGradient }: any) => ({ background: theme.backgrounds[backgroundGradient] }),
@TFK70 имеется ввиду, должен ли он быть заключен в круглыес кобки?

2021-05-14 12:03 UTC, TFK70 commented on practice/web-diary/ui/background/src/Background.tsx
> +  ({ theme, backgroundGradient }: any) => ({ background: theme.backgrounds[backgroundGradient] }),
@gochicus код

2021-05-14 12:04 UTC, gochicus commented on practice/web-diary/ui/background/src/Background.tsx
> +  ({ theme, backgroundGradient }: any) => ({ background: theme.backgrounds[backgroundGradient] }),
@TFK70 `export const Background = styled('div')(
  ({ theme, backgroundGradient }: any) => ({ theme.backgrounds[backgroundGradient]===true)? background: theme.backgrounds[backgroundGradient]:'white' }),
  color,
  layout,
  space,
  background,
)
`

2021-05-14 12:05 UTC, TFK70 commented on practice/web-diary/ui/background/src/Background.tsx
> +  ({ theme, backgroundGradient }: any) => ({ background: theme.backgrounds[backgroundGradient] }),
@gochicus когда вставляешь код -  форматируй его
\`\`\`javascript
{код}
\`\`\`

2021-05-14 12:06 UTC, TFK70 commented on practice/web-diary/ui/background/src/Background.tsx
> +  ({ theme, backgroundGradient }: any) => ({ background: theme.backgrounds[backgroundGradient] }),
> @TFK70
> 
> ```js
> export const Background = styled('div')(
>   ({ theme, backgroundGradient }: any) => ({ (theme.backgrounds[backgroundGradient]===true)? background: theme.backgrounds[backgroundGradient]:'white' }),
>   color,
>   layout,
>   space,
>   background,
> )
> ```

Так же не будет работать

2021-05-14 12:07 UTC, gochicus commented on practice/web-diary/ui/background/src/Background.tsx
> +  ({ theme, backgroundGradient }: any) => ({ background: theme.backgrounds[backgroundGradient] }),
@TFK70 Оно и не работает, я не знаю как это оформить, потому и спрашиваю про синтаксис.

2021-05-14 12:10 UTC, TFK70 commented on practice/web-diary/ui/background/src/Background.tsx
> +  ({ theme, backgroundGradient }: any) => ({ background: theme.backgrounds[backgroundGradient] }),
@gochicus это делается так
```javascript
background: backgroundGradient ? theme.backgrounds[backgroundGradient] : 'none'
```

2021-05-14 12:11 UTC, TFK70 commented on practice/web-diary/ui/background/src/Background.tsx
> +  ({ theme, backgroundGradient }: any) => ({ background: theme.backgrounds[backgroundGradient] }),
@gochicus и если в Background приходит проп  background, то его сетнет background из styled-system и он не будет 'none' в 100% случаев

2021-05-14 12:16 UTC, gochicus commented on practice/web-diary/ui/background/src/Background.tsx
> +  ({ theme, backgroundGradient }: any) => ({ background: theme.backgrounds[backgroundGradient] }),
@TFK70 Ясно, затупил, мы осуществляем проверку уже в  background

2021-05-14 12:28 UTC, TFK70 requested changes

2021-05-14 12:28 UTC, TFK70 commented on practice/web-diary/ui/background/src/Background.tsx
> +  ({ theme, blueAndGreenGradient }: any) => ({
зачем ключ пропа было переименовывать?
backgroundGradient может быть blueAndGreen или любым другим

2021-05-14 12:28 UTC, TFK70 commented on practice/web-diary/ui/list/src/Item.tsx
>                  minWidth='30px'
а это зачем если ширина и так фиксированная?

2021-05-14 12:36 UTC, gochicus commented on practice/web-diary/ui/background/src/Background.tsx
> +  ({ theme, blueAndGreenGradient }: any) => ({
@TFK70 просто градиент пойдет?

2021-05-14 12:36 UTC, TFK70 commented on practice/web-diary/ui/background/src/Background.tsx
> +  ({ theme, blueAndGreenGradient }: any) => ({
@gochicus да,  пойдет

2021-05-14 12:42 UTC, TFK70 requested changes

2021-05-14 12:42 UTC, TFK70 commented on practice/web-diary/ui/list/src/Item.tsx
> -                width='30px'
так тебе maxWidth нужен или нет?

2021-05-14 12:42 UTC, TFK70 commented on practice/web-diary/ui/background/src/Background.tsx
> +  ({ theme, Gradient }: any) => ({
Почему с заглавной?
Пропы всегда в кэмелкейсе

2021-05-14 12:54 UTC, gochicus commented on practice/web-diary/ui/list/src/Item.tsx
> -                width='30px'
@TFK70 Нужен

2021-05-14 12:55 UTC, TFK70 commented on practice/web-diary/ui/list/src/Item.tsx
> -                width='30px'
@gochicus minWidth=30 + maxWidth=30 === ширина блока всегда равна 30, а это можно записать так: width=30
Если он тебе нужен - то куда он делся?

2021-05-14 12:56 UTC, TFK70 commented on practice/web-diary/ui/list/src/Item.tsx
> -                width='30px'
@gochicus если тебе нужен только minWidth то так все и оставь

2021-05-14 12:59 UTC, gochicus commented on practice/web-diary/ui/list/src/Item.tsx
> -                width='30px'
@TFK70 я сейчас проверяю, вроде без max оно плыть начинает, а вроде нет. На паузу поставлю и проверю

2021-05-14 13:07 UTC, TFK70 approved these changes, later dismissed

2021-05-14 14:10 UTC, TorinAsakura requested changes

2021-05-14 14:10 UTC, TorinAsakura commented on practice/web-diary/components/switcher-post-status/messages/messages.ts
> +    defaultMessage: '!',
почему часть на латинице?

2021-05-14 14:13 UTC, gochicus commented on practice/web-diary/components/switcher-post-status/messages/messages.ts
> +    defaultMessage: '!',
@TorinAsakura  кнопки управления, по размерам лучше смотрится.

2021-05-14 14:14 UTC, TorinAsakura commented on practice/web-diary/components/switcher-post-status/messages/messages.ts
> +    defaultMessage: '!',
> @TorinAsakura кнопки управления, по размерам лучше смотрится.

так не годится, тут или русский или инглиш

2021-05-14 14:42 UTC, TFK70 requested changes

2021-05-14 14:42 UTC, TFK70 commented on practice/web-diary/ui/list/src/Item.tsx
> +                  <Text fontFamily='secondary'>{postObject.post}</Text>
Шрифт у тудушек не соответствует дизайну

2021-05-14 14:53 UTC, gochicus commented on practice/web-diary/ui/list/src/Item.tsx
> +                  <Text fontFamily='secondary'>{postObject.post}</Text>
@TFK70 а какой шрифт нужно использовать?

2021-05-14 14:54 UTC, TFK70 commented on practice/web-diary/ui/list/src/Item.tsx
> +                  <Text fontFamily='secondary'>{postObject.post}</Text>
@gochicus тот же что и везде, видно же что твой шрифт и шрифт из диза не совпадают

2021-05-14 14:56 UTC, gochicus commented on practice/web-diary/ui/list/src/Item.tsx
> +                  <Text fontFamily='secondary'>{postObject.post}</Text>
@TFK70 тот же, что и в хэдере?

2021-05-14 14:58 UTC, TFK70 commented on practice/web-diary/ui/list/src/Item.tsx
> +                  <Text fontFamily='secondary'>{postObject.post}</Text>
@gochicus у тебя же везде один шрифт
secondary я только тут видел, но я его прикола не совсем понимаю если честно, он 1 в 1 как дефолтный выглядит

2021-05-14 15:09 UTC, TFK70 requested changes
Баг


https://user-images.githubusercontent.com/62806448/118290754-36d4d280-b4f0-11eb-921f-8be0b981ff80.mov

2021-05-14 15:12 UTC, gochicus commented
@TFK70 Что по твоему работает не так?

2021-05-14 15:13 UTC, TFK70 commented
@gochicus Там посты не добавляются

2021-05-14 15:14 UTC, gochicus commented
@TFK70 Кнопка all меняет цвет на неактивна, нажми на нее

2021-05-14 15:18 UTC, TFK70 commented
@gochicus Увидел, поменяй в этом месте ее значение на all пожалуйста
Смысл от состояния где ни одна тудушка не показывается

2021-05-14 15:30 UTC, gochicus commented
@TFK70 Вот так попробуй потестируй, мне кажется так завершеннее будет.

2021-05-14 15:31 UTC, TFK70 approved these changes, later dismissed

2021-05-17 04:29 UTC, TFK70 requested changes

2021-05-17 04:29 UTC, TFK70 commented on practice/web-diary/fragments/controls/package.json
> +  "name": "@fragments/controls",
Слишком общее название, конкретизируй до post controls

2021-05-17 04:29 UTC, TFK70 commented on practice/web-diary/fragments/controls/src/actions/clearPost.ts
> +  return [...postData.splice(0, -1)]
Это же экшен который все тудушки очищает? Зачем тут применять спред, делать сплайс если в 100% случае вощвращается пустой массив?

2021-05-17 04:29 UTC, TFK70 commented on practice/web-diary/fragments/form-post-add/src/FormPostAdd.tsx
> +          minWidth='252px'
Опять
Если у тебя для min и max стоит одно значение - значит размер фиксированный, а фиксированный размер задается атрибутами width/height

2021-05-17 04:29 UTC, TFK70 commented on practice/web-diary/package.json
> +    "@emotion/css": "^11.1.3"
Это тут с какой целью?

2021-05-17 04:51 UTC, gochicus commented on practice/web-diary/package.json
> +    "@emotion/css": "^11.1.3"
@TFK70  конеретезируй замечание.

2021-05-17 04:57 UTC, TFK70 commented on practice/web-diary/package.json
> +    "@emotion/css": "^11.1.3"
@gochicus Эта зависимость тут просто так находится или с какой-то целью? Это глобальный скоуп вообще-то

2021-05-17 09:15 UTC, TFK70 requested changes

2021-05-17 09:15 UTC, TFK70 commented on practice/web-diary/fragments/postControls/package.json
> +  "name": "@fragments/post-controls",
Есть идеи что тут не так?:
![image](https://user-images.githubusercontent.com/62806448/118464324-29029580-b71a-11eb-9501-e32ce96d2c25.png)

2021-05-17 09:15 UTC, TFK70 commented on practice/web-diary/fragments/postControls/package.json
> +  "name": "@fragments/post-controls",
@gochicus и тут
![image](https://user-images.githubusercontent.com/62806448/118464513-6109d880-b71a-11eb-80ca-d32b20b01466.png)

2021-05-17 09:35 UTC, gochicus commented on practice/web-diary/fragments/postControls/package.json
> +  "name": "@fragments/post-controls",
@TFK70 Если ты про `status`, то тут спорно, поскольку в компоненте теперь осуществляется и подсчет и очистка постов.

2021-05-17 10:32 UTC, TFK70 commented on practice/web-diary/fragments/postControls/package.json
> +  "name": "@fragments/post-controls",
@gochicus я оставил коммент под строкой чтобы вести обсуждение изолированно и не засирать пр комментами
Помимо строки тут есть еще 2 коммента со скринами, обрати на них внимание

2021-05-17 10:33 UTC, gochicus commented on practice/web-diary/fragments/postControls/package.json
> +  "name": "@fragments/post-controls",
@TFK70 Я прекрасно вижу 2 коммента со скринами и все ещё не понимаю, что ты хотел сказать.

2021-05-17 10:35 UTC, TFK70 commented on practice/web-diary/fragments/postControls/package.json
> +  "name": "@fragments/post-controls",
@gochicus почему у тебя директории названы в кэмелкейсе?
В fragments у тебя вообще часть в кэмелкейсе, а часть - нет

2021-05-17 10:37 UTC, gochicus commented on practice/web-diary/fragments/postControls/package.json
> +  "name": "@fragments/post-controls",
@TFK70 всё, теперь понятно что ты имел ввиду.  Поправлю.

2021-05-17 14:31 UTC, TFK70 requested changes

2021-05-17 14:31 UTC, TFK70 commented on practice/web-diary/app/src/App.tsx
> +          <Background backgroundColor='white' maxWidth='500px'>
Не суй все подряд в background
Используй там где нужны background значения не применимые к обычным компонентам, по типо backgroundImage или того же градиента

2021-05-17 14:31 UTC, TFK70 commented on practice/web-diary/ui/list/src/Item.tsx
> +          maxWidth='328px'
Пройдись по проекту, почисти грязные места

2021-05-18 07:18 UTC, TFK70 approved these changes

2021-05-18 07:50 UTC, TFK70 requested changes

2021-05-18 07:50 UTC, TFK70 commented on practice/web-diary/fragments/post-сontrols/src/actions/clearPost.ts
> +export const clearPost = () => {
А вообще это же можно не выносить в отдельный экшен
Точнее не нужно

2021-05-18 09:44 UTC, TFK70 approved these changes

2021-05-18 09:46 UTC, TFK70 requested changes

2021-05-18 09:46 UTC, TFK70 commented on practice/web-diary/app/index.tsx
> +    { post: 'yesterday', id: 1 },
id должен генерироваться под капотом

2021-05-18 14:42 UTC, TFK70 requested changes

2021-05-18 14:42 UTC, TFK70 commented on practice/web-diary/fragments/form-post-add/src/FormPostAdd.tsx
> +import { mocks }                      from './actions'
1. Не дублируй импорты
2. Нет нужды тащить mocks сюда. Бери их прямо внутри fetchinitialData экшена

2021-05-18 14:42 UTC, TFK70 commented on practice/web-diary/fragments/form-post-add/src/actions/fetchInitialData.ts
> +      result.push(element)
Немного не понимаю смысла
В addItem можно передавать postData, а потом этот же postData в return прописывать. На самом деле эту функцию можно в одну строку написать:
```javascript
export const fetchInitialData = (mocks, postData) => [...postData,mocks.map(item => addItem(item,postData))]
```
Примерно так

2021-05-18 15:00 UTC, gochicus commented on practice/web-diary/fragments/form-post-add/src/actions/fetchInitialData.ts
> +      result.push(element)
@TFK70 Такой код  нерабочий.  Мне прямо обязательно изыскивать решения в одну строку?

2021-05-18 16:27 UTC, TFK70 requested changes

2021-05-18 16:27 UTC, TFK70 commented on practice/web-diary/ui/list/src/Item.tsx
> +  console.log(postObject.id)
Тебе же линтер даже на него ругается

2021-05-18 16:29 UTC, gochicus commented on practice/web-diary/ui/list/src/Item.tsx
> +  console.log(postObject.id)
@TFK70 Как ни странно, пропустил линтер. Сейчас поправлю.

2021-05-18 16:30 UTC, TFK70 commented on practice/web-diary/ui/list/src/Item.tsx
> +  console.log(postObject.id)
@gochicus ну просто это ворнинг а не ошибка

2021-05-18 16:32 UTC, TFK70 submitted a review, later dismissed

2021-05-18 19:39 UTC, TorinAsakura requested changes

2021-05-18 19:39 UTC, TorinAsakura commented on practice/web-diary/app/src/App.tsx
> +    <Background gradient='blueAndGreenGradient' height='100vh' width='100vw' overflowY='auto'>
В app должен быть только маунт, никакой логики или вёрстки

2021-05-18 23:39 UTC, gochicus commented on practice/web-diary/app/src/App.tsx
> +    <Background gradient='blueAndGreenGradient' height='100vh' width='100vw' overflowY='auto'>
@TorinAsakura  Что допустимо оставить в App? Например, направляющие Column объединяют все компоненты только здесь.

2021-05-19 10:53 UTC, TFK70 requested changes

2021-05-19 10:53 UTC, TFK70 commented on practice/web-diary/app/index.tsx
> +ReactDOM.render(<App />, document.getElementById('root'))
Укажи в вебпак конфиге как entry 'app/src/index.tsx' и перенеси все отсюда в src/index, а этот удали
От него вообще смысла нет, просто файл лишний

2021-05-19 10:53 UTC, TFK70 commented on practice/web-diary/webpack.config.ts
> +export const target = 'web'
target по умолчанию тот который тебе нужен, его вообще можно отсюда убрать

2021-05-19 15:17 UTC, TFK70 approved these changes

2021-05-20 10:23 UTC, TFK70 requested changes

2021-05-20 10:23 UTC, TFK70 commented on practice/web-diary/app/src/App.tsx
> +      <ThemeProvider theme={theme}>
Вынеси этот провайдер в ui/theme, он должен прокидывать тему внутри себя
Использование:

```javascript
import {.ThemeProvider } from '@ui/theme'

const App = () => (
   <ThemeProvider> // где в провайдер уже прокинуто значение theme
       ....
   </ThemeProvider>
)
```

2021-05-20 15:00 UTC, gochicus commented on practice/web-diary/app/src/App.tsx
> +      <ThemeProvider theme={theme}>
@TFK70 Вообще не понял что ты хочешь, он же из emotion идет.

2021-05-20 15:41 UTC, gochicus commented on practice/web-diary/app/src/App.tsx
> +      <ThemeProvider theme={theme}>
@TFK70  делаю подобную реализацию,не работает, что мне следует учесть? 
`export const Theme = ({children}) => <ThemeProvider theme = {theme}> </ThemeProvider>`

2021-05-20 15:44 UTC, TFK70 commented on practice/web-diary/app/src/App.tsx
> +      <ThemeProvider theme={theme}>
@gochicus 
1. То что у тебя проп children не используется
2. Лучше прокидывать в ThemeProvider все пропсы для большей гибкости, а не только children

2021-05-20 15:48 UTC, gochicus commented on practice/web-diary/app/src/App.tsx
> +      <ThemeProvider theme={theme}>
@TFK70  Если пропсами все провайдеры прокидывать, тайпскрипт ошибку выдаёт.

2021-05-20 15:51 UTC, TFK70 commented on practice/web-diary/app/src/App.tsx
> +      <ThemeProvider theme={theme}>
@gochicus а зачем так делать? провайдеры это тоже чилдрены

2021-05-20 15:53 UTC, gochicus commented on practice/web-diary/app/src/App.tsx
> +      <ThemeProvider theme={theme}>
@TFK70 тогда какие другие пропсы имелись ввиду и как должно использоваться чилдрен?

2021-05-20 15:58 UTC, TFK70 commented on practice/web-diary/app/src/App.tsx
> +      <ThemeProvider theme={theme}>
@gochicus что есть children в таком случае?

2021-05-20 16:02 UTC, gochicus commented on practice/web-diary/app/src/App.tsx
> +      <ThemeProvider theme={theme}>
@TFK70 в Theme это пропсы, конкретно это все, что обёрнуто в него. Но я не могу прописать App  children. Тайпскрипт ошибку пишет

2021-05-20 16:05 UTC, TFK70 commented on practice/web-diary/app/src/App.tsx
> +      <ThemeProvider theme={theme}>
@gochicus зачем прописывать в App children?

2021-05-21 12:27 UTC, TFK70 requested changes
![image](https://user-images.githubusercontent.com/62806448/119136976-bc5d0300-ba59-11eb-9e95-4d79b0d1894a.png)

2021-05-21 14:15 UTC, TFK70 requested changes

2021-05-21 14:15 UTC, TFK70 commented on practice/web-diary/fragments/diary/src/Diary.tsx
> +        <Column alignItems='center'>
Есть ли смысл от этой колонке если она уже находится в колонке?

2021-05-21 14:15 UTC, TFK70 commented on practice/web-diary/fragments/form-post-add/src/FormPostAdd.tsx
> +      <Box>
Box стоит использовать для обертки нескольких компонентов воедино, здесь от него смысла вроде как нет

2021-05-21 14:15 UTC, TFK70 commented on practice/web-diary/fragments/post-сontrols/src/PostControls.tsx
> +      <Box justifyContent='center'>
Оно тут точно надо?
```javascript
<Box>
   <Row>
        ....
   </Row>
</Box>
```

2021-05-21 14:15 UTC, TFK70 commented on practice/web-diary/fragments/post-сontrols/src/PostControls.tsx
> +        <Box>
Здесь тоже в Box нет необходимости тк элемент один
А вот [тут](https://github.com/atls-academy/gochicus.github.io/pull/80/files#diff-7721268a62841e6a4fbecde9d19422e713e2d85c7c88c0a6519d8f5cc2e5ef5dR70), например, все грамотно

2021-05-21 14:15 UTC, TFK70 commented on practice/web-diary/ui/layout/src/Box.tsx
> +    cursor: true,
Боксу-то это зачем?

2021-05-21 14:15 UTC, TFK70 commented on practice/web-diary/ui/list/src/Item.tsx
> +          <Row jstifyContent='center'>
Этот Row, видимо, тоже тут особо большой роли не играет, раз тут justifyContent с опечаткой написано и это ни на что не повлияло

2021-05-21 14:15 UTC, TFK70 commented on practice/web-diary/ui/list/src/Item.tsx
> +              <Column justifyContent='center'>
Проблема, которую решает эта колонка можно решить с помощью alignItems у родителя

2021-05-21 15:12 UTC, gochicus commented on practice/web-diary/ui/layout/src/Box.tsx
> +    cursor: true,
@TFK70 чтобы при наведении на блок поста курсор менялся. Была такая задача.

2021-05-21 15:15 UTC, TorinAsakura commented on practice/web-diary/ui/layout/src/Box.tsx
> +    cursor: true,
что за бредятина? блок не должен быть активным элементом. Нужен блок с курсором? Сделай кнопку или линк с нужными стилями.

2021-05-21 15:51 UTC, TFK70 requested changes

2021-05-21 15:51 UTC, TFK70 commented on practice/web-diary/ui/list/src/Item.tsx
> +
1. Вайтспейс?
2. Кое-какие изменения в этом файле все портят в сафари (в хроме все нормально):
![image](https://user-images.githubusercontent.com/62806448/119164708-1f5c9300-ba76-11eb-9098-139bb5720f51.png)

2021-05-21 15:58 UTC, gochicus commented on practice/web-diary/ui/list/src/Item.tsx
> +
@TFK70 1) Есть подробности что именно не так? 2) Кнопки отображаются при наведении? 3) До изменений  всё было как и в хроме? 4)  Если речь идет только о цвете поста, решит ли проблему добавление цвета  фона туда?

2021-05-21 16:15 UTC, TFK70 commented on practice/web-diary/ui/list/src/Item.tsx
> +
@gochicus 
1. Все работает как раньше
2. Проблема в том что ты не сбросил у Button некоторые дефолтные стили и они наследуются от браузера. У сафари по умолчанию для баттона ставится background-color: buttonface

2021-05-22 07:44 UTC, TFK70 requested changes

2021-05-22 07:44 UTC, TFK70 commented on practice/web-diary/ui/button/src/Button.tsx
> +    backgroundColor: 'transparent',
Тут лучше использовать `background: none` тк таким образом ты сбрасываешь не только backgroundColor, но и backgroundImage разом

Конкретно в твоем кейсе это ни на что не повлияет, но почти всегда `background: none` > `backgroundColor: transparent`

2021-05-22 07:44 UTC, TFK70 commented on practice/web-diary/fragments/form-post-add/src/FormPostAdd.tsx
> +import { fetchInitialData }           from './actions'
Дубль импортов

В целом такое допускается, но код нужно писать в одном стиле, так что засунь все это под один

2021-05-22 07:44 UTC, TFK70 commented on practice/web-diary/ui/input/src/Input.tsx
>    display: 'block',
block? У нас же flex везде

2021-05-22 07:44 UTC, TFK70 commented on practice/web-diary/ui/input/src/Input.tsx
>    display: 'block',
И там ниже в дефолт пропсах цвета опять захардкоженные

2021-05-22 07:44 UTC, TFK70 commented on practice/web-diary/app/package.json
> +    "@fragments/form-post-add": "0.0.0",
Если я не ошибаюсь то этот пекедж относится к app в котором лишь происходит маунт Diary
Зачем тут все эти зависимости?

2021-05-22 10:12 UTC, TorinAsakura requested changes
в целом - уже близко, добивай

2021-05-22 10:12 UTC, TorinAsakura commented on practice/web-diary/ui/input/src/Input.tsx
> +  background: 'white',
если у тебя не определена white и ты берёшь её из browser api - это неправильно, ты не контролируешь процесс, ты доверяешь другой стороне

первоначальный вариант выглядел правильней
определи у себя white и будет ок

также необходимо определять backgroundColor, так как backgroundImage это вообще другая тема со своими параметрами

2021-05-22 10:12 UTC, TorinAsakura commented on practice/web-diary/ui/input/src/Input.tsx
>    minWidth: '200px',
зачем в инпате minWidth? 
Вот пример нормальной стилизации инпата
https://github.com/atls/uikit/blob/master/ui-parts/input/src/input/base/base.styles.ts#L3

2021-05-22 10:17 UTC, gochicus commented on practice/web-diary/ui/input/src/Input.tsx
> +  background: 'white',
@TorinAsakura имеется ввиду определение white в теме? Просто он там определен.

2021-05-22 10:22 UTC, TorinAsakura commented on practice/web-diary/ui/input/src/Input.tsx
> +  background: 'white',
Безусловно, мой маленький дамбат

2021-05-22 10:41 UTC, TorinAsakura requested changes

2021-05-22 10:41 UTC, TorinAsakura commented on practice/web-diary/ui/list/src/Item.tsx
> +              minHeight='30px'
я не понимаю для чего ты задаёшь минимальные значения?

2021-05-22 10:41 UTC, TorinAsakura commented on practice/web-diary/ui/list/src/Item.tsx
> +          <Button minWidth='215px' minHeight='40px' justifyContent='flex-start' alignItems='center'>
снова, зачем тут минимальные величины?

2021-05-22 10:41 UTC, TorinAsakura commented on practice/web-diary/ui/theme/src/theme/index.ts
> +export * from '../globals'
случайно затесался?

2021-05-22 10:41 UTC, TorinAsakura commented on practice/web-diary/ui/input/src/Input.tsx
>    padding: '6px 10px',
зачем тебе размер шрифта и паддинги в инпате?

2021-05-22 10:44 UTC, gochicus commented on practice/web-diary/ui/input/src/Input.tsx
>    padding: '6px 10px',
@TorinAsakura для placeholder, задать значение по умолчанию проще, чем прописывать значение каждому.  Какой-то необходимости менять размеры шрифтов для них нет.

2021-05-23 09:31 UTC, TFK70 requested changes
И, разумеется, коцанный дизайн (шрифты):

![image](https://user-images.githubusercontent.com/62806448/119255141-775cdc00-bbd3-11eb-823e-d7039be3c151.png)

2021-05-23 09:31 UTC, TFK70 commented on practice/web-diary/fragments/form-post-add/src/FormPostAdd.tsx
> +        padding='6px 10px'
Это те самые паддинги в инпате которые буквально в предыдущем ревью попросили убрать?

2021-05-23 09:31 UTC, TFK70 commented on practice/web-diary/fragments/form-post-add/src/FormPostAdd.tsx
> +        maxHeight='40px'
То что ты заменил min на max вообще никакой погоды не делает, дело было в том что таких точек по-хорошему вообще быть не должно, все размеры задаются через флексы
width=100%, если надо порезать - в контейнер добавляешь Layout с flexBasis или flexGrow

2021-05-23 09:31 UTC, TFK70 commented on practice/web-diary/fragments/form-post-add/src/FormPostAdd.tsx
>          color='white'
Зачем? У тебя же уже есть Text который отвечает за текст

2021-05-23 09:31 UTC, TFK70 commented on practice/web-diary/fragments/post-сontrols/src/PostControls.tsx
> +      <Row justifyContent='center' maxWidth='328px'>
Если ты задаешь width для Row - у тебя что-то идет не так

2021-05-23 09:31 UTC, TFK70 commented on practice/web-diary/fragments/post-сontrols/src/PostControls.tsx
> +      <Row justifyContent='center' maxWidth='328px'>
Если конкретнее - width так же должен регулироваться средствами флекса
Лейауты с flexBasis и flexGrow

2021-05-23 09:31 UTC, TFK70 commented on practice/web-diary/fragments/post-сontrols/src/PostControls.tsx
> +          <Text marginLeft='2px'>{intl.formatMessage(messages.all)}</Text>
Никаких маржинов

2021-05-23 09:31 UTC, TFK70 commented on practice/web-diary/fragments/post-сontrols/src/PostControls.tsx
> +          <Text paddingLeft='10px'>{intl.formatMessage(messages.like)}</Text>
По-моему твои стили не слишком универсальные раз тебе нужно прибегать к паддингам с маржинами чтобы текст в кнопку засунуть. Это плохо

2021-05-23 09:31 UTC, TFK70 commented on practice/web-diary/fragments/post-сontrols/src/PostControls.tsx
>            color={status === 'important' ? 'purple' : 'white'}
То же
У тебя для этого есть Text

2021-05-23 09:31 UTC, TFK70 commented on practice/web-diary/fragments/post-сontrols/src/PostControls.tsx
> +          <Text padding='0px' fontSize='basic'>
padding=0??

2021-05-23 09:31 UTC, TFK70 commented on practice/web-diary/fragments/post-сontrols/src/PostControls.tsx
> +          <Text padding='0px' fontSize='basic'>
Вообще не понимаю этого

2021-05-23 09:31 UTC, TFK70 commented on practice/web-diary/fragments/post-сontrols/src/PostControls.tsx
> +          <Text margin='5px 20px' fontSize='basic' padding='0px'>
С чего ты опять-то начал маржины использовать?

2021-05-23 09:31 UTC, TFK70 commented on practice/web-diary/ui/list/src/Item.tsx
> +              <Box>
Зачем это было в Box пихать?

2021-05-23 09:31 UTC, TFK70 commented on practice/web-diary/ui/button/src/Button.tsx
> +export const createBaseStyles: styleFn = () => () => ({
Они описаны немного некорректно

2021-05-23 09:31 UTC, TFK70 commented on practice/web-diary/ui/text/src/Text.tsx
> +export const createTextStyles: styleFn = () => () => ({
А таких вообще не бывает

2021-05-26 12:31 UTC, TFK70 requested changes

2021-05-26 12:31 UTC, TFK70 commented on practice/web-diary/ui/list/src/Item.tsx
>    const [postData, setPostData] = usePostData()
Антипаттерн

2021-05-31 12:59 UTC, TFK70 requested changes

2021-05-31 12:59 UTC, TFK70 commented on practice/web-diary/fragments/diary/src/Diary.tsx
> +        <Box backgroundColor='white' maxWidth='500px'>
А в чем проблема задать в процентах?
Типа "чтобы он занимал не более 30% ширины всего экрана"

2021-05-31 12:59 UTC, TFK70 commented on practice/web-diary/fragments/header/src/Header.tsx
> +    <Row minWidth='320px'>
Row и width в пикселях, уже обсуждали

2021-05-31 12:59 UTC, TFK70 commented on practice/web-diary/fragments/header/src/Header.tsx
> +    <Row minWidth='320px'>
Во-первых у Row ширина всегда 100%
Во-вторых проведи эксперимент: возьми какой-нибудь контейнер и задай ему большую ширину в пикселях (1000-1500 пикселей, например) и начни сужать окно браузера. Запомни результат, замени ширину с пикселей на 80%, сделай то же самое и сравни результаты

2021-05-31 12:59 UTC, TFK70 commented on practice/web-diary/fragments/post-сontrols/src/PostControls.tsx
> +    <Column width={'92%'}>
Богда ради не ставь эти скобки
Просто width='92%'

2021-05-31 12:59 UTC, TFK70 commented on practice/web-diary/fragments/post-сontrols/src/PostControls.tsx
> +          size={1}
?
Хочешь сказать у этого инпута height=1?

2021-05-31 12:59 UTC, TFK70 commented on practice/web-diary/ui/button/src/Button.style.ts
> +  display: 'flex',
В этом нет смысла, тогда уж проще подтянуть display из styled-system
Но display='none'/'flex' должен регулироваться компонентом Condition, так что дисплеи отсюда лучше убрать

2021-05-31 12:59 UTC, TFK70 commented on practice/web-diary/ui/list/src/Item.tsx
>              <Text>{postObject.post}</Text>
Кстати самый первый айтем по какой-то причине выглядит отличным от остальных, будто с паддингами, так что ищи ошибку:
![image](https://user-images.githubusercontent.com/62806448/120196674-8c6fe580-c239-11eb-8510-277dbc55987e.png)

2021-05-31 12:59 UTC, TFK70 commented on practice/web-diary/ui/text/src/Text.tsx
> +export const createTextStyles: styleFn = () => () => ({
@gochicus createTextStyles почему остались?
Тебе тут скорее надо подтянуть функции из styled-system и все это задать в defaultProps, а то будто у тебя всегда во всем приложении текст будет 16 пикселей и с паддингами

2021-05-31 12:59 UTC, TFK70 commented on practice/web-diary/ui/theme/src/theme/colors.ts
> +  white: '#FFFFFF',
Если ты все цвета пишешь в lowercase - тогда уж соблюдай это везде

2021-05-31 13:25 UTC, TorinAsakura commented on practice/web-diary/fragments/post-сontrols/src/PostControls.tsx
> +    <Column width={'92%'}>
> Бооога ради не ставь эти скобки
> Просто width='92%'

объясни их назначение, видишь же - не понимает

2021-05-31 13:33 UTC, TFK70 commented on practice/web-diary/fragments/post-сontrols/src/PostControls.tsx
> +    <Column width={'92%'}>
@gochicus конкретно здесь у них вообще никакого назначения нет, просто код уродуют, но вот [тут](https://github.com/atls-academy/gochicus.github.io/pull/80/files/b582848f26b04a493dd13b9ed8f43625e5534ce4#diff-7721268a62841e6a4fbecde9d19422e713e2d85c7c88c0a6519d8f5cc2e5ef5dR32) ты вроде как их не используешь

Они нужны только когда прям нужны, когда пишется логическое выражение или число (как [тут](https://github.com/atls-academy/gochicus.github.io/pull/80/files/b582848f26b04a493dd13b9ed8f43625e5534ce4#diff-7721268a62841e6a4fbecde9d19422e713e2d85c7c88c0a6519d8f5cc2e5ef5dR24))
Во всех остальных случаях (включая этот) - от них больше вреда чем пользы

2021-05-31 14:42 UTC, gochicus commented on practice/web-diary/fragments/post-сontrols/src/PostControls.tsx
> +    <Column width={'92%'}>
@TFK70 Скобки шторм по умолчанию ставит.

2021-05-31 14:44 UTC, TorinAsakura commented on practice/web-diary/fragments/post-сontrols/src/PostControls.tsx
> +    <Column width={'92%'}>
я тебе уже объяснял что такое шторм, отмазываться в другом месте будешь Саша

2021-05-31 14:45 UTC, TFK70 commented on practice/web-diary/fragments/post-сontrols/src/PostControls.tsx
> +    <Column width={'92%'}>
@gochicus я знаю, но шторм - это в первую очередь твой интрумент, а твой инструмент должен удовлетворять в первую очередь тебя для более продуктивной работы
Благо его можно конфигурировать, так что гугл -> webstorm configure autocomplete или что-то в этом роде

2021-05-31 18:32 UTC, TFK70 requested changes

2021-05-31 18:32 UTC, TFK70 commented on practice/web-diary/fragments/diary/src/Diary.tsx
> +        <Box backgroundColor='white' width='20%' maxWidth='30%'>
Вот тут не понял немного
Если у тебя width='20%' то он всегда будет занимать 20% от родителя/экрана, он никогда не будет больше или меньше 20%, так вот в таком случае зачем здесь maxWidth на 30%?

2021-05-31 18:32 UTC, TFK70 commented on practice/web-diary/fragments/header/src/Header.tsx
> +    <Box width='100%'>
`<Box width='100%'>` === `<Row>`

2021-05-31 18:32 UTC, TFK70 commented on practice/web-diary/ui/button/src/Button.tsx
> +import { colorStyles }            from './Button.style'
Здесь ты снова за код стайлом не следишь
Либо пихай импорты в один, либо разбивай на несколько мелких, но, как я уже говорил, опираясь на твой остальной код - импорты нужно засунуть в один, чтобы не противоречить самому себе

2021-05-31 18:32 UTC, TFK70 commented on practice/web-diary/ui/button/src/Button.tsx
> +import { colorStyles }            from './Button.style'
На самом деле код это никакой не код, это просто обычный текст в текстовом файлике, а у тебя есть куча инструментов для удобного представления/форматирования этого текста, так что очень странно этим не пользоваться учитывая что тебе же от этого будет хуже в первую очередь

2021-05-31 18:32 UTC, TFK70 commented on practice/web-diary/ui/condition/src/Condition.tsx
> +import { Layout } from '../../layout'
Ну тут и так все ясно, вроде бы

2021-05-31 18:32 UTC, TFK70 commented on practice/web-diary/ui/condition/src/Condition.tsx
> +  return match ? children : <Layout flexBasis='200px' />
Нет
Я понял для чего это, я даже готов согласиться с тем что это очень удобно, но так делать нельзя
Рушится зона ответственности твоего Condition. Его цель - условно отображать компонент, так что в твоем итеме нужно сделать кондишн на кнопку и кондишн на Layout

Ну, очевидно, в большинстве мест лейаут с флекс базисом 200 пикселей на месте твоего компонента будет мешать

2021-05-31 18:32 UTC, TFK70 commented on practice/web-diary/ui/list/src/Item.tsx
> +                  display={visible === true ? 'show' : 'hide'}
А тут чего?
Запусти через ctrl+F поиск по этой строке и замени на кондишн

2021-06-02 09:39 UTC, TFK70 requested changes

2021-06-02 09:39 UTC, TFK70 commented on practice/web-diary/fragments/header/src/Header.tsx
> +    <Row width='100%'>
Ты даешь Row с width 100%  еще один width 100%?

2021-06-02 09:39 UTC, TFK70 commented on practice/web-diary/ui/condition/src/LayoutCondition.tsx
> +  return match ? <Layout flexBasis='20px' /> : <Layout flexBasis='200px' />
В этом нет необходимости, просто засунь Layout в Condition

2021-06-02 09:39 UTC, TFK70 commented on practice/web-diary/fragments/post-сontrols/src/PostControls.tsx
> +          <Input
Обрати внимание на текст внутри инпута
Размеры плейсхолдера не пропорциональны размерам инпута (слишком маленький)
Стили самого текста внутри инпута не совпадают со стилями плейсхолдера (нет отступа слева, тоже не пропорциональный размер)

2021-06-02 09:47 UTC, TFK70 commented on practice/web-diary/fragments/post-сontrols/src/PostControls.tsx
> +          <Input
https://user-images.githubusercontent.com/62806448/120459197-64a38d80-c3b1-11eb-8267-ba6233352e16.mov

2021-06-02 09:49 UTC, TFK70 requested changes

2021-06-02 09:49 UTC, TFK70 commented on practice/web-diary/fragments/post-сontrols/src/PostControls.tsx
> +            display='show'
Почему display: show?
1. Дисплею нету никакого смысла задавать кастомные значения
2. У тебя для этого есть Condition, если я оставил коммент только в итеме это не значит что на весь остальной код надо забить

2021-06-02 12:16 UTC, TFK70 requested changes

2021-06-02 12:16 UTC, TFK70 commented on practice/web-diary/ui/list/src/Item.tsx
>        <Box backgroundColor='lightGrey' width='100%'>
Итемы не проходят проверку на перегрузку контентом:

![image](https://user-images.githubusercontent.com/62806448/120477846-a9392400-c3c5-11eb-8470-3dc35bd98944.png)

2021-06-02 12:16 UTC, TFK70 commented on practice/web-diary/ui/list/src/Item.tsx
> +            <Layout flexBasis='200px' />{' '}
А че там за пробел?

2021-06-02 12:16 UTC, TFK70 commented on practice/web-diary/ui/input/src/base/base.styles.ts
> +  padding: '0 6px',
Паддинг должен быть у текста внутри инпута, а не у инпута
Погугли про псевдоклассы у инпута

2021-06-02 12:21 UTC, gochicus commented on practice/web-diary/ui/list/src/Item.tsx
>        <Box backgroundColor='lightGrey' width='100%'>
@TFK70 а что это?

2021-06-02 12:34 UTC, TFK70 commented on practice/web-diary/ui/list/src/Item.tsx
>        <Box backgroundColor='lightGrey' width='100%'>
@gochicus ну введи тудушку с кучей текста

2021-06-02 13:35 UTC, gochicus commented on practice/web-diary/ui/input/src/base/base.styles.ts
> +  padding: '0 6px',
@TFK70 Погуглил, посмотрел, в официальной доке у инпута нет псевдоклассов для значений( в смысле value). Погуглил как делается стилизация такая, и попадается, что в самом инпуте и делается.

2021-06-02 13:41 UTC, TFK70 commented on practice/web-diary/ui/input/src/base/base.styles.ts
> +  padding: '0 6px',
@gochicus что по-твоему "в самом инпуте" значит?
дай код

2021-06-02 13:43 UTC, gochicus commented on practice/web-diary/ui/input/src/base/base.styles.ts
> +  padding: '0 6px',
@TFK70 
`input {
	width: 300px;
	font-size: 13px;
	padding: 6px 0 4px 10px;
	border: 1px solid #cecece;
	background: #F6F6f6;
	border-radius: 8px;
}`

2021-06-02 13:45 UTC, TFK70 commented on practice/web-diary/ui/input/src/base/base.styles.ts
> +  padding: '0 6px',
@gochicus нет, это не так делается, продолжай искать

2021-06-02 15:17 UTC, gochicus commented on practice/web-diary/ui/input/src/base/base.styles.ts
> +  padding: '0 6px',
@TFK70 за два часа так и не нашел решения, встретились варианты: обернуть input и стилизовать через родителя, классы, и уже описанная стилизация через input

2021-06-02 15:24 UTC, TFK70 commented on practice/web-diary/ui/input/src/base/base.styles.ts
> +  padding: '0 6px',
@gochicus https://www.web4college.com/questions/css-selectors-cheat-sheet.php#structural

2021-06-02 15:26 UTC, gochicus commented on practice/web-diary/ui/input/src/base/base.styles.ts
> +  padding: '0 6px',
@TFK70 пробовал так, не работает почему-то.

2021-06-02 15:27 UTC, TFK70 commented on practice/web-diary/ui/input/src/base/base.styles.ts
> +  padding: '0 6px',
@gochicus ну и как ты пробовал-то?

2021-06-02 15:28 UTC, gochicus commented on practice/web-diary/ui/input/src/base/base.styles.ts
> +  padding: '0 6px',
@TFK70 ```
`import { styleFn } from 'styled-system'

export const createBaseStyles = (): styleFn => () => ({
  outline: 'none',
  margin: 0,
  border: '1px solid',
  width: '100%',

  '&::placeholder': {
    fontFamily: 'Gordita, sans-serif',
    fontSize: '14px',
    padding: '6px 6px',
  },
  '&:first-child':{
    padding:'10px'
  }
})
`
```

2021-06-02 15:32 UTC, TFK70 commented on practice/web-diary/ui/input/src/base/base.styles.ts
> +  padding: '0 6px',
@gochicus 
1. Отформатируй коммент по-нормальному
2. Это и не должно работать. Я тебе кинул страницу с дюжиной псевдоклассов, ты из них методом тыка взял только один и сейчас утверждаешь что это не работает?

Для ясности, это было сделано только что с помощью тех материалов котоырые я тебе скинул:

![image](https://user-images.githubusercontent.com/62806448/120509121-af3cfe00-c3e1-11eb-9b5e-c588b00f545f.png)

2021-06-02 15:39 UTC, gochicus commented on practice/web-diary/ui/input/src/base/base.styles.ts
> +  padding: '0 6px',
@TFK70  `first-of-type` сработал, абсолютно не понимаю почему он работает, а` first-child ` нет.

2021-06-02 15:42 UTC, TFK70 commented on practice/web-diary/ui/input/src/base/base.styles.ts
> +  padding: '0 6px',
@gochicus 
> :first-child selects first child of the parent element.

> :first-of-type selects the first child of a specific type of element. In this case, parent has more than one types of elements.

Попробуй поиграть с ними, сделать так:

```javascript
'&:first-child: {
   backgroundColor: 'red'
}'
```

2021-06-02 15:49 UTC, gochicus commented on practice/web-diary/ui/input/src/base/base.styles.ts
> +  padding: '0 6px',
@TFK70 Очень странно, попробовал и оно применилось ко второму инпуту, а к первому нет.

2021-06-02 15:51 UTC, TFK70 commented on practice/web-diary/ui/input/src/base/base.styles.ts
> +  padding: '0 6px',
@gochicus ага
потому что в первом инпуте первый ребенок другой, поэтому ты и используешь более конкретный селектор по первому ребенку со специфик типом (`span`,`h`,`p`,`a` и прочие)

2021-06-02 16:18 UTC, TFK70 requested changes

2021-06-02 16:18 UTC, TFK70 commented on practice/web-diary/ui/list/src/Item.tsx
>        <Box backgroundColor='lightGrey' width='100%'>
@gochicus Саша это вообще не вариант
![image](https://user-images.githubusercontent.com/62806448/120515545-d7c7f680-c3e7-11eb-89df-3096d810e2cc.png)

2021-06-02 16:18 UTC, TFK70 commented on practice/web-diary/ui/list/src/Item.tsx
> +            <Layout flexBasis='200px' />{' '}
?

2021-06-02 18:47 UTC, TFK70 requested changes

2021-06-02 18:47 UTC, TFK70 commented on practice/web-diary/fragments/diary/src/Diary.tsx
> +        <Box backgroundColor='white' maxWidth='450px'>
1. Вместе с контентом тудушки листаются кнопки
 2. Итем слишком узкий для комфортного просмотра большого текста
 3. Ну и да, содержимое итема зачем-то зумится при наведении
 
Дай ему максимальную высоту в 1.5 от изначального размера, если контент переполняет и это - добавляй скролл

https://user-images.githubusercontent.com/62806448/120535511-824a1480-c3fc-11eb-9d77-21c8386bed70.mp4

2021-06-03 09:58 UTC, TFK70 requested changes
Не все условия соблюдены:

1. Ширина основного блока точно больше 20%
2. При наведении на итем его содержимое по-прежнему зумится (вроде как), короче что-то у тебя есть на онховере и текст из-за этого очень жестко плывет

В остальном по части отрисовки более-менее норм

2021-06-03 10:13 UTC, TFK70 requested changes

2021-06-03 10:13 UTC, TFK70 commented on practice/web-diary/fragments/post-list/src/PostList.tsx
> +      updateState={setPostData}
А смысл функцию переименовывать? Это лишний раз с толку сбивает, если ты передаешь setPostData то и передавай его под названием setPostData, так сразу понятно что именно вызывается

2021-06-03 10:13 UTC, TFK70 commented on practice/web-diary/ui/button/src/Button.style.ts
> +export const overflowInheritStyles = createShapeStyles({ value: 'inherit' })
Что за value? Из того что тут написано ничего не говорит о том что value - это значение overflowY

2021-06-03 10:13 UTC, TFK70 commented on practice/web-diary/ui/button/src/Button.style.ts
> +export const overflowStyles = switchProp(prop('scroll', 'inherit'), () => ({
И у тебя опять повторяется история с дисплеем где ты зачем-то напридумывал show и hide
Зачем? Если я знаю css и хочу задать значение overflowY - то мне будет удобнее сделать это по всем правилам css, а не вникать лишний раз в твою экосистему, это ж жесть, почти как для каждого значения position создавать функции по типу createPositionAbsoluteStyles на проп posabs который я сам же и придумал. Куча времени уйдет на то чтобы в это вникнуть, это неудобно, ты сам на это тратишь больше времени, а самое главное - это не необходимо

2021-06-03 10:13 UTC, TFK70 commented on practice/web-diary/ui/button/src/Button.style.ts
> +export const justifyContentStyles = switchProp(prop('position', 'center'), () => ({
А стоп...
Ну ты понял суть

2021-06-03 10:13 UTC, TFK70 commented on practice/web-diary/ui/button/src/shape/shape.styles.ts
> +  minHeight: minSize,
minHeight чек
maxHeight чек
height ???

Не понимаю что ты к этим минам и максам привязался, убери их вообще ото всюду, а то в подобных местах уже до абсурда доходит, в них же нету никакой необходимости

2021-06-03 10:13 UTC, TFK70 commented on practice/web-diary/ui/button/src/shape/shape.styles.ts
> +  minHeight: minSize,
И да, здесь ты опять зачем-то переименовал height в size заставляя лишний раз вникать в твою экосистему
Зачем?

2021-06-03 10:13 UTC, TFK70 commented on practice/web-diary/ui/input/src/base/base.styles.ts
> +
Опять какой-то пробел
Линтер конечно хорош, но это не значит что тебе нарочно везде нужно оставлять код без малейшего форматирования

2021-06-03 10:22 UTC, gochicus commented on practice/web-diary/fragments/post-list/src/PostList.tsx
> +      updateState={setPostData}
@TFK70 так тут же вроде идет вынос бизнес логики из List и Item соответственно

2021-06-03 10:24 UTC, TFK70 commented on practice/web-diary/fragments/post-list/src/PostList.tsx
> +      updateState={setPostData}
@gochicus так я и не просил тут логику менять
Я просто спрашиваю зачем функцию setPostData передавать под именем updateState лишний раз сбивая с толку?

2021-06-03 10:30 UTC, gochicus commented on practice/web-diary/fragments/post-list/src/PostList.tsx
> +      updateState={setPostData}
@TFK70 Как по мне, разные названия в данном случае больше путают в смысле понимания того как происходит управление состоянием, но да ладно, переименуем

2021-06-03 10:34 UTC, TFK70 commented on practice/web-diary/fragments/post-list/src/PostList.tsx
> +      updateState={setPostData}
@gochicus разные название действительно больше путают, я ж так и написал

2021-06-03 10:36 UTC, gochicus commented on practice/web-diary/fragments/post-list/src/PostList.tsx
> +      updateState={setPostData}
@TFK70 Ошибся, не то написал

2021-06-03 10:37 UTC, TFK70 commented on practice/web-diary/fragments/post-list/src/PostList.tsx
> +      updateState={setPostData}
@gochicus да ты б лучше пояснил что ты имел ввиду, я и так ничего не понял

2021-06-03 13:18 UTC, TFK70 requested changes

2021-06-03 13:18 UTC, TFK70 commented on practice/web-diary/ui/button/src/Button.style.ts
> +export const overflowStyles = switchProp(prop('overflowY', 'inherit'), () => ({
Теперь от этого тем более смысла нет
Просто дай возможность напрямую задавать overflowY

2021-06-03 13:18 UTC, TFK70 commented on practice/web-diary/ui/button/src/Button.tsx.rej
> +diff a/practice/web-diary/ui/button/src/Button.tsx b/practice/web-diary/ui/button/src/Button.tsx	(rejected hunks)
Это что?

2021-06-03 13:18 UTC, TFK70 commented on practice/web-diary/ui/list/src/Item.tsx
>              <Text>{postObject.post}</Text>
Контент итема обрезается сверху:
![image](https://user-images.githubusercontent.com/62806448/120651214-f685c600-c497-11eb-9aa1-6ad02bab9b50.png)

Если что первые слова текста: Lorem ipsum dolor sit amet...
А тут от них след простыл

2021-06-03 13:34 UTC, gochicus commented on practice/web-diary/ui/button/src/Button.tsx.rej
> +diff a/practice/web-diary/ui/button/src/Button.tsx b/practice/web-diary/ui/button/src/Button.tsx	(rejected hunks)
@TFK70 Блин, видимо как-то связано с конфликтом в ветках, я уже дважды его резолвил.

2021-06-03 13:37 UTC, TFK70 commented on practice/web-diary/ui/button/src/Button.tsx.rej
> +diff a/practice/web-diary/ui/button/src/Button.tsx b/practice/web-diary/ui/button/src/Button.tsx	(rejected hunks)
@gochicus эти файлы скорее всего IDE создает
И да, судя по содержимому это действительно связано с тем как ты резолвил конфликты
Погугли

2021-06-03 13:46 UTC, gochicus commented on practice/web-diary/ui/list/src/Item.tsx
>              <Text>{postObject.post}</Text>
@TFK70 я могу вернуть минимальную и максимальную высоту, чтобы контейнер несколько расширялся?

2021-06-03 13:56 UTC, TFK70 commented on practice/web-diary/ui/list/src/Item.tsx
>              <Text>{postObject.post}</Text>
@gochicus так тут и нужна максимальная высота, но не в Button

2021-06-03 14:09 UTC, gochicus commented on practice/web-diary/ui/list/src/Item.tsx
>              <Text>{postObject.post}</Text>
@TFK70 у меня все серое поле - `Button`, и оно гвоздями прибито сейчас по высоте. Впрочем, кажется,  проблема обрезания решилась оборачиванием `Text` в `Box`.
```
<Button borderColor='transparent' justifyContent='start' overflowY='auto' color='grey'>
           <Box columnWidth='100px'> <Text>{postObject.post}</Text></Box>
          </Button>
```

2021-06-03 14:17 UTC, TFK70 commented on practice/web-diary/ui/list/src/Item.tsx
>              <Text>{postObject.post}</Text>
@gochicus одно дело писать костыль для сторонней либы, но вот писать костыль для своего же кода - это точно что-то не то

2021-06-03 15:01 UTC, TFK70 requested changes

2021-06-03 15:01 UTC, TFK70 commented on practice/web-diary/ui/list/src/Item.tsx
>              <Text>{postObject.post}</Text>
Что-то изменилось? Текст по-прежнему режется
И у тебя опять конфликт

2021-06-03 15:09 UTC, gochicus commented on practice/web-diary/ui/list/src/Item.tsx
>              <Text>{postObject.post}</Text>
@TFK70 значит ошибся, когда тестировал. У меня кроме резиновой высоты min-max нет решения. Завтра над этим подумаю.  А насчет конфликта, он почему-то возобновляется с каждым новым коммитом, так что резолвить буду его в последний момент.  Вчера резолвил, все проверки проходили, новые коммиты и снова конфликт.

2021-06-04 08:49 UTC, TFK70 requested changes

2021-06-04 08:49 UTC, TFK70 commented on practice/web-diary/ui/layout/src/Box.tsx
> +  system({ overflow: true, hyphens: true, cursor: true }),
Боксу не нужен cursor

2021-06-04 08:49 UTC, TFK70 commented on practice/web-diary/ui/list/src/Item.tsx
> +import { TrashIcon }           from '@ui/icons'
Импорты в один собери
И поищи по проекту еще такие места

2021-06-04 08:49 UTC, TFK70 commented on practice/web-diary/ui/list/src/Item.tsx
> +        width='100%'
Row?

2021-06-04 08:49 UTC, TFK70 commented on practice/web-diary/ui/list/src/Item.tsx
> +            <Box overflow='auto' display='block'>
Тогда при перегрузке отступ будет только у первой строки
Реши это с помощью флекс базиса

2021-06-04 08:49 UTC, TFK70 commented on practice/web-diary/ui/list/src/Item.tsx
> +        <Box width='100%'>
Roow??

2021-06-04 08:49 UTC, TFK70 commented on practice/web-diary/ui/text/src/Text.tsx
> +  padding: '0 15px',
Все-таки лучше от этого избавиться
padding={0} слишком сильно глаза режет, да и вообще текст по умолчанию без паддингов - наиболее логично

2021-06-04 08:49 UTC, TFK70 commented on practice/web-diary/ui/text/src/Text.tsx
> +  padding: '0 15px',
И пофикси конфликт

2021-06-04 08:53 UTC, gochicus commented on practice/web-diary/ui/text/src/Text.tsx
> +  padding: '0 15px',
@TFK70 Я у себя локально с мастером смержился, конфликт не пофиксился.

2021-06-04 08:54 UTC, TFK70 commented on practice/web-diary/ui/text/src/Text.tsx
> +  padding: '0 15px',
@gochicus https://githowto.com/ru/resolving_conflicts

2021-06-04 09:18 UTC, gochicus commented on practice/web-diary/ui/text/src/Text.tsx
> +  padding: '0 15px',
@TFK70 Спасибо конечно, но я уже делал мердж из ветки feature/new-design в  master, На данный момент он `up to date`, конфликтов не показывает.

2021-06-04 09:20 UTC, TFK70 commented on practice/web-diary/ui/text/src/Text.tsx
> +  padding: '0 15px',
@gochicus ии? 
Тут-то конфликт есть

2021-06-04 09:23 UTC, gochicus commented on practice/web-diary/ui/text/src/Text.tsx
> +  padding: '0 15px',
@TFK70 Есть, и тут он резолвится через браузер.  Может мне мастер нужно обновить, хотя вроде и делал пулл. Закончу проверять  импорты, сделаю коммит и попробую.

2021-06-04 09:23 UTC, TFK70 commented on practice/web-diary/ui/text/src/Text.tsx
> +  padding: '0 15px',
@gochicus ты шутишь?
Почитай ссылку которую я тебе отправил

2021-06-04 10:26 UTC, TFK70 requested changes

2021-06-04 10:26 UTC, TFK70 commented on practice/web-diary/ui/button/src/Button.style.ts
> +export const justifyContentStyles = switchProp(prop('justifyContent', 'center'), () => ({
Ну что это?
Ты не вообще не понял что я тебе несколько комментов назад по этому поводу говорил?

2021-06-04 10:26 UTC, TFK70 commented on practice/web-diary/ui/button/src/appearance/appearance.style.ts
> +  display,
display это ни appearance, ни шейпы
Зачем тут дисплей вообще? Чтобы опять костылить и писать block вместо flex? Или тебе недостаточно кондишна и тебе нужен none?

2021-06-04 10:26 UTC, TFK70 commented on practice/web-diary/ui/button/src/appearance/appearance.style.ts
> +  justifyContent,
Зачем?

2021-06-04 10:26 UTC, TFK70 commented on practice/web-diary/ui/button/src/shape/shape.styles.ts
> +  overflowY: overflowValue,
Зачем?

2021-06-04 10:26 UTC, TFK70 commented on practice/web-diary/ui/list/src/Item.tsx
> +      <Row
Зачем?

2021-06-04 10:26 UTC, TFK70 commented on practice/web-diary/ui/list/src/List.tsx
> +          data={items}
А тут-то что? Что за data?

2021-06-04 10:26 UTC, TFK70 commented on practice/web-diary/ui/text/src/Text.tsx
> +  fontSize: '16px',
Тебе в теме fontSizes зачем?

2021-06-04 10:32 UTC, gochicus commented on practice/web-diary/ui/button/src/Button.style.ts
> +export const justifyContentStyles = switchProp(prop('justifyContent', 'center'), () => ({
@TFK70  Нет не понял, мы то всё атомизируем,то зачем.

2021-06-04 10:38 UTC, gochicus commented on practice/web-diary/ui/button/src/appearance/appearance.style.ts
> +  display,
@TFK70 в таком случае, я не знаю что такое дисплей, казалось логичным, так как отвечает за представление.

2021-06-04 10:39 UTC, TFK70 commented on practice/web-diary/ui/button/src/appearance/appearance.style.ts
> +  display,
@gochicus так ты мне можешь сказать зачем он тут? Или ты его опять просто так доабвил?

2021-06-04 10:40 UTC, TFK70 commented on practice/web-diary/ui/button/src/Button.style.ts
> +export const justifyContentStyles = switchProp(prop('justifyContent', 'center'), () => ({
@gochicus и не понимаю что ты подразумеваешь под "все атомизируем"
У тебя куча кода просто существует без какой-то цели, ты его написал просто так и сам не понимаешь для чего

2021-06-04 10:41 UTC, gochicus commented on practice/web-diary/ui/button/src/appearance/appearance.style.ts
> +  display,
@TFK70 он тут остался с предыдущей реализации, когда я использовал дисплей именно таким образом.

2021-06-04 10:43 UTC, gochicus commented on practice/web-diary/ui/button/src/Button.style.ts
> +export const justifyContentStyles = switchProp(prop('justifyContent', 'center'), () => ({
@TFK70 в прошлой реализации это использовалось, я понимаю зачем я это писал. Ты сказал больще не используем, я перестал это использовать.

2021-06-04 10:44 UTC, TFK70 commented on practice/web-diary/ui/button/src/appearance/appearance.style.ts
> +  display,
@gochicus предлагаешь его тут так и оставить?
Просто когда ты делаешь коммит и запрашиваешь ревью это значит что твой код готов и его можно мержить в мастер

2021-06-04 11:16 UTC, TFK70 requested changes

2021-06-04 11:16 UTC, TFK70 commented on practice/web-diary/ui/list/src/Item.tsx
> +      <Box
То что я спрашиваю "зачем?" еще не значит что надо все удалять, я помню что я сказал тут использовать Row, но тут проблема в другом, ты снова видимо не понял зачем

2021-06-04 11:29 UTC, gochicus commented on practice/web-diary/ui/list/src/Item.tsx
> +      <Box
@TFK70 Если использовать `Row`, то ширину можно будет убрать, в остальном зачем использовать именно направляющую не понимаю, ведь тут у нас контейнеры спозиционированные `Column` в `List`

2021-06-04 11:30 UTC, TFK70 commented on practice/web-diary/ui/list/src/Item.tsx
> +      <Box
@gochicus насчет первого - да
Насчет второго - это к тебе вопрос, здесь меня стриггерило только `<Box width='100%'>`

2021-06-04 14:29 UTC, TFK70 requested changes

2021-06-04 14:29 UTC, TFK70 commented on practice/web-diary/ui/button/src/base/base.style.ts
> +  padding: '5px',
Почему у есть паддинг и он находится в baseStyles?
Кнопка на тысячу частей чтоль без этого паддинга разлетится? Паддинга у блочного элемента быть не должно

2021-06-04 14:35 UTC, gochicus commented on practice/web-diary/ui/button/src/base/base.style.ts
> +  padding: '5px',
@TFK70  Могу коммитить убранный паддинг или ты ещё ревьюишь?

2021-06-04 14:37 UTC, TFK70 commented on practice/web-diary/ui/button/src/base/base.style.ts
> +  padding: '5px',
@gochicus коммить

2021-06-04 14:42 UTC, TFK70 requested changes

2021-06-04 14:42 UTC, TFK70 commented on practice/web-diary/fragments/form-post-add/src/FormPostAdd.tsx
> +          <Text color='white' fontWeight='bold' padding={0} fontSize='large'>
А чего ты паддинги то эти нулевые не убрал?

2021-06-04 14:43 UTC, gochicus commented on practice/web-diary/fragments/form-post-add/src/FormPostAdd.tsx
> +          <Text color='white' fontWeight='bold' padding={0} fontSize='large'>
@TFK70  Убирал, видимо, что-то пропустил.

2021-06-04 14:50 UTC, TFK70 approved these changes, later dismissed

2021-06-04 18:12 UTC, TorinAsakura commented on .gitignore
> +.rej
это что?

2021-06-04 18:32 UTC, TorinAsakura requested changes
дальше смотреть не вижу смысла, чистите, фиксите

2021-06-04 18:32 UTC, TorinAsakura commented on practice/web-diary/fragments/header/src/Header.tsx
> +      <Text paddingLeft='15px' fontSize='large' fontWeight='bold' fontFamily='primary'>
Полагаю, вместо paddingLeft тут должен быть layout basis 15px

2021-06-04 18:32 UTC, TorinAsakura commented on practice/web-diary/fragments/form-post-add/src/FormPostAdd.tsx
> +    <Box justifyContent='flex-start' width='98%'>
width 98%?  А почему не 99? 100?

2021-06-04 18:32 UTC, TorinAsakura commented on practice/web-diary/fragments/diary/src/Diary.tsx
> +    <Background gradient='blueAndGreenGradient' height='100vh' width='100vw' overflowY='auto'>
overflowY наверно можно в дефолты унести, да?

2021-06-04 18:32 UTC, TorinAsakura commented on practice/web-diary/fragments/post-сontrols/src/PostControls.tsx
> +    <Column width='92%'>
что вообще за жесть с относительными величинами?

2021-06-04 18:32 UTC, TorinAsakura commented on practice/web-diary/fragments/post-сontrols/src/PostControls.tsx
> +        <Box width='60%'>
у тебя должны быть чёткие размеры иначе при разработке мобильной версии ты на каждый чих будешь думать об этих несчастных процентах

2021-06-04 18:32 UTC, TorinAsakura commented on practice/web-diary/fragments/post-сontrols/src/PostControls.tsx
> +        <Box width='35%'>
ну и далее по всему проекту…

2021-06-04 18:32 UTC, TorinAsakura commented on practice/web-diary/ui/button/src/base/base.style.ts
> +  border: '1px solid',
я бы ещё добавил transparent

2021-06-04 18:32 UTC, TorinAsakura commented on practice/web-diary/ui/button/src/base/base.style.ts
> +  width: '100%',
зачем ширина на всё пространство?

2021-06-04 18:32 UTC, TorinAsakura commented on practice/web-diary/ui/button/src/base/base.style.ts
> +})
где outline, wordBreak, padding?

2021-06-04 18:32 UTC, TorinAsakura commented on practice/web-diary/ui/input/src/Input.styles.ts
> +export const createSmallWidthStyles = createBaseShape({ size: 40 })
почему в кнопке ты используешь явные величины, а тут нет?

2021-06-04 18:32 UTC, TorinAsakura commented on practice/web-diary/ui/input/src/Input.styles.ts
> +import { prop, switchProp }       from 'styled-tools'
почему тут файл называется styles а там в button style?

2021-06-04 18:32 UTC, TorinAsakura commented on practice/web-diary/ui/input/src/base/base.styles.ts
> +  border: '1px solid',
я бы добавил transparent…

2021-06-04 18:32 UTC, TorinAsakura commented on practice/web-diary/ui/input/src/base/base.styles.ts
> +  margin: 0,
зачем?

2021-06-04 18:32 UTC, TorinAsakura commented on practice/web-diary/ui/input/src/base/base.styles.ts
> +  },
что-то не похоже на base

2021-06-04 18:32 UTC, TorinAsakura commented on practice/web-diary/ui/input/src/base/base.styles.ts
> +export const createBaseStyles = (): styleFn => () => ({
выходит у тебя input имеет display block?

2021-06-04 18:32 UTC, TorinAsakura commented on practice/web-diary/ui/layout/src/Row.tsx
>  Row.defaultProps = {
где boxSizing?

2021-06-04 18:48 UTC, gochicus commented on practice/web-diary/fragments/post-сontrols/src/PostControls.tsx
> +        <Box width='60%'>
@TorinAsakura под четкими подразумеваются пиксели?

2021-06-04 18:48 UTC, TorinAsakura commented on practice/web-diary/fragments/post-сontrols/src/PostControls.tsx
> +        <Box width='60%'>
> @TorinAsakura под четкими подразумеваются пиксели?

чёткие - осязаемые - явные - понятные - заданные макетом

2021-06-04 18:54 UTC, gochicus commented on practice/web-diary/fragments/post-сontrols/src/PostControls.tsx
> +        <Box width='60%'>
@TorinAsakura а если приминительно к этому реквесту что подразумевается?

2021-06-04 18:54 UTC, TorinAsakura commented on practice/web-diary/fragments/post-сontrols/src/PostControls.tsx
> +        <Box width='60%'>
У тебя ширина блока какой должна быть?

2021-06-04 18:58 UTC, gochicus commented on practice/web-diary/fragments/post-сontrols/src/PostControls.tsx
> +        <Box width='60%'>
@TorinAsakura по макету видна только одна кнопка, размеры сам подбирал, чтобы нормально смотрелось.

2021-06-07 11:04 UTC, TFK70 requested changes

2021-06-07 11:04 UTC, TFK70 commented on practice/web-diary/ui/button/src/base/base.styles.ts
> +  padding: '5px',
Зачем ему здесь паддинг?

2021-06-07 11:04 UTC, TFK70 commented on practice/web-diary/ui/button/src/base/base.styles.ts
> +  wordBreak: 'auto',
И зачем здесь стили для текста если они должны конфигурироваться через Text?

2021-06-07 11:04 UTC, TFK70 commented on practice/web-diary/ui/button/src/Button.style.ts
> +export const widthStyles = switchProp(prop('width', 'normal'), () => ({
Зачем давать конкретные значения для размеров блока?
Это можно делать с текстом чтобы везде были +- одни размеры которые не нужно запоминать. Зачем это блокам? Если среди твоих значений не будет нужного, чтобы втиснуть кнопку в форму регистрации - придется создавать новое, и так до бесконечности пока твой файл не отожрется до размера в 1MB. Это бред, особенно учитывая что в контексте разных блоков те же 30px могут быть как маленькими, так и гигантскими

2021-06-07 11:04 UTC, TFK70 commented on practice/web-diary/fragments/form-post-add/src/FormPostAdd.tsx
> +    <Box justifyContent='flex-start' width='400px'>
Почему у тебя здесь размер в пикселях? Тут должен быть Row с width 100%, не будешь же ты для всех подобных блоков выискивать значения в пикселях

2021-06-07 11:04 UTC, TFK70 commented on practice/web-diary/fragments/form-post-add/src/FormPostAdd.tsx
> +    <Box justifyContent='flex-start' width='400px'>
Зачем нам флексы тогда....

![image](https://user-images.githubusercontent.com/62806448/121005943-c4cb7280-c7a9-11eb-8020-9cd0dd430d1e.png)

2021-06-07 11:04 UTC, TFK70 commented on practice/web-diary/fragments/post-сontrols/src/PostControls.tsx
> +      <Row justifyContent='space-between' width='356px'>
А это вообще что? Почему у Row задана ширина в пикселях?

2021-06-07 11:12 UTC, gochicus commented on practice/web-diary/fragments/post-сontrols/src/PostControls.tsx
> +      <Row justifyContent='space-between' width='356px'>
@TFK70 это к вопросу о резиновой верстке,  к тому,что блокам можно где-то задавать ширину.

2021-06-07 11:12 UTC, gochicus commented on practice/web-diary/ui/button/src/Button.style.ts
> +export const widthStyles = switchProp(prop('width', 'normal'), () => ({
[Я может и неправильно, это реализую, но как-то размер задать надо было](https://github.com/atls-academy/gochicus.github.io/pull/80#discussion_r645770576)

2021-06-07 11:12 UTC, gochicus commented on practice/web-diary/ui/button/src/base/base.styles.ts
> +  wordBreak: 'auto',
@TFK70 [вот](https://github.com/atls-academy/gochicus.github.io/pull/80#discussion_r645770758)

2021-06-07 11:12 UTC, gochicus commented on practice/web-diary/ui/button/src/base/base.styles.ts
> +  padding: '5px',
@TFK70 [вот](https://github.com/atls-academy/gochicus.github.io/pull/80#discussion_r645770758)

2021-06-07 11:15 UTC, TFK70 commented on practice/web-diary/ui/button/src/Button.style.ts
> +export const widthStyles = switchProp(prop('width', 'normal'), () => ({
@gochicus а сам ты что насчет этой реализации думаешь?

2021-06-07 11:15 UTC, TFK70 commented on practice/web-diary/fragments/post-сontrols/src/PostControls.tsx
> +      <Row justifyContent='space-between' width='356px'>
@gochicus какому вопросу?

2021-06-07 11:22 UTC, gochicus commented on practice/web-diary/ui/button/src/Button.style.ts
> +export const widthStyles = switchProp(prop('width', 'normal'), () => ({
@TFK70 кнопка конфигурирумая, писать тысячи вариантов мне точно не понадобится,  даже десятки сильно вряд ли. Вероятно, не такая уж и большая работа, в зависимости от макета. Вариант с заданием ширины удобнее, но тут, я так понял, вопрос в том,чтобы не отдавать контроль за отображением браузеру.

2021-06-07 11:24 UTC, gochicus commented on practice/web-diary/fragments/post-сontrols/src/PostControls.tsx
> +      <Row justifyContent='space-between' width='356px'>
@TFK70 ну мы обсуждали, что некоторые размеры, можно задавать и жетско, что я могу использовать пиксели, чтобы верстка не ехала при сужении экрана и т.д

2021-06-07 11:26 UTC, TFK70 commented on practice/web-diary/fragments/post-сontrols/src/PostControls.tsx
> +      <Row justifyContent='space-between' width='356px'>
@gochicus и нам Row тогда зачем? А Column зачем? А флексы вообще тогда зачем? 
Почему же мы тогда размеры для всех блоков в пикселях не задаем?

2021-06-07 15:35 UTC, TFK70 requested changes

2021-06-07 15:35 UTC, TFK70 commented on practice/web-diary/fragments/post-сontrols/src/PostControls.tsx
> +          <Text fontSize='small'>{intl.formatMessage(messages.messageCount)}</Text>
Ни за что бы не догадался что messageCount это Posts
Переименуй месседж

2021-06-07 15:35 UTC, TFK70 commented on practice/web-diary/ui/button/src/Button.style.ts
> +export const normaHeightStyles = createShapeStyles({ height: '40px' })
Опечатка

2021-06-07 15:35 UTC, TFK70 commented on practice/web-diary/ui/input/src/Input.styles.ts
> +export const widthStyles = switchProp(prop('size', 'small'), () => ({
походу ты width и height перепутал

2021-06-07 15:35 UTC, TFK70 commented on practice/web-diary/ui/input/src/Input.styles.ts
> +export const widthStyles = switchProp(prop('size', 'small'), () => ({
Но раз уж на то пошло:
width в случае с кнопками, инпутами и подобным - это content-based значение, оно динамически изменяется в зависимости от количества контента, так что заливать значения ширины бетоном для таких компонентов не стоит. Другая ситуация с высотой, контент на нее никак не влияет, так что это значение можно спокойно держать в пресетах

2021-06-07 15:35 UTC, TFK70 commented on practice/web-diary/ui/theme/src/theme/fonts.ts
> +  primary: 'Gordita, sans-serif',
От этого можно избавиться, теперь fontFamily задан глобально и он один для всего приложения

2021-06-07 16:01 UTC, TFK70 requested changes
Что-то тут не так

![image](https://user-images.githubusercontent.com/62806448/121052102-7a5eeb80-c7d3-11eb-965e-cf994dce67df.png)

2021-06-07 16:26 UTC, TFK70 requested changes

2021-06-07 16:26 UTC, TFK70 commented on .gitignore
> +
Подчисти это еще и ок

2021-06-07 16:28 UTC, gochicus commented on .gitignore
> +
@TFK70  ты про лишнюю строку сейчас?

2021-06-07 16:29 UTC, TFK70 requested changes

2021-06-07 16:29 UTC, TFK70 commented on practice/web-diary/fragments/post-сontrols/src/PostControls.tsx
> +            {' '}
Что за пробел?

2021-06-07 16:29 UTC, TFK70 commented on practice/web-diary/ui/list/src/Item.tsx
> +                <StarIcon color={postObject.important === true ? '#8f49e7' : 'white'} />{' '}
И тут

2021-06-07 16:29 UTC, TFK70 commented on .gitignore
> +
@gochicus да, у тебя же в гитигноре кроме этого ничего не изменилось

2021-06-07 16:29 UTC, TFK70 commented on .gitignore
> +
@gochicus суть в том чтобы он был идентичен с мастером

2021-06-07 16:30 UTC, gochicus commented on practice/web-diary/fragments/post-сontrols/src/PostControls.tsx
> +            {' '}
@TFK70 Хз, то ли от линтера подарок, то ли от шторма

2021-06-07 16:32 UTC, TFK70 commented on practice/web-diary/fragments/post-сontrols/src/PostControls.tsx
> +            {' '}
@gochicus 0_о
Они-то тут при чем?

2021-06-07 16:34 UTC, gochicus commented on practice/web-diary/fragments/post-сontrols/src/PostControls.tsx
> +            {' '}
@TFK70 Так не я же эти скобки расставляю.

2021-06-07 16:36 UTC, TFK70 requested changes

2021-06-07 16:36 UTC, TFK70 commented on .gitignore
> +credentials.json
Еще раз: ты в гитигнор никакие изменения не вносил, сделай его абсолютно идентичным с мастером чтобы он не трекался гитом как файл с диффами

2021-06-07 16:39 UTC, gochicus commented on .gitignore
> +credentials.json
@TFK70 
Так вроде соответствует, количество строк и содержание одинаковое.

2021-06-07 16:41 UTC, TFK70 commented on .gitignore
> +credentials.json
@gochicus если бы соответствовал его бы не было в changed files самым первым файлом
сам проверь, на гитхабе

мой совет тебе воспользоваться средствами шторма и откатить историю файла до мастеровской

2021-06-07 16:45 UTC, TFK70 commented on .gitignore
> +credentials.json
@gochicus  пкм -> git -> compare with branch -> master

2021-06-07 19:03 UTC, TFK70 requested changes

2021-06-07 19:03 UTC, TFK70 commented on practice/web-diary/ui/input/src/Input.styles.ts
> +export const widthStyles = switchProp(prop('size', 'small'), () => ({
?

2021-06-07 19:03 UTC, TFK70 commented on practice/web-diary/ui/button/src/Button.style.ts
> +
Почему файл не переименовал?

2021-06-07 19:03 UTC, TFK70 commented on practice/web-diary/ui/button/src/Button.interface.ts
> +  width?: string
Ширина может быть не только строкой
Как минимум еще и числом

2021-06-07 19:03 UTC, TFK70 commented on practice/web-diary/ui/theme/src/theme/fontSizes.ts
> +  large: '33px',
Зачем хранить число в виде строки если это число?

2021-06-07 19:03 UTC, TFK70 commented on practice/web-diary/ui/theme/src/theme/fontWeights.ts
> +  normal: '400',
Тем более тут

2021-06-07 19:03 UTC, TFK70 commented on practice/web-diary/ui/button/src/Button.style.ts
> +    borderColor: 'transparent',
Он вроде бы уже

2021-06-07 19:03 UTC, TFK70 commented on practice/web-diary/fragments/form-post-add/src/FormPostAdd.tsx
> +        width='50px'
Это было допустимо где ты задавал ширину в пикселях для кнопок в PostControls. В них у тебя находился один элемент которого в теории могло быть недостаточно чтобы растянуть кнопку до желаемого размера, но тут width зачем?
Повоторюсь, что это content-based значение, которое ты в данный момент захардкодил. Получается, добавив сюда пару лишних буков придется заново подбиать ширину в пикселях? Ну такое..
Добейся того же через паддинги у текста

2021-06-08 02:50 UTC, gochicus commented on practice/web-diary/fragments/form-post-add/src/FormPostAdd.tsx
> +        width='50px'
@TFK70 Ты же понимаешь, что паддинги это тоже такое себе. Если мы вдруг добавим пару букв, придется точно также подбирать пиксели, но уже для паддингов, чтобы оно выглядело нормально. Я сделаю, но, как по мне, с паддингами даже хуже, ширину поменять просто, а вот если забыть про паддинги, то потом придется удивляться странному поведению кнопки.

2021-06-08 03:00 UTC, gochicus commented on practice/web-diary/ui/theme/src/theme/fontSizes.ts
> +  large: '33px',
@TFK70 собственно, а есть разница? Допустимые типы прописаны.

2021-06-08 03:14 UTC, gochicus commented on practice/web-diary/ui/button/src/Button.style.ts
> +
@TFK70 Возможно, в гит не добавилось, какая-то странная фигня.

2021-06-08 07:15 UTC, TFK70 commented on practice/web-diary/ui/theme/src/theme/fontSizes.ts
> +  large: '33px',
@gochicus нет ну если тебе так больше нравится то пожалуйста, но это вообще-то небольшой оверхед оборачивать число в строку и подписывать px

2021-06-08 07:17 UTC, gochicus commented on practice/web-diary/ui/theme/src/theme/fontSizes.ts
> +  large: '33px',
@TFK70 Мне действительно так больше нравится, поскольку в строке я чётко указываю единицу измерения - пиксели, но изменения я уже внес, так что чего уж тепеь.

2021-06-08 07:20 UTC, TFK70 commented on practice/web-diary/fragments/form-post-add/src/FormPostAdd.tsx
> +        width='50px'
@gochicus вот тут уже ооочень странно что ты не видишь проблемы
В том то и дело что когда ты смотришь на верстку и видишь кнопки с отступами - то ты ожидаешь увидеть их с паддингами (теми или иными), но если у тебя везде будут заданы значения в пикселях - это сразу породит кучу вопросов "как производился расчет?", "везде ли они выставлялись по одному принципу?"
Более того, опять же повторюсь, ширина зависит от контента. Напрямую. У тебя ширина зависит от ничего, просто абсолютная величина. Вот тут и могут быть непредсказуемые последствия, когда на мобилке например фонт сайз чуть уменьшился, наполнение кнопки соответственно тоже, но вместо сужения она просто продолжает сохранять свои размеры (которые как бы гигантские для нового шрифта)
Это бред, такие вещи за тебя должен считать комп, а не ты сам

2021-06-08 07:26 UTC, gochicus commented on practice/web-diary/fragments/form-post-add/src/FormPostAdd.tsx
> +        width='50px'
@TFK70 так, если я правильно уловил общую концепцию,  нужно, по возможности, стремиться уменьшать контроль браузера над приложением, в этом отношении,я не уверен, что паддинг лучше. А то, что конкретно хардкодить ширину как то не очень, соглашусь, но мы ж именно насчет использования этого метода и договорились, когда ты ревьюил мою реализацию со `switchProps.`

2021-06-08 07:33 UTC, TFK70 commented on practice/web-diary/fragments/form-post-add/src/FormPostAdd.tsx
> +        width='50px'
@gochicus я сказал про switchProps что это еще больший бред в котором нет никакого смысла и значения ширины должны задаваться напрямую, но я не говорил что тебе нужно везде их задавать, речь шла о местах где это необходимо

> по возможности, стремиться уменьшать контроль браузера над приложением
Зачем? Конкретно в этом случае ты себе же делаешь хуже
И нам не нужно отбирать у браузера контроль, нам достаточно сказать что ему нужно делать в той или иной ситуации. Такими темпами можешь приступать рисовать свой интерфейс красками на бумаге

2021-06-08 07:36 UTC, TFK70 requested changes

2021-06-08 07:36 UTC, TFK70 commented on practice/web-diary/fragments/post-сontrols/src/PostControls.tsx
> +            width='80px'
Ну и тут аналогично
Вот ты же используешь intl. Представь у тебя приложения доживет до этапа где у тебя будет русская и английская версии сайта. Сообщение  "Очистить все" явно занимает больше места чем Clear All, но твоя кнопка не поддастся потому что у тебя content-based значение захардкожено

2021-06-08 07:44 UTC, gochicus commented on practice/web-diary/fragments/post-сontrols/src/PostControls.tsx
> +            width='80px'
@TFK70 Никита, я попрошу тебя на будущее изъясняться точнее. На прямой вопрос, нужно ли мне ширину задавать прямо в нопках, ты ответил да.

2021-06-08 07:54 UTC, TFK70 commented on practice/web-diary/fragments/post-сontrols/src/PostControls.tsx
> +            width='80px'
@gochicus это было тут? На гх?

2021-06-08 07:59 UTC, gochicus commented on practice/web-diary/fragments/post-сontrols/src/PostControls.tsx
> +            width='80px'
@TFK70 К сожалению, в дс, когда я поднял тему про   реализацию через switchProp.

2021-06-08 08:03 UTC, TFK70 submitted a review, later dismissed

2021-06-08 15:28 UTC, TorinAsakura requested changes
В целом уже почти финал

2021-06-08 15:28 UTC, TorinAsakura commented on practice/web-diary/ui/list/src/Item.tsx
> +        <Row>
ок, а что если !visible?

2021-06-08 15:28 UTC, TorinAsakura commented on practice/web-diary/ui/list/src/List.tsx
> +    <Column width='100%'>
зачем тут width?

2021-06-08 15:28 UTC, TorinAsakura commented on practice/web-diary/ui/theme/src/globals.ts
> +    '*': {
Это что за жесть? Почитайте как нужно назначать шрифты, ты вообще понимаешь, что ты сделал?

2021-06-08 15:47 UTC, gochicus commented on practice/web-diary/ui/list/src/Item.tsx
> +        <Row>
@TorinAsakura  тогда кнопки не отрисовываются, ширина  блока с фоном задаётся тем самым `width=100%` в List

2021-06-08 15:50 UTC, gochicus commented on practice/web-diary/ui/list/src/List.tsx
> +    <Column width='100%'>
@TorinAsakura  тут он нужен, чтобы задать ширину колонне `Item`, где каждый получаетширину родителя List, таким образом сохраняется ширина блока с фоном.

2021-06-08 15:51 UTC, TorinAsakura commented on practice/web-diary/ui/list/src/List.tsx
> +    <Column width='100%'>
не понимаю, почему у тебя управление размерами бэкграунда легло на несчастный column…

2021-06-08 15:52 UTC, TorinAsakura commented on practice/web-diary/ui/list/src/Item.tsx
> +        <Row>
а что на их месте будет?

2021-06-08 15:59 UTC, gochicus commented on practice/web-diary/ui/list/src/Item.tsx
> +        <Row>
@TorinAsakura пустой  `Row`  остается, но  весь блок не разъезжется, потому что управление шириной происходит через `Column` в лист

2021-06-08 16:00 UTC, gochicus commented on practice/web-diary/ui/list/src/List.tsx
> +    <Column width='100%'>
@TorinAsakura так он не разъезжается вне зависимости от наполненности блока, есть ли кнопки внутри или нет.

2021-06-08 16:04 UTC, gochicus commented on practice/web-diary/ui/theme/src/globals.ts
> +    '*': {
@TorinAsakura  задал глобально шрифт всему документу. Вроде ж об этом в субботу говорили? Или тут проблема в том как это сделано?

2021-06-09 12:36 UTC, TFK70 approved these changes

2021-06-09 19:51 UTC, TorinAsakura approved these changes

2021-06-09 19:51 UTC, merged