Feature/mobile
atls-academy/frontend-study-gochicus pull request #86
Opened 2021-06-15 10:15 UTC by gochicus

#74

2021-06-15 12:37 UTC, TFK70 requested changes
Верстка полетела (в том числе и на десктопе, отступы другие)
Вероятно, после добавления height='100%'

![IMG_8F55E9158B0F-1](https://user-images.githubusercontent.com/62806448/122053418-28841a00-ce00-11eb-8675-a5dd6a16248a.jpeg)

2021-06-15 12:37 UTC, TFK70 commented on practice/web-diary/fragments/diary/src/Diary.tsx
> +    <Background gradient='blueAndGreenGradient' height='100vh' width={[1, 1, 1]}>
Ты так и не рассказал что за [1,1,1]

2021-06-15 12:49 UTC, gochicus commented on practice/web-diary/fragments/diary/src/Diary.tsx
> +    <Background gradient='blueAndGreenGradient' height='100vh' width={[1, 1, 1]}>
@TFK70 ну здесь можно просто на 100% заменить. А вот насчет того, что едет, так это всё резиновая верстка. Я точно не могу использовать своё решение с медиазапросом в бэкграунде?

2021-06-15 12:51 UTC, TFK70 commented on practice/web-diary/fragments/diary/src/Diary.tsx
> +    <Background gradient='blueAndGreenGradient' height='100vh' width={[1, 1, 1]}>
@gochicus 
1. [1,1,1] точно меняй на более адекватное значение ширины
2. Нет, это проблема в верстке

2021-06-15 14:57 UTC, TFK70 requested changes

2021-06-15 14:57 UTC, TFK70 commented on practice/web-diary/fragments/diary/src/Diary.tsx
> +          backgroundColor='white'
Даже медиа-запросы кажутся не такой плохой идеей на фоне этой
Пересмотри свой основной лейаут, мне все-таки как-то удалось добиться того же результата без подобных костылей (буквально одной строкой)

2021-06-15 15:39 UTC, TFK70 requested changes

2021-06-15 15:39 UTC, TFK70 commented on practice/web-diary/fragments/diary/src/Diary.tsx
> +        <Column backgroundColor='white' width={['100%', '400px', '400px']} overflowY='auto'>
1. Зачем overflowY?
2. Ты видел десктоп версию?

2021-06-15 15:43 UTC, gochicus commented on practice/web-diary/fragments/diary/src/Diary.tsx
> +        <Column backgroundColor='white' width={['100%', '400px', '400px']} overflowY='auto'>
@TFK70 overflow нужен, потому как при большом количестве постов они начинают выезжать за пределы белого блока.

2021-06-15 15:43 UTC, gochicus commented on practice/web-diary/fragments/diary/src/Diary.tsx
> +        <Column backgroundColor='white' width={['100%', '400px', '400px']} overflowY='auto'>
@TFK70 overflow нужен, потому как при большом количестве постов они начинают выезжать за пределы белого блока.

2021-06-16 11:03 UTC, TFK70 requested changes

2021-06-16 11:03 UTC, TFK70 commented on practice/web-diary/fragments/diary/src/Diary.tsx
> +    <Background gradient='blueAndGreenGradient' height={['50vh', '100vh', '100vh']} width='100%'>
Точно нет
Background всегда занимает все пространство от родителя, манипулировать его размерами таким образом нельзя, иначе это уже не бекграунд

2021-06-16 11:03 UTC, TFK70 commented on practice/web-diary/fragments/diary/src/Diary.tsx
> +    <Background gradient='blueAndGreenGradient' height={['50vh', '100vh', '100vh']} width='100%'>
И из этого следует дефект:

https://user-images.githubusercontent.com/62806448/122208088-4e6ef480-cebc-11eb-85aa-2398dfdd4932.mov

2021-06-16 11:16 UTC, gochicus commented on practice/web-diary/fragments/diary/src/Diary.tsx
> +    <Background gradient='blueAndGreenGradient' height={['50vh', '100vh', '100vh']} width='100%'>
@TFK70 Ну я бы не сказл, что это деффект. Если скроллить в белом блоке или в `column`,  то возникают проблемы с контентом, по сравнению с которыми это ерунда. А вообще в каком ключе  это делать? Уже третье решение не то, что надо. Так что надо?

2021-06-16 11:25 UTC, TFK70 commented on practice/web-diary/fragments/diary/src/Diary.tsx
> +    <Background gradient='blueAndGreenGradient' height={['50vh', '100vh', '100vh']} width='100%'>
@gochicus я тебя немного не понимаю

1. Ты предлагаешь закрыть глаза на полуразваленную мобильную версию потому что по сравнению с полуразваленной десктопной это ерунда? 

2. > Так что надо?

Задача не понятна или готовый код нужен?

Сформулируй проблему, скажи что делал, приложи код, будем вместе смотреть что не так
И если тебе для этого придется некоторые куски приложения заново переписать - это нормально, до этого у тебя не было представления как должна выглядеть верстка с которой не будет проблем на мобилке. Сейчас есть

2021-06-16 11:41 UTC, gochicus commented on practice/web-diary/fragments/diary/src/Diary.tsx
> +    <Background gradient='blueAndGreenGradient' height={['50vh', '100vh', '100vh']} width='100%'>
@TFK70 

> Задача не понятна или готовый код нужен?

Да, сформулируй как оно должно быть выполнено.  Что можно использовать, а что нельзя (ещё бы желательно почему). Подходит ли текущая верстка или какие то фрагменты требуют переписывания.  Ну, как минимум, обозначай проблему.  Нужно понимание в каком направлении двигаться. Например, сейчас, я абсолютно уверен, что не могу использовать `height` в белом блоке, или в `column` , потому что вылезут серьезные проблемы с контентом. Но может быть я ошибаюсь, и мы об этом ещё долго не узнаем, пока я просто закидываю варианты решений, игнорирующие задание высоты.

2021-06-16 11:49 UTC, TFK70 commented on practice/web-diary/fragments/diary/src/Diary.tsx
> +    <Background gradient='blueAndGreenGradient' height={['50vh', '100vh', '100vh']} width='100%'>
@gochicus ну так ты меня сейчас просишь за тебя код написать, так не пойдет
> Что можно использовать, а что нельзя

Я вообще не уверен что есть вещи которые "нельзя" использовать, основная суть в том что у всего есть свое назначение, и если мы, например, даем бекраунду высоту 50vh - это уже никакой не бекграунд

> Подходит ли текущая верстка или какие то фрагменты требуют переписывания

Это ты сам должен выяснить. Проект и верстка твои, необходимые знания у тебя есть. Я просто слежу чтобы в твоем коде не было явных антипаттернов (как с тем же бекграундом)

> Нужно понимание в каком направлении двигаться

Тут советую еще раз разбить твою верстку на компоненты: что чем должно являться, так же как мы в example приложении делали в самом начале. Разметь верстку на высоком уровне: где должен быть Column, где Box и тд,  как каждый компонент должен изменяться, потом сравни с тем что у тебя есть сейчас

> Например, сейчас, я абсолютно уверен, что не могу использовать height в белом блоке, или в column , потому что вылезут серьезные проблемы с контентом.

Вполне вероятно пункт выше в этом поможет, это стандартная ситуация когда твоя верстка тебя же и блокирует. Тут только один вариант - переверстать (если возможно, конечно)

2021-06-16 14:03 UTC, TFK70 requested changes

2021-06-16 14:03 UTC, TFK70 commented on practice/web-diary/fragments/post-list/src/PostList.tsx
> +      height={[postData.length <= 3 ? '20%' : '100%', '100%', '100%']}
Это конечно интересно, но есть путь попроще

2021-06-16 14:03 UTC, TFK70 commented on practice/web-diary/ui/list/src/List.tsx
> +    <>
Да, возможно List как компонент и стоит обернуть снаружи во что-то, что будет регулировать его размеры, но здесь Column должен остаться, ведь без него это уже не лист, как минимум потому, что итемы будут располагаться горизонтально

2021-06-16 14:03 UTC, TFK70 commented on practice/web-diary/fragments/diary/src/Diary.tsx
>          <Box backgroundColor='white' width={['100%', '400px', '400px']}>
А в чем проблема тут height регулировать?

2021-06-16 14:07 UTC, gochicus commented on practice/web-diary/ui/list/src/List.tsx
> +    <>
@TFK70 ты смотрел верстку? Они корректно, вертикально располагаются.

2021-06-16 14:10 UTC, TFK70 commented on practice/web-diary/ui/list/src/List.tsx
> +    <>
@gochicus да, я смотрел и всегда смотрю
Я к тому что если List будет без колонки то элементы будут в ряду. Это неправильно, тк ты у себя в приложении позиционируешь List как самостоятельную сущность

2021-06-16 14:13 UTC, gochicus commented on practice/web-diary/fragments/diary/src/Diary.tsx
>          <Box backgroundColor='white' width={['100%', '400px', '400px']}>
@TFK70 В мобильной версии едет именно колонка с айтемами, если задать высоту колонке здесь или же блоку с белым цветом, то при загрузке большого числа постов они будут наезжать друг на друга, пропадут отступы, а при оверфлоу контент будет резаться.

2021-06-16 14:16 UTC, gochicus commented on practice/web-diary/ui/list/src/List.tsx
> +    <>
@TFK70 я вот сейчас вообще не понял идею. List - ui компонент для использования. То есть, использовать его можно хоть в ряд, хоть в колонку.

2021-06-17 08:20 UTC, TFK70 requested changes

2021-06-17 08:20 UTC, TFK70 commented on practice/web-diary/fragments/post-list/src/PostList.tsx
> +    <Box width='100%' justifyContent='center'>
Row

2021-06-17 08:20 UTC, TFK70 commented on practice/web-diary/fragments/post-сontrols/src/PostControls.tsx
> +    <Box width='100%' justifyContent='center'>
Row

2021-06-17 08:27 UTC, TFK70 requested changes

2021-06-17 08:27 UTC, TFK70 commented on practice/web-diary/fragments/post-list/src/PostList.tsx
> +    <Row width='100%' justifyContent='center'>
Нуу иии? `<Row width='100%'`?

2021-06-17 08:31 UTC, TFK70 approved these changes

2021-06-17 08:38 UTC, TFK70 requested changes

2021-06-17 08:38 UTC, TFK70 commented on practice/web-diary/fragments/diary/src/Diary.tsx
> +        <Box backgroundColor='white' width={['100%', '400px', '400px']}>
У тебя вид с таблета должен быть такой же как с мобилки:

![image](https://user-images.githubusercontent.com/62806448/122361870-17a6e600-cf71-11eb-944c-bfe4d3956f5c.png)

Чтобы контент не уменьшался как сейчас

2021-06-17 09:11 UTC, TFK70 requested changes

2021-06-17 09:11 UTC, TFK70 commented on practice/web-diary/fragments/post-сontrols/src/PostControls.tsx
> +          <Row>
Не уверен что понимаю зачем здесь инпут оборачивать в Row

2021-06-17 09:16 UTC, TFK70 requested changes

2021-06-17 09:16 UTC, TFK70 commented on practice/web-diary/fragments/post-сontrols/src/PostControls.tsx
>            <Row justifyContent='flex-end'>
А вот здесь Row зачем? У тебя же там в таблетке инпуту прям плохо по ширине

2021-06-17 09:52 UTC, TFK70 approved these changes
У тебя вид с таблета должен быть такой же как с мобилки:

![image](https://user-images.githubusercontent.com/62806448/122361870-17a6e600-cf71-11eb-944c-bfe4d3956f5c.png)

Чтобы контент не уменьшался как сейчас

2021-06-17 15:47 UTC, TorinAsakura approved these changes

2021-06-17 15:48 UTC, merged