WIP(web-diary): npm package content
atls-academy/frontend-study-gochicus pull request #87
Opened 2021-06-24 08:03 UTC by gochicus

ISSUES CLOSED: #81

2021-06-24 13:20 UTC, TFK70 commented
@gochicus когда ты создаешь папку - подразумевается, что там будет лежать больше одного элемента (иначе зачем папка)
Это я к тому что в том что ты засунул свой пакет в папку package не особо много смысла, переименуй ее в packageS

2021-06-24 13:29 UTC, TFK70 requested changes

2021-06-24 13:29 UTC, TFK70 commented on package/list/package.json
> +    "test": "echo \"Error: no test specified\""
Это что?

2021-06-24 13:29 UTC, TFK70 commented on package/list/package.json
> +  "name": "@gochicus/list",
А почему @academy/gochicus не получилось?

2021-06-24 13:29 UTC, TFK70 commented on package/list/src/Item.tsx
> +import { Button }                         from './button/src'
Что-то не так с путями
src создается в случае с пакетом, сейчас твои button'ы и condition'ы пакетами не являются (по-крайней мере не должны ими являться), так что если у тебя снова структура button->src где на одном уровне с src ничего не лежит то вынеси все на уровень выше

2021-06-24 13:29 UTC, TFK70 commented on package/list/src/button/src/Button.tsx
> +import styled                                  from '@emotion/styled'
Если ты называешь файлы по аналогии с uikit'ом - этот файл будет `button.component.tsx`

2021-06-24 13:29 UTC, TFK70 commented on package/list/src/layout/src/Box.tsx
> +  position,
Неужели в листе прям все надо?

2021-06-24 13:29 UTC, TFK70 commented on package/list/src/layout/src/Layout.tsx
> +export const Layout = styled.div(layout, space, flexbox, position, color, size)
И тут

2021-06-25 06:18 UTC, gochicus commented on package/list/package.json
> +  "name": "@gochicus/list",
@TFK70 Я  не совсем уверен, долго искал эту проблему и наткнулся на вот  [такое](https://rugeek.ru/questions/npm-403-forbidden-put-http-registry-npmjs-org-package-name-forbidden/)
К слову, ты смотрел  type ошибку с `Text`, про которую я в issue писал?

2021-06-25 10:47 UTC, TFK70 commented on package/list/package.json
> +  "name": "@gochicus/list",
> К слову, ты смотрел type ошибку с Text, про которую я в issue писал?

В следующий раз оставляй пожалуйста ссылку
Там импорта нет

> Я не совсем уверен, долго искал эту проблему и наткнулся на вот такое

И ты зачем-то оттуда скопипстил шаги? Есть идеи почему не сработало-то?

2021-06-25 10:52 UTC, gochicus commented on package/list/package.json
> +  "name": "@gochicus/list",
@TFK70 

> И ты зачем-то оттуда скопипстил шаги? Есть идеи почему не сработало-то?

Там нечего копипастить, но написано, что в скоупедолжно быть имя юзера, совпадающее с тем, под которым ты зарегистрирован на npm. Я в скоуп ник и записал. А почему скоуп academy не срабатывает, ну думаю от того, что довольно распространенное название.

2021-06-28 06:47 UTC, TFK70 requested changes

2021-06-28 06:47 UTC, TFK70 commented on practice/web-diary/fragments/post-list/src/PostList.tsx
> +import { List }                                            from '@gochicus/list/src'
а почему не @ui/layout/src @ui/button/src @store/post-data/src ?

2021-06-28 06:51 UTC, TFK70 commented on practice/web-diary/fragments/post-list/src/PostList.tsx
> +import { List }                                            from '@gochicus/list/src'
@gochicus и я не пойму куда сам пакет делся

2021-06-28 06:51 UTC, gochicus commented on practice/web-diary/fragments/post-list/src/PostList.tsx
> +import { List }                                            from '@gochicus/list/src'
@TFK70 без src почему-то модуль не находит

2021-06-28 06:53 UTC, TFK70 commented on practice/web-diary/fragments/post-list/src/PostList.tsx
> +import { List }                                            from '@gochicus/list/src'
> @TFK70 без src почему-то модуль не находит

Вот давай ты в таких моментах не будешь сидеть над проблемой несколько часов а потом забивать на нее, а сразу обращаться ко мне? У тебя такое уже который раз повторяется

2021-06-28 06:56 UTC, TFK70 commented on practice/web-diary/fragments/post-list/src/PostList.tsx
> +import { List }                                            from '@gochicus/list/src'
> @TFK70 без src почему-то модуль не находит
> 
> > @gochicus и я не пойму куда сам пакет делся
> 
> Он прямо из npm ставится, зачем он здесь?

Он действительно берется из npm регистра, но это не значит что нужно убивать его локальную копию
То что ты его запаблил в глобальный регистр значит что ты сможешь использовать его где угодно за пределами репозитория где он живет, но как ты будешь в случае чего обновлять сам пакет?

2021-06-28 06:59 UTC, gochicus commented on practice/web-diary/fragments/post-list/src/PostList.tsx
> +import { List }                                            from '@gochicus/list/src'
@TFK70 я над ней и не сидел, оно не работало, добавил src - заработало, если в этом где-то проблема, то обсудим. Я лично хз почему так происходит,.  Насчет содержимого пакета, надо всё же реально на это смотреть, по завершении тудушки я с ней больше ничего и никогда делать не буду, в том числе пакет обновлять.

2021-06-28 07:01 UTC, TFK70 commented on practice/web-diary/fragments/post-list/src/PostList.tsx
> +import { List }                                            from '@gochicus/list/src'
@gochicus так у тебя щас к исходникам пакета есть доступ?

2021-06-28 07:03 UTC, gochicus commented on practice/web-diary/fragments/post-list/src/PostList.tsx
> +import { List }                                            from '@gochicus/list/src'
@TFK70 есть, а если бы и не было, качаешь из npm,идешь в node modules, оттуда его тащишь и меняешь как вздумается для новой версии.

2021-06-28 07:09 UTC, TFK70 commented on practice/web-diary/fragments/post-list/src/PostList.tsx
> +import { List }                                            from '@gochicus/list/src'
> @TFK70 есть, а если бы и не было, качаешь из npm,идешь в node modules, оттуда его тащишь и меняешь как вздумается для новой версии.

Ну насчет удобства такой "методики" я лучше промолчу, но то что ты понимаешь что такое нод модули это очень хорошо, вот только в них у тебя должен находиться только js. Что там делать исходникам?

2021-06-28 07:15 UTC, gochicus commented on practice/web-diary/fragments/post-list/src/PostList.tsx
> +import { List }                                            from '@gochicus/list/src'
@TFK70 почему только js? Как ты вообще это видишь? Сейчас модуль крайне прост: он просто дает подтянуть кусок реакта в код, а затем всё это компилится  и парсится вебпаком.

2021-06-28 07:31 UTC, TFK70 commented on practice/web-diary/fragments/post-list/src/PostList.tsx
> +import { List }                                            from '@gochicus/list/src'
@gochicus https://coderoad.ru/30928253/Написание-npm-модулей-в-TypeScript

2021-06-28 07:44 UTC, TFK70 commented on practice/web-diary/fragments/post-list/src/PostList.tsx
> +import { List }                                            from '@gochicus/list/src'
@gochicus нужно пояснение? Или все понятно?

2021-06-28 07:51 UTC, gochicus commented on practice/web-diary/fragments/post-list/src/PostList.tsx
> +import { List }                                            from '@gochicus/list/src'
@TFK70  а какой ответ мне нужен? Имеется ввиду `.npmignore`. Что-то не пойму что к чему. Как сюдавписывается js?

2021-06-28 08:05 UTC, gochicus commented on practice/web-diary/fragments/post-list/src/PostList.tsx
> +import { List }                                            from '@gochicus/list/src'
@TFK70 Короче, я так и не понял как оно должно выглядеть и работать.

2021-06-28 08:29 UTC, TFK70 commented on practice/web-diary/fragments/post-list/src/PostList.tsx
> +import { List }                                            from '@gochicus/list/src'
@gochicus чекни еще связанный топик: https://coderoad.ru/13645824/Могу-ли-я-написать-пакет-npm-в-CoffeeScript

Там про coffee script но суть та же: когда ты захочешь юзать этот пакет с чистым js он будет орать на любой непонятный ему синтаксис, будь то jsx или определение типов через тайпскрипт, так что все твои супер-современные либы на последнем синтаксисе должны так или иначе полифилиться в js, чтобы их можно было использовать в любой другой среде

Плюс это weight issue, src как правило жирные, в отличие от сбилженных файлов, да они и не нужны в нод модулях никому

Чекни в тех же нод модулях как выглядит реакт, обрати внимание на его package.json

2021-06-28 08:32 UTC, gochicus commented on practice/web-diary/fragments/post-list/src/PostList.tsx
> +import { List }                                            from '@gochicus/list/src'
@TFK70 ты хочешь, чтобы модуль выдавал javascript и уже в код вставлял javascript или что?

2021-06-28 08:44 UTC, TFK70 commented on practice/web-diary/fragments/post-list/src/PostList.tsx
> +import { List }                                            from '@gochicus/list/src'
А почему "я хочу"? И что кого куда вставляет? Это просто нормы которые нужно соблюдать. Ну и внятного ответа на вопрос "зачем в нод модулях исходники" ты мне так и не дал

2021-06-28 09:01 UTC, gochicus commented on practice/web-diary/fragments/post-list/src/PostList.tsx
> +import { List }                                            from '@gochicus/list/src'
@TFK70 

> Ну и внятного ответа на вопрос "зачем в нод модулях исходники" ты мне так и не дал
Потому что ты внятно  такого вопроса не задавал. Но если на то пошло, у меня в пакете все файлы импортируюся локально, затем объединяются в лист, а он уже экспортируется. 

>  И что кого куда вставляет? Это просто нормы которые нужно соблюдать. 
Мы сейчас не абстракцию обсуждаем, а в контексте конкретной тудушки. У меня есть фрагмент с реактом, который компилится, затем парсится. Часть этого фрагмента приходит из npm пакета. Что-то мне подсказывает, что если я в реакт насыплю чистого javascript, webpack не обработает всё, радуясь,  что соблюдаются нормы. Фрагмент у нас не распарсится, приложение отображаться не будет.  И тут мы подходим к самому важному вопросу: что делать с javascript из модуля?  Я тебя в начале беседы спросил [как ты это видишь](https://github.com/atls-academy/gochicus.github.io/pull/87#discussion_r659535246), потому что, на мой взгляд, приложение сломается на этапе компиляции.  Как этот полученный javascript должен взаимодействовать с приложением?

2021-06-28 09:15 UTC, TFK70 commented on practice/web-diary/fragments/post-list/src/PostList.tsx
> +import { List }                                            from '@gochicus/list/src'
> Что там делать исходникам?

Давай без этого пожалуйста, если я задаю вопрос - значит в большинстве случаев ожидаю ответ. Ответ я не получил. (https://github.com/atls-academy/gochicus.github.io/pull/87#discussion_r659531919)

> Но если на то пошло, у меня в пакете все файлы импортируюся локально, затем объединяются в лист, а он уже экспортируется.

? Ты ведешь к тому что если тайпскрипт сбилдится в js то он сломается? Или в к тому что cjs модули не поддерживает?

> Что-то мне подсказывает

Дашь ссылку? Покажешь пример? Или это "что-то" не материальное?

> на мой взгляд

Твой взгляд формируется из предыдущего "что-то"?

Короче это все к тому что на данный момент в твоем описании слишком мало объективщины. Если ты утверждаешь что все сломается - либо подробно распиши какой момент и почему сломается (с ссылками на реальные сущности, а не на "что-то", например "webpack в этом моменте не отработает корректно потому что ..."), либо просто предоставь пример

К слову все этом время ты по-прежнему мог прикладывать код к своим комментам, он бы точно не помешал. Мы уже больше часа переписываемся текстом, а я так и не понял в чем твоя проблема, учитывая что я в целом знаю что в твоем приложении происходит. 

> Я тебя в начале беседы спросил как ты это видишь

И я по-прежнему не собираюсь писать за тебя код

2021-06-28 09:34 UTC, gochicus commented on practice/web-diary/fragments/post-list/src/PostList.tsx
> +import { List }                                            from '@gochicus/list/src'
@TFK70 

> ? Ты ведешь к тому что если тайпскрипт сбилдится в js то он сломается? Или в к тому что cjs модули не поддерживает?

 Вот фрагмент  из post-list:

>  return (
    <Row justifyContent='center'>
      <List
        deleteItem={deleteItem}
        likeItem={likeItem}
        importantItem={importantItem}
        items={filterData(postData, status, searchResult)}
        setPostData={setPostData}
      />
    </Row>
Меня волнует то, что  если вместо List там будет javascript не сломается ли приложение, когда webpack  будет парсить  react.  
Возвращаемся к этому вопросу:

> ты хочешь, чтобы модуль выдавал javascript и уже в код вставлял javascript или что?

То есть, вариантов два, либо "да", всё будет ок, либо "нет".  Если нет, то меня интересовал вопрос как это должно 
 правильно взаимодействовать в приложении, но ты считаешь последнее написанием кода за меня.

2021-06-28 09:46 UTC, TFK70 commented on practice/web-diary/fragments/post-list/src/PostList.tsx
> +import { List }                                            from '@gochicus/list/src'
@gochicus если что, jsx это просто более удобный синтаксис. Когда ты пишешь

```javascript
<List
   items={[1,2,3]}
/>
```

Под капотом происходит что-то такое

```javascript
React.createElement(List, { items: [1,2,3] })
```

Все, что ты пишешь - это в конечном итоге js. Браузеры с нодой не умеют исполнять ts, этот язык компилируемый. После компиляции он превращается в js

Ну и попробуй сам уже ответить на свой вопрос: если в браузере в среде js'а выполнится js - что-то сломается? И ты за это время мог уже тысячу раз это опробовать и скинуть лог с ошибкой при наличии

> То есть, вариантов два, либо "да", всё будет ок, либо "нет".

Не особо много от меня смысла, если б я так отвечал. Твоих знаний более чем достаточно чтобы самому отвечать на такие вопросы, опять же - посмотри как сделаны другие либы, если не хватает примеров. Реакт, наноид, либы атлантиса. Никто же не запрещает пробовать, в конце концов

2021-07-01 08:32 UTC, TFK70 requested changes

2021-07-01 08:32 UTC, TFK70 commented on package.json
> +    "list/**"
Это единственная причина по которой у тебя все работает
В нод модулях у пакета нету папки dist, в поле main указан путь до несуществующего файла

2021-07-01 08:32 UTC, TFK70 commented on list/src/icons/svg/star.svg
> +<g>
Почисти

2021-07-01 08:32 UTC, TFK70 commented on list/src/icons/svg/heart.svg
> +</g>
И тут

2021-07-01 08:32 UTC, TFK70 commented on list/src/List.interface.ts
> +  setPostData: [{}]
Насколько мне известно это коллбек

2021-07-01 08:32 UTC, TFK70 commented on list/src/List.interface.ts
> +  postObject: {}
Мало того что это объект. Какие проперти там должны быть?

2021-07-01 08:32 UTC, TFK70 commented on list/src/List.interface.ts
> +  deleteItem: [{}]
Это вроде тоже коллбек

2021-07-01 08:32 UTC, TFK70 commented on list/src/List.interface.ts
> +  items: [{ id: number }]
А тут если не ошибаюсь свойств чуть больше, чем id

2021-07-01 08:32 UTC, TFK70 commented on list/src/List.tsx
> +}: ListInterface): ReactJSXElement => {
Лучше вместо ReactJSXElement и тд писать:

```javascript
import { FC } from 'react'

const List: FC<ListProps> = () => ....
```

Более ёмко и лаконично

2021-07-01 08:34 UTC, TFK70 commented on package.json
> +    "list/**"
На всякий случай: с самим пакетом у тебя все ок (вроде как), просто сейчас он берется локально как воркспейс, соответственно в нод модули тянутся src

2021-07-01 08:46 UTC, gochicus commented on list/src/icons/svg/star.svg
> +<g>
@TFK70  У меня, кажется, проблемы, с линтом,  изменения после линта, добавленные в гит, не уходят в коммитах.

2021-07-01 08:50 UTC, gochicus commented on package.json
> +    "list/**"
@TFK70 Нет, всё прекрасно работает и без воркспейсов, в list только исходники без дистов потому, что я js файлы почистил. Попробуй установи из npm и удали list из воркспейсов, у меня всё работает.

2021-07-01 08:50 UTC, gochicus commented on package.json
> +    "list/**"
@TFK70 Нет, всё прекрасно работает и без воркспейсов, в list только исходники без дистов потому, что я js файлы почистил. Попробуй установи из npm и удали list из воркспейсов, у меня всё работает.

2021-07-01 08:51 UTC, TFK70 commented on package.json
> +    "list/**"
> @TFK70 Нет, всё прекрасно работает и без воркспейсов, в list только исходники без дистов потому, что я js файлы почистил. Попробуй установи из npm и удали list из воркспейсов, у меня всё работает.

Ну так я про это и написал, что с пакетом все в порядке, убери его из воркспейсов

2021-07-01 08:56 UTC, TFK70 commented on list/src/icons/svg/star.svg
> +<g>
Если git status их подсвечивает попробуй сделать коммит просто через git commit

2021-07-01 10:31 UTC, TFK70 requested changes

2021-07-01 10:31 UTC, TFK70 commented on list/src/List.interface.ts
> +  deleteItem: []
Еще раз:

1. Это коллбек
2. Даже если бы это был массив - указывай из каких элементов он состоит. Сейчас исходя из твоего интерфейса я могу написать в пропсах deleteItem={[1]} и все будет прекрасно работать

2021-07-01 10:31 UTC, TFK70 commented on list/package.json
> +    "@atlantis-lab/tsconfig": "^0.1.12",
Почему это в обычных зависимостях?

2021-07-01 10:48 UTC, gochicus commented on list/src/List.interface.ts
> +  deleteItem: []
@TFK70 никогда не слышал про коллбек с использованием квадратных скобок. Есть ссылки, где об этом сказано? Лично я ориентируюсь на вот  [это](http://typescript-lang.ru/docs/Basic%20Types.html#Tuple)

2021-07-01 11:29 UTC, TFK70 requested changes

2021-07-01 11:29 UTC, TFK70 commented on list/src/List.interface.ts
> +  ) => []
эти функции ничего не возвращают
ты же понимаешь зачем ты это типизируешь?

2021-07-01 11:44 UTC, gochicus commented on list/src/List.interface.ts
> +  ) => []
@TFK70 

>  ты же понимаешь зачем ты это типизируешь?

В данном случае, нет. 

> эти функции ничего не возвращают

Ну, по идее массив. Если я перепишу на Array<any> будет лучше?

2021-07-01 11:49 UTC, TFK70 commented on list/src/List.interface.ts
> +  ) => []
> В данном случае, нет.

Так с этого и надо было начать. Это нужно исключительно для того чтобы понимать что компонент ожидает на вход. Если ты определишь компонент так

```javascript
<List
   deleteItem={['wesfaew']}
   setPostData={123}
```

И он ни на что не поругается - это правильное поведение или нет?

2021-07-01 11:57 UTC, TFK70 requested changes

2021-07-01 11:57 UTC, TFK70 commented on list/src/List.interface.ts
> +  ) => Array<any>
Что изменилось?

2021-07-01 12:14 UTC, TFK70 commented on list/src/List.interface.ts
> +  ) => Array<any>
@gochicus короче я веду к тому чтобы ты типизировал item:

```javascript
interface Item { .... }
```

А потом использовал его для типизации коллбеков:

```javascript
interface ListProps {
   items: Item[]
   deleteItem: () => Item[]
   ....
}
```

2021-07-01 12:33 UTC, gochicus commented on list/src/List.interface.ts
> +  ) => Array<any>
@TFK70 так, я это только после коммита увидел, инет отваливался.  Но как-то я с айтемом я идею не понял, ведь это просто большой JSX компонент и не представляю как его типизация поможет, ведь он не хранит логики и данных. Не представляю как это поможет.

2021-07-01 12:46 UTC, TFK70 requested changes

2021-07-01 12:46 UTC, TFK70 commented on list/package.json
> +  "name": "@gochicus/list2",
Почему 2?

2021-07-01 12:50 UTC, gochicus commented on list/package.json
> +  "name": "@gochicus/list2",
@TFK70 для теста использовал другое название, чтобы не путать с npm.  Поменять обратно?

2021-07-01 12:51 UTC, TFK70 commented on list/package.json
> +  "name": "@gochicus/list2",
Ну да

2021-07-01 12:52 UTC, TFK70 requested changes

2021-07-01 12:52 UTC, TFK70 commented on list/src/List.interface.ts
> +  ) => [{ post?: string | number; important?: boolean; like?: boolean; id: number }]
Я же показал пример: вынеси в отдельный интерфейс, зачем код дублировать?

2021-07-01 12:55 UTC, gochicus commented on list/src/List.interface.ts
> +  ) => [{ post?: string | number; important?: boolean; like?: boolean; id: number }]
@TFK70 если два файла, то папка types нужна будет?

2021-07-01 12:57 UTC, TFK70 commented on list/src/List.interface.ts
> +  ) => [{ post?: string | number; important?: boolean; like?: boolean; id: number }]
@gochicus а че зачем два файла?

2021-07-01 12:58 UTC, TFK70 commented on list/src/List.interface.ts
> +  ) => Array<any>
@gochicus ты щас тупо дублируешь [{ post?: string | number; important?: boolean; like?: boolean; id: number }]
Вынеси это в type и используй

2021-07-01 13:12 UTC, TFK70 requested changes

2021-07-01 13:12 UTC, TFK70 commented on list/src/List.interface.ts
> +  object: { post?: string | number; important?: boolean; like?: boolean; id: number }
Зачем?

2021-07-01 13:12 UTC, TFK70 commented on list/src/List.interface.ts
> +    postData: [PostDataObject['object']],
Короче:

```javascript
export interface ListInterface {
  items: PostDataObject[]
  deleteItem: (postData: PostDataObject[], id: number) => PostDataObject[]
  importantItem: (
    postData: PostDataObject[],
    id: number,
    status: boolean,
  ) => PostDataObject[]
  likeItem: (
    postData: PostDataObject[],
    id: number,
    status: boolean,
  ) => PostDataObject[]
  postObject: PostDataObject
  setPostData: () => PostDataObject[]
}

export interface PostDataObject { post?: string | number; important?: boolean; like?: boolean; id: number }
```

Тут все понятно?

2021-07-01 13:19 UTC, gochicus commented on list/src/List.interface.ts
> +    postData: [PostDataObject['object']],
@TFK70 Да, тут надо было возвращать массивы с объектами типов PostDataObject, а я ошибся, не поставил скобки и возвращал просто объект PostDataObject.

2021-07-01 13:21 UTC, TFK70 commented on list/src/List.interface.ts
> +    postData: [PostDataObject['object']],
@gochicus да ты еще и дополнительную вложенность в интерфейсе зачем-то добавил

2021-07-01 13:22 UTC, TFK70 commented on list/src/List.interface.ts
> +    postData: [PostDataObject['object']],
@gochicus да и вообще: у тебя же типы у коллбеков одинаковые, вынеси их тоже

2021-07-01 13:41 UTC, TFK70 requested changes

2021-07-01 13:41 UTC, TFK70 commented on list/src/List.interface.ts
> +  object: { post?: string | number; important?: boolean; like?: boolean; id: number }
Зачем? x2

2021-07-01 13:41 UTC, TFK70 commented on list/src/List.interface.ts
> +  likeItem: (CallbackInterface) => PostDataObject['object'][]
Так они же у тебя по-прежнему все 3 абсолютно идентичны, создай тип для коллбека и только его и используй

2021-07-01 13:41 UTC, TFK70 commented on list/src/List.interface.ts
>  export interface PostDataObject {
Ну и на будущее: имей привычку определять использующиеся в дальнейшем коде переменные до их непосредственного использования (перенеси вспомогательные интерфейсы наверх)

2021-07-01 13:41 UTC, TFK70 commented on list/src/List.interface.ts
> +  object: { post?: string | number; important?: boolean; like?: boolean; id: number }
Или PostDataObject['object'] удобнее чем PostDataObject?

2021-07-01 13:55 UTC, TFK70 requested changes

2021-07-01 13:55 UTC, TFK70 commented on list/src/List.interface.ts
> +  likeItem: CallbackInterface['callback']
Я не понимаю зачем ты это делаешь
Ты только что исправил это в PostDataObject и сделал абсолютно аналогичное тут? Тебе что-то мешает просто type использовать?

```javascript
type Callback = ({ ... }) => PostDataObject[]
```

Интерфейсы типа предназначены для типизации классов, а классы - это объекты, из этого следует что любой интерфейс по дефолту как бы тоже объект, поэтому их удобно использовать для типизации пропсов (потому что пропсы - это объект). Если тебе как сейчас никакой объект типизировать не надо - просто используй type и почитай доку

2021-07-01 13:55 UTC, TFK70 commented on list/src/List.interface.ts
>  export interface PostDataObject {
И наверх ты ничего так и не вынес

2021-07-01 14:00 UTC, gochicus commented on list/src/List.interface.ts
> +  likeItem: CallbackInterface['callback']
@TFK70 

>  И наверх ты ничего так и не вынес

ЧТо ты имеешь ввиду? в смысле в файле?

2021-07-01 14:02 UTC, TFK70 commented on list/src/List.interface.ts
> +  likeItem: CallbackInterface['callback']
Ну да, у тебя вспомогательные интерфейсы определяются после того, как они используются, поэтому вынеси их наверх
Это просто ради кодстайла, код все-таки сверху вниз читают

2021-07-01 14:22 UTC, TFK70 approved these changes

2021-07-01 14:30 UTC, TFK70 requested changes

2021-07-01 14:30 UTC, TFK70 commented on list/src/List.interface.ts
> +  postObject: PostDataObject
Это что?

2021-07-01 14:30 UTC, TFK70 commented on list/src/List.interface.ts
> +  items: [PostDataObject]
Интересный тип
Знаешь что такое tuple? И в чем разница между PostDataObject[]?

2021-07-01 14:37 UTC, gochicus commented on list/src/List.interface.ts
> +  postObject: PostDataObject
@TFK70 Тут всё верно, именно объект с указанными типами. То же самое, что и одиночный item, но названия разные для лучшего понимания кода.

2021-07-01 14:38 UTC, TFK70 commented on list/src/List.interface.ts
> +  postObject: PostDataObject
Он тут зачем? Я вот посмотрел в твой фрагмент и там такого пропа нет, да и я не совсем понимаю его смысл

```javascript
      <List
        deleteItem={deleteItem}
        likeItem={likeItem}
        importantItem={importantItem}
        items={filterData(postData, status, searchResult)}
        setPostData={setPostData}
      />
```

2021-07-01 14:38 UTC, gochicus commented on list/src/List.interface.ts
> +  items: [PostDataObject]
@TFK70  кортеж, когда данные внутри разных типов.  Исправлю на это PostDataObject[].

2021-07-01 14:40 UTC, TFK70 commented on list/src/List.interface.ts
> +  items: [PostDataObject]
@gochicus тут скорее суть была в том что их ограниченное количество, но да, с помощью таплов так же можно типизировать массив где разные типы

2021-07-01 14:41 UTC, gochicus commented on list/src/List.interface.ts
> +  postObject: PostDataObject
@TFK70 прокидывается в Item, используется для управления внешним видом в зависимости от свойств конкретного объекта.

2021-07-01 17:37 UTC, TFK70 commented on list/src/List.interface.ts
> +  postObject: PostDataObject
@gochicus никуда он не прокидывается, ты интерфейсы перепутал
Item у тебя вообще не типизирован

2021-07-02 04:30 UTC, gochicus commented on list/src/List.interface.ts
> +  postObject: PostDataObject
@TFK70 Абсолютно не согласен с твоей оценкой. Но возникает ощущение, что мы разные вещи обсуждаем. Предлагаю созвониться, как у тебя время будет, и детально всё обсудить.

2021-07-02 07:03 UTC, TFK70 requested changes

2021-07-02 07:03 UTC, TFK70 commented on list/src/Item.tsx
> +import { HeartIcon, StarIcon, TrashIcon } from './icons/src'
Зачем они в src?

2021-07-02 07:03 UTC, TFK70 commented on list/src/List.tsx
> +import { ListInterface }    from './List.interface'
Если уж называешь в таком стиле:

`list.interface.ts`
`list.component.tsx`

2021-07-02 07:03 UTC, TFK70 commented on list/src/icons/svg/heart.svg
> +<?xml version="1.0" encoding="iso-8859-1"?>
И не совсем понимаю зачем тебе держать свг

2021-07-02 07:03 UTC, TFK70 commented on practice/web-diary/webpack.config.ts
> -      exclude: /node_modules/,
почему убрал?

2021-07-02 07:14 UTC, TFK70 requested changes

2021-07-02 07:14 UTC, TFK70 commented on list/src/List.component.tsx
> +export const ListComponent: FC<ListInterface> = ({
Название-то List по-прежнему

2021-07-02 07:15 UTC, TFK70 commented on list/src/Item.tsx
> +import { HeartIcon, StarIcon, TrashIcon } from './icons/src'
@gochicus

2021-07-02 07:53 UTC, TFK70 requested changes

2021-07-02 07:53 UTC, TFK70 commented on list/src/index.ts
> +export { ListComponent } from './List.component'
Ну так `list.component.tsx` и `List.component.tsx`, первая буква в лоуеркейсе

2021-07-02 07:55 UTC, gochicus commented on list/src/index.ts
> +export { ListComponent } from './List.component'
@TFK70 должна быть в лоуеркейсе?

2021-07-02 07:57 UTC, TFK70 commented on list/src/index.ts
> +export { ListComponent } from './List.component'
да

2021-07-02 08:01 UTC, TFK70 requested changes

2021-07-02 08:01 UTC, TFK70 commented on list/src/list.component.tsx
> +import { ListInterface }    from './list.interface'
Да, и лучше называть интерфейсы исходя из того что они типизируют, чтобы меньше путаницы было: `ListProps`

2021-07-02 08:43 UTC, TFK70 submitted a review, later dismissed

2021-07-02 08:59 UTC, TorinAsakura commented on list/package.json
> +  "description": "item iteration",
Что такое item iteration и что оно делает в описании пакета?

2021-07-02 09:01 UTC, TorinAsakura commented on list/src/button/base/base.styles.ts
> +  display: 'flex',
я полагаю, что это всё же потоковый объект, а не тупо блочный

2021-07-02 09:02 UTC, gochicus commented on list/package.json
> +  "description": "item iteration",
@TorinAsakura это, собственно, описание пакета.

2021-07-02 09:03 UTC, gochicus commented on list/src/button/base/base.styles.ts
> +  display: 'flex',
@TorinAsakura можешь развернуть мысль? в чём тут проблема?

2021-07-02 09:04 UTC, TorinAsakura approved these changes, later dismissed

2021-07-02 09:05 UTC, TorinAsakura commented on list/src/button/base/base.styles.ts
> +  display: 'flex',
в том, что это должно быть inline-flex

2021-07-02 09:06 UTC, TorinAsakura commented on list/package.json
> +  "description": "item iteration",
и как твоё описание даёт понимание о содержимом пакета? Либо сделай нормальное описание либо убери вообще это поле

2021-07-02 09:14 UTC, TorinAsakura approved these changes

2021-07-02 09:18 UTC, TFK70 approved these changes

2021-07-02 09:29 UTC, merged