WIP(frontend-study-gochicus): yarn2 migration in progress
atls-academy/frontend-study-gochicus pull request #89
Opened 2021-07-12 11:27 UTC by gochicus

ISSUES CLOSED: #88

2021-08-03 09:42 UTC, TFK70 commented
@gochicus ты смотрел как app [тут](https://github.com/atls/serenity/tree/dev/frontend/site/app) оформлен?
1. Не нужно ничего дублировать, укажи в воркспейсах прямой путь только до web-diary: `"practice/web-diary/**/*"`
2. Почему pages находятся не в app?
3. Почему next.config.js не в app?
4. Почему в app нету скриптов запускающих проект, как мы и договаривались?

2021-08-03 09:49 UTC, gochicus commented
@TFK70  Да, собственно структуру и постарался сделать похожей:

- package и next.config
- src
А уже внутри самого src pages  и все папки проекта, которые потом отходят в index, который находится в pages.

2021-08-03 10:02 UTC, TFK70 commented
@gochicus я не понимаю почему файлы необходимые для запуска приложения находятся вне app и почему у тебя весь твой проект находится в src
По-крайней мере в серенити я такого не припомню, там страницы являются отдельными [пакетами](https://github.com/atls/serenity/tree/dev/frontend/site/projects-detail-page), которые потом устанавливаются в app как [зависимости](https://github.com/atls/serenity/blob/dev/frontend/site/app/package.json#L38) и [экспортируются в pages](https://github.com/atls/serenity/blob/dev/frontend/site/app/src/pages/projects/%5Bid%5D.ts) по соответствующим роутам буквально в 1 строку, твой проект даже отдаленно ничего подобного не напоминает

Ну и еще:

1. Я не понимю зачем ты используешь ReactDOM руками (ReactDOM.render)
2. Ты должен оборачивать свое приложение в провайдеры через кастомный app (_app.tsx), см. доку некста. Судя по всему ты на тестовом проекте так с ним и не поигрался, так что попробуй сначала добавить пару провайдеров там, а потом внедряй к себе. Примеры реализаций можешь найти в репозитории nextjs в атлантисе, ссылку уже оставлял

2021-08-04 08:26 UTC, gochicus commented
@TFK70  Посмотри, пожалуйста, структуру, так оно должно выглядеть?

2021-08-04 08:41 UTC, TFK70 commented
@gochicus все, что до папки src - верно, но
1. Где pages?
2. Где index (http сервер где инициализируется next)?
3. Чтобы next понял что ты собираешься переписать встроенный app твой файл должен называться _app.tsx (дока)

2021-08-04 08:45 UTC, gochicus commented
@TFK70  Не закинулось почему-то, сейчас докину.

2021-08-04 08:56 UTC, TFK70 commented
@gochicus 1. Зачем тебе 2 тсконфига?
2. Зачем тебе App.tsx? В серенити же есть пример экспорта в pages, у тебя должно быть точно так же, без всяких Result

Конечно можешь это оставить пока у тебя приложение не запустится, если так удобнее, но в результате такого быть точно не должно

2021-08-04 08:58 UTC, gochicus commented
@TFK70  я к чему,  если структура правильная, то это билдится должно?

2021-08-04 09:08 UTC, TFK70 commented
@gochicus перемести next.config.js и tsconfig в src, используй next@10.0.5 и тогда да, должно

2021-08-04 09:10 UTC, gochicus commented
@TFK70 так next.config доожен же быть рядом с package,  разве нет?

2021-08-04 09:15 UTC, TFK70 commented
@gochicus нет
и тебе не обязательно такие вещи у меня спрашивать, проверил бы сам

2021-08-05 11:19 UTC, TFK70 commented
@gochicus 
```javascript
import express from 'express'
import next    from 'next'
import path    from 'path'

const bootstrap = async () => {
  const app = next({
    dev: process.env.NODE_ENV !== 'production',
    dir: process.env.NODE_ENV !== 'production' ? path.join(__dirname, '../src') : __dirname,
  })

  const handle = app.getRequestHandler()

  await app.prepare()

  const server = express()

  server.get('*', (req, res) => handle(req, res))

  server.listen(process.env.PORT || 3000)
}

bootstrap()
```

https://github.com/atls/serenity/blob/dev/frontend/site/app/src/index.ts

2021-08-05 11:51 UTC, gochicus commented
@TFK70  всё билдится, но почему-то при запуске dev  pages не находится. Возможно мне каких-то пакетов не хватает? 
```
 Update failed: Error: apply() is only allowed in ready status
                             at /home/aleksandr/Desktop/project/frontend-study-gochicus/practice/web-diary/app/dist/index.js:1802:21
●  (node:24028) UnhandledPromiseRejectionWarning: Error: > Couldn't find a `pages` directory. Please create one under the project root
●      at findPagesDir (/home/aleksandr/Desktop/project/frontend-study-gochicus/.yarn/__virtual__/next-virtual-3faeefb9bb/0/cache/next-npm-10.2.3-e1de0387ed-715c83439f.zip/node_modules/next/dist/lib/find-pages-dir.js:3:170)
●      at new DevServer
   (/home/aleksandr/Desktop/project/frontend-study-gochicus/.yarn/__virtual__/next-virtual-3faeefb9bb/0/cache/next-npm-10.2.3-e1de0387ed-715c83439f.zip/node_modules/next/dist/server/next-dev-server.js:2:1761)
●      at NextServer.createServer
   (/home/aleksandr/Desktop/project/frontend-study-gochicus/.yarn/__virtual__/next-virtual-3faeefb9bb/0/cache/next-npm-10.2.3-e1de0387ed-715c83439f.zip/node_modules/next/dist/server/next.js:1:2904)
●      at /home/aleksandr/Desktop/project/frontend-study-gochicus/.yarn/__virtual__/next-virtual-3faeefb9bb/0/cache/next-npm-10.2.3-e1de0387ed-715c83439f.zip/node_modules/next/dist/server/next.js:1:3371
●      at async NextServer.prepare
   (/home/aleksandr/Desktop/project/frontend-study-gochicus/.yarn/__virtual__/next-virtual-3faeefb9bb/0/cache/next-npm-10.2.3-e1de0387ed-715c83439f.zip/node_modules/next/dist/server/next.js:1:2679)
●      at async bootstrap (webpack-internal:///./practice/web-diary/app/src/index.ts:17:5)
●  (Use `node --trace-warnings ...` to show where the warning was created)
●  (node:24028) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with
   .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
●  (node:24028) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

2021-08-05 11:56 UTC, TFK70 commented
@gochicus путь до src неверный

1. index.ts должен находится в src
2. в app должно быть это
 const app = next({ 
    dev: process.env.NODE_ENV !== 'production', 
    dir: process.env.NODE_ENV !== 'production' ? path.join(__dirname, '../src') : __dirname, 
  })

2021-08-05 11:59 UTC, gochicus commented
@TFK70  

1. Да, он в src
2. в смысле в _app ?

2021-08-05 12:02 UTC, TFK70 commented
@gochicus а что ты в _app собрался делать?
index.ts у тебя должен выглядеть так

import express from 'express'
import next    from 'next'
import path    from 'path'

const bootstrap = async () => {
  const app = next({
    dev: process.env.NODE_ENV !== 'production',
    dir: process.env.NODE_ENV !== 'production' ? path.join(__dirname, '../src') : __dirname,
  })

  const handle = app.getRequestHandler()

  await app.prepare()

  const server = express()

  server.get('*', (req, res) => handle(req, res))

  server.listen(process.env.PORT || 3000)
}

bootstrap()

2021-08-06 12:11 UTC, TFK70 requested changes

2021-08-06 12:11 UTC, TFK70 commented on package.json
> +    "diary": "yarn workspace @web-diary/app run start"
Вообще скрипт должен называться dev

2021-08-06 12:11 UTC, TFK70 commented on practice/web-diary/app/src/next.config.js
> +const { withAliases } = require('./helpers/withAliases')
Ну нет, сделай как надо с index.js

Импорты должны выглядеть так:

```javascript
const { withAliases } = require('./helpers')
const { withFutureWebpack5 } = require('./helpers')
```

2021-08-06 12:11 UTC, TFK70 commented on practice/web-diary/app/src/pages/_app.tsx
> +function MyApp({ Component, pageProps }) {
Я понимаю что так написано в доке, но:
1. Не помню когда я в последний раз `function` в js/ts видел, сделай как надо через стрелочную функцию
2. Переименуй из MyApp в App

2021-08-06 12:11 UTC, TFK70 commented on practice/web-diary/ui/theme/src/globals.ts
>      '#root': {
Такого уже не должно быть, у тебя __next вместо этого

2021-08-06 12:11 UTC, TFK70 commented on package.json
> +    "diary": "yarn workspace @web-diary/app run start"
`yarn workspace @web-diary/app dev`

2021-08-06 12:25 UTC, gochicus commented on practice/web-diary/app/src/next.config.js
> +const { withAliases } = require('./helpers/withAliases')
@TFK70  ты хочешь, чтобы я прямо пакет сделал с package ?

2021-08-06 12:34 UTC, TFK70 commented on practice/web-diary/app/src/next.config.js
> +const { withAliases } = require('./helpers/withAliases')
нет, зачем?
просто создай index.js в директории helpers чтобы у тебя импорты выглядели так как я показал и не нужно было напрямую к файлам обращаться

2021-08-06 12:35 UTC, gochicus commented on practice/web-diary/app/src/next.config.js
> +const { withAliases } = require('./helpers/withAliases')
@TFK70 так ты ж говорил, что не нужно их в одном файле держать, а если  индексы по директориям их раскидать, то они просто их helpers тоже не находятся

2021-08-06 12:37 UTC, TFK70 commented on practice/web-diary/app/src/next.config.js
> +const { withAliases } = require('./helpers/withAliases')
@gochicus ты знаешь зачем index.ts/js файлы нужны?

2021-08-06 12:40 UTC, gochicus commented on practice/web-diary/app/src/next.config.js
> +const { withAliases } = require('./helpers/withAliases')
@TFK70 а, ты экспортировать через него хотел.

2021-08-06 12:48 UTC, gochicus commented on practice/web-diary/app/src/next.config.js
> +const { withAliases } = require('./helpers/withAliases')
@TFK70 
```
> Build error occurred
/home/aleksandr/Desktop/project/frontend-study-gochicus/practice/web-diary/app/src/helpers/index.js:1
export * from  './withAliases'
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
```

2021-08-06 13:06 UTC, TFK70 commented on practice/web-diary/app/src/next.config.js
> +const { withAliases } = require('./helpers/withAliases')
@gochicus какой модуль? 
Ты пытаешься использовать esm синтаксис в js файле который потом никак не транспилится, он понимает только cjs

2021-08-06 13:09 UTC, gochicus commented on practice/web-diary/app/src/next.config.js
> +const { withAliases } = require('./helpers/withAliases')
@TFK70 Уже написал про старый синтаксис:
```
const  withAliases = require('./withAliases')
const  withFutureWebpack5 = require('./withFutureWebpack5')
module.exports = withAliases
module.exports = {withFutureWebpack5}
```
 Ошибка: 
```
> Build error occurred
TypeError: withAliases is not a function
    at Object.<anonymous> (/home/aleksandr/Desktop/project/frontend-study-gochicus/practice/web-diary/app/src/next.config.js:9:3)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.external_module_.Module._load (/home/aleksandr/Desktop/project/frontend-study-gochicus/.pnp.cjs:24662:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at loadConfig (/home/aleksandr/Desktop/project/frontend-study-gochicus/.yarn/__virtual__/next-virtual-3faeefb9bb/0/cache/next-npm-10.2.3-e1de0387ed-715c83439f.zip/node_modules/next/dist/next-server/server/config.js:8:72)
    at async Span.traceAsyncFn (/home/aleksandr/Desktop/project/frontend-study-gochicus/.yarn/__virtual__/next-virtual-3faeefb9bb/0/cache/next-npm-10.2.3-e1de0387ed-715c83439f.zip/node_modules/next/dist/telemetry/trace/trace.js:6:584)
    at async /home/aleksandr/Desktop/project/frontend-study-gochicus/.yarn/__virtual__/next-virtual-3faeefb9bb/0/cache/next-npm-10.2.3-e1de0387ed-715c83439f.zip/node_modules/next/dist/build/index.js:2:127
```

2021-08-06 13:10 UTC, TFK70 commented on practice/web-diary/app/src/next.config.js
> +const { withAliases } = require('./helpers/withAliases')
@gochicus что ты сделал? Тебе не надо было ничего менять, просто экспортировать все через index.js

```javascript
const { withFutureWebpack5 } = require('./withFutureWebpack5')
const { withAliases } = require('./withAliases')

module.exports = {
  withAliases,
  withFutureWebpack5
}
```

2021-08-06 13:15 UTC, gochicus commented on practice/web-diary/app/src/next.config.js
> +const { withAliases } = require('./helpers/withAliases')
@TFK70 можешь объяснить? Ошибка в том, что я (старый синтаксис) модуль дважды экспортировал?

2021-08-06 13:16 UTC, TFK70 commented on practice/web-diary/app/src/next.config.js
> +const { withAliases } = require('./helpers/withAliases')
@gochicus откуда я знаю? Тебе надо было просто index.js файл добавить и все бы заработало, я без понятия что ты там вертеть начал

2021-08-06 13:29 UTC, TFK70 requested changes

2021-08-06 13:29 UTC, TFK70 commented on practice/web-diary/app/package.json
> +  "main": "index.tsx",
Тут такого файла нет

2021-08-06 13:38 UTC, gochicus commented on practice/web-diary/app/package.json
> +  "main": "index.tsx",
@TFK70 по аналогии с serenity main файлом  будет index.ts с которого next dev запускается?

2021-08-06 13:40 UTC, TFK70 commented on practice/web-diary/app/package.json
> +  "main": "index.tsx",
тут дело не в аналогии с серенити а тупо в работоспособности, ты ссылаешься на файл которого нет

2021-08-06 13:43 UTC, gochicus commented on practice/web-diary/app/package.json
> +  "main": "index.tsx",
@TFK70 index.tsx понятно, пропустил, я спрашиваю(чтобы коммиты не плодить лишний раз неправильные) будет ли правильно поставить в main src/index.ts в нем next настройки для сервера, в serenity вроде так же.

2021-08-06 13:48 UTC, TFK70 commented on practice/web-diary/app/package.json
> +  "main": "index.tsx",
еще раз: причем тут серенити? у тебя есть один index.ts который лежит в src, почему тебе тебе нужно сверяться с серенити чтобы указать путь до существующего индекса? и ты вообще понимаешь зачем поле main нужно?

2021-08-06 13:55 UTC, gochicus commented on practice/web-diary/app/package.json
> +  "main": "index.tsx",
@TFK70 main это поле которое обозначает вебпаку точку входа вприложение. Что происходит в данном индексе я понимаю не полностью, но вроде как обозначен next и пути, сам next хз как потом собирает проект. Вроде похоже на точку входа в проект, а вроде и не привычно. Посмотрел в серенити, вроде все верно, потом обратился с вопросм к тебе, вдруг я сильно не прав.

2021-08-06 14:08 UTC, TFK70 approved these changes

2021-08-06 14:10 UTC, TFK70 requested changes

2021-08-06 14:10 UTC, TFK70 commented on practice/web-diary/app/package.json
> +    "@formatjs/intl": "^1.13.4",
Зачем?

2021-08-06 14:10 UTC, TFK70 commented on practice/web-diary/app/package.json
> +    "pnp-webpack-plugin": "^1.6.4",
У тебя где-то вебпак есть?

2021-08-06 14:16 UTC, gochicus commented on practice/web-diary/app/package.json
> +    "@formatjs/intl": "^1.13.4",
@TFK70 Возникло в консоличто возможно этого не хватает, когда с intl проблемы были,  как воспроизвести не помню, но без него всё работает, так что убираю.

2021-08-06 15:07 UTC, TFK70 requested changes

2021-08-06 15:07 UTC, TFK70 commented on package.json
>      "hooks": {
Это старый метод, добавляй хуки через yarn husky add: https://typicode.github.io/husky/#/?id=create-a-hook

2021-08-06 15:07 UTC, TFK70 commented on package.json
> +    "@atls/actl-format": "^0.0.17",
Зачем?

2021-08-06 15:07 UTC, TFK70 commented on package.json
> +    "react": "^17.0.2",
Почему это тут?

2021-08-06 15:07 UTC, TFK70 commented on package.json
> +    "react-dom": "^17.0.2",
И это

2021-08-06 15:07 UTC, TFK70 commented on package.json
> +    "styled-system": "^5.1.5"
И это

2021-08-06 15:07 UTC, TFK70 commented on package.json
>      "lerna": "3.22.1",
Мы лерну уже не используем?

2021-08-06 15:07 UTC, TFK70 commented on lerna.json
> +  "packages": ["lessons/**/*", "practice/**/*"],
лерна конфиг соответственно тоже не нужен

2021-08-06 15:31 UTC, TFK70 requested changes
Прекоммит хука нет

2021-08-06 15:41 UTC, TFK70 requested changes

2021-08-06 15:41 UTC, TFK70 commented on package.json
>      "hooks": {
https://github.com/atls-academy/gochicus.github.io/pull/89/commits/f8c0a1e061f7745c6bc06f25ed1cda820c1f9022#r684307110

2021-08-07 08:31 UTC, TFK70 requested changes
1. Почему у тебя 2 директории с хаски? `.husky` и `.config/husky`?
Прекоммит хук должен лежать в `.config/husky/precommit.sh`

2. Я же написал что у тебя команда yarn commit staged, почему у тебя прекммит выглядит так:

```javascript
actl precommit
yarn lint yarn typecheck
actl lint actl typecheck
actl lint && actl typecheck
yarn precommit
yarn precommit
yarn precommit
actl lint
actl lint
actl lint
 yarn actl lint
yarn run actl lint
yarn precommit
```

2021-08-07 10:20 UTC, gochicus commented
@TFK70 нужно понимать, что руками я эти директории не создавал и не переименовывал. Сначала,как в доках, инсталляция хаски, потом гит хуков. Потом установка гит хуков с определенной командой, там  в консоли при вводе новой команды появляется надпись hook updated, я думал он меняется, а не все подряд туда пихает. Попробую удалить папки,все заново поставить как за комп сяду. Если есть какие-то советы по очередности команд, напиши. Как я делал уже написал.

2021-08-07 10:36 UTC, TFK70 commented
@gochicus А еще нужно понимать что у тебя приложение не билдится и в деве не поднимается, ты как проверял-то?
И еще раз насчет хаски - в доке есть абсолютно все необходимое, я указал где должен лежать прекоммит хук, его можно создать в необходимом месте так же через cli, читай внимательнее, ищи по кейвордам

2021-08-07 10:40 UTC, gochicus commented
@TFK70  Нормально билдилось и запускалось, когда проверял, не думаю что husky мог повлиять на билд, но если так, проверю.

2021-08-07 10:42 UTC, TFK70 commented
@gochicus Оно даже в чеках упало если что
https://github.com/atls-academy/gochicus.github.io/runs/3264527923#step:7:15

2021-08-07 10:45 UTC, gochicus commented
@TFK70 Я открываю твою ссылку, он мне показывает выполненные чеки,  открываю ветку, показывает, что последний комит чеки прошёл

2021-08-07 10:46 UTC, TFK70 commented
@gochicus Ты лог failed to compile не видишь?
https://github.com/atls-academy/gochicus.github.io/runs/3264527923#step:7:13

2021-08-07 12:49 UTC, TFK70 requested changes
1. husky/_ должен быть в игноре
2. Убери precommit скрипт (в хуке пиши просто yarn commit staged)
3. Поменяй пиры в packageExtensions на обычные dependencies

2021-08-18 15:59 UTC, TorinAsakura approved these changes

2021-08-18 15:59 UTC, merged