feat(how-to-use-objects): turning functions into object properties to…
atls-academy/frontend-study-gochicus pull request #9
Opened 2020-12-11 20:29 UTC by gochicus

… make them one product

ISSUES CLOSED: #8

2020-12-11 21:23 UTC, themetronome requested changes
Снова замечание про форматирование кода, его просто нет

2020-12-11 21:23 UTC, ad21ewda1231dsa123das12 commented on lessons/how-to-use-objects/src/index.js
> +  moviesCount:  () => {
double whitespace

2020-12-11 21:23 UTC, ad21ewda1231dsa123das12 commented on lessons/how-to-use-objects/src/index.js
> +let personalMoviesDB = {
let or const?

2020-12-11 21:23 UTC, ad21ewda1231dsa123das12 commented on lessons/how-to-use-objects/src/index.js
> +      personalMoviesDB.genres[ i ] = prompt(`Ваш любимый жанр № ${i}?`);
Даже не знаю, на мой взгляд здесь наоборот целесообразнее присвоить в переменную. Как пример, монструозное выражение при проверке if

2020-12-11 21:23 UTC, themetronome commented on lessons/how-to-use-objects/src/index.js
> +        }
А где запись введённых с промпта данных в поле объекта?

2020-12-11 21:23 UTC, themetronome commented on lessons/how-to-use-objects/src/index.js
> +           i--;
Было бы неплохо, уведомить пользователя о том что он ввёл данные неверно

2020-12-11 21:23 UTC, themetronome commented on lessons/how-to-use-objects/src/index.js
> +  count: [],
Массив здесь не нужен

2020-12-11 21:23 UTC, themetronome commented on lessons/how-to-use-objects/src/index.js
> +        i--
semicolon

2020-12-11 21:23 UTC, themetronome commented on lessons/how-to-use-objects/src/index.js
> +    return personalMoviesDB.count = numberOfFilms;
Для чего `return`?

2020-12-11 21:23 UTC, themetronome commented on lessons/how-to-use-objects/src/index.js
> +    let numberOfFilms = +prompt('Сколько фильмов вы уже посмотрели?', '');
Я правильно понял, что переменная `numberOfFilms` используется только чтобы её прогнать в цикле?

2020-12-11 22:52 UTC, gochicus commented on lessons/how-to-use-objects/src/index.js
> +      personalMoviesDB.genres[ i ] = prompt(`Ваш любимый жанр № ${i}?`);
Помимо монструозности есть аргументы? Я убрал проверку на false, была лишняя, так что теперь получше. Мне такая структура кажется понятнее: массив заполняется, а уже в следующей строке к его элементам применяется проверка с помощью forEach. И всё в рамках одного цикла.

2020-12-12 07:29 UTC, TorinAsakura commented on lessons/how-to-use-objects/src/index.js
> +      personalMoviesDB.genres[ i ] = prompt(`Ваш любимый жанр № ${i}?`);
> @themetronome Помимо монструозности есть аргументы? Я убрал проверку на false, была лишняя, так что теперь получше. Мне такая структура кажется понятнее: массив заполняется, а уже в следующей строке к его элементам применяется проверка с помощью forEach. И всё в рамках одного цикла.

https://habr.com/ru/post/328584/

2020-12-12 14:56 UTC, themetronome requested changes
Форматирование кода

2020-12-12 15:07 UTC, themetronome approved these changes

2020-12-12 16:31 UTC, merged